// Shared FR/EN scenarios. All patient values and coefficients below are synthetic.
/** @typedef {import('../learning/types').Localized} Localized */
/** @typedef {import('../learning/types').NumericStep} NumericStep */
/** @typedef {import('../learning/types').SelectStep} SelectStep */
/** @param {string} fr @param {string} en */
const l = (fr, en) => ({ fr, en });
/** @param {string} id @param {Localized} prompt @param {number} answer @param {string} unit @param {Localized} correction @param {Partial<NumericStep>} extra @returns {NumericStep} */
const numeric = (id, prompt, answer, unit, correction, extra = {}) => ({
  id, type: 'numeric', prompt, answer, unit, correction,
  tolerance: { kind: 'absolute', value: 0.02 }, ...extra
});
/** @param {string} id @param {Localized} prompt @param {Localized[]} options @param {number[]} correct @param {Localized} correction @param {Partial<SelectStep>} extra @returns {SelectStep} */
const select = (id, prompt, options, correct, correction, extra = {}) => ({ id, type: 'select', prompt, options, correct, correction, ...extra });
/** @param {string} id @param {Localized} prompt @param {Localized[]} rubric @param {Localized} correction @returns {import('../learning/types').ReflectionStep} */
const reflect = (id, prompt, rubric, correction) => ({ id, type: 'reflection', prompt, rubric, correction });
const basic = 'covariates-basics', groups = 'covariates-groups', phys = 'covariates-physiology', symbolic = 'covariates-symbolic', impl = 'covariates-implementation';
/** @param {number} weight */
const cl = weight => 4 * (weight / 70) ** 0.75;

/** @type {import('../learning/types').Activity[]} */
export const covariateActivities = [
  {
    id: 'cov-weight-eta', chapter: basic, minutes: 8, difficulty: 1,
    title: l('Du poids à la clairance individuelle', 'From weight to individual clearance'),
    objective: l('Séparer valeur typique et écart individuel.', 'Separate the typical value from the individual deviation.'),
    context: l('Modèle fictif : CLtyp = 4 (WT/70)^0,75 L/h. Domaine illustré : 40–90 kg. Le patient pèse 50 kg. CLi = CLtyp × exp(ETA).', 'Fictional model: CLtyp = 4 (WT/70)^0.75 L/h. Illustrated domain: 40–90 kg. The patient weighs 50 kg. CLi = CLtyp × exp(ETA).'),
    sources: ['monolix-covariates', 'sanghavi-covariates'],
    steps: [
      numeric('predict', l('Avant de voir le graphique, calculez CLtyp à 50 kg.', 'Before seeing the graph, calculate CLtyp at 50 kg.'), cl(50), 'L/h', l('4 × (50/70)^0,75 = 3,108 L/h. Le rapport de poids est sans unité ; 4 porte l’unité L/h.', '4 × (50/70)^0.75 = 3.108 L/h. The weight ratio is dimensionless; 4 carries the L/h unit.'), {
        units: ['L/h', 'L', 'h'], hints: [l('Commencez par WT/70, pas par WT seul.', 'Start with WT/70, not WT alone.'), l('La puissance s’applique au rapport entier.', 'Apply the power to the whole ratio.')],
        commonErrors: [{ value: 4 * 50 / 70, feedback: l('Vous avez utilisé une relation proportionnelle (bêta = 1). Ici bêta vaut 0,75.', 'You used a proportional relationship (beta = 1). Here beta is 0.75.') }]
      }),
      numeric('individual', l('Examinez le graphique. Pour ETA = 0,2, calculez maintenant CLi du même patient.', 'Inspect the graph. With ETA = 0.2, now calculate CLi for the same patient.'), cl(50) * Math.exp(0.2), 'L/h', l('CLi = 3,108 × exp(0,2) ≈ 3,796 L/h. Ajouter 0,2 directement à CL serait incorrect : l’ETA est additif sur log(CL).', 'CLi = 3.108 × exp(0.2) ≈ 3.796 L/h. Adding 0.2 directly to CL is incorrect: ETA is additive on log(CL).'), {
        visual: { lesson: 'basics', value: 50, settings: { eta: 0.2 } },
        commonErrors: [{ value: cl(50) + 0.2, feedback: l('L’ETA n’est pas une quantité en L/h : utilisez exp(ETA).', 'ETA is not a quantity in L/h: use exp(ETA).') }], hints: [l('Un ETA positif multiplie CLtyp par un facteur supérieur à 1.', 'A positive ETA multiplies CLtyp by a factor greater than 1.')]
      }),
      reflect('reason', l('Deux patients de 50 kg ont-ils nécessairement la même CL ? Justifiez.', 'Must two 50 kg patients have the same CL? Explain.'), [l('Distinguer CLtyp et CLi.', 'Distinguish CLtyp from CLi.'), l('Mentionner les ETA et les autres caractéristiques non prises en compte.', 'Mention ETAs and other unmodeled characteristics.')], l('Ils partagent la valeur typique conditionnelle aux mêmes covariables du modèle, pas nécessairement leur paramètre individuel. La covariable n’explique pas toute l’hétérogénéité.', 'They share the typical value conditional on the same modeled covariates, not necessarily their individual parameter. The covariate does not explain all heterogeneity.'))
    ]
  },
  {
    id: 'cov-dispersion', chapter: basic, minutes: 7, difficulty: 2,
    title: l('Changer la relation ou changer la dispersion ?', 'Change the relationship or the dispersion?'),
    objective: l('Distinguer bêta, omega et variance résiduelle.', 'Distinguish beta, omega and residual variance.'),
    context: l('Le nuage représente des paramètres CL individuels simulés, pas des concentrations mesurées. ETA suit N(0, omega²).', 'The cloud shows simulated individual CL parameters, not measured concentrations. ETA follows N(0, omega²).'), sources: ['monolix-covariates', 'simulx-individual'],
    steps: [
      select('predict', l('Si omega passe de 0,3 à 0 sans modifier bêta, quelles propositions sont correctes ?', 'If omega changes from 0.3 to 0 without changing beta, which statements are correct?'), [
        l('La courbe typique reste identique.', 'The typical curve remains unchanged.'), l('La dispersion conditionnelle des CL disparaît.', 'Conditional CL dispersion disappears.'), l('La relation poids–CL disparaît.', 'The weight–CL relationship disappears.'), l('Toute erreur de mesure disparaît forcément.', 'All measurement error necessarily disappears.')
      ], [0, 1], l('Omega contrôle ici les ETA. Bêta continue de décrire la relation au poids. SIGMA n’est ni modifié ni représenté dans ce nuage de paramètres.' , 'Omega controls ETAs here. Beta still describes the weight relationship. SIGMA is neither changed nor represented in this parameter cloud.')),
      { id: 'experiment', type: 'tune', prompt: l('Dans l’animation, supprimez la dispersion et rendez CL indépendante du poids : ajustez omega et bêta.', 'In the animation, remove dispersion and make CL independent of weight: adjust omega and beta.'), visual: { lesson: 'basics', value: 70 }, targets: { omega: 0, beta: 0 }, correction: l('Avec omega = 0 et bêta = 0, tous les CL simulés valent 4 L/h. Il s’agit d’un changement du modèle, pas d’une démonstration que le poids est sans effet dans une population réelle.', 'With omega = 0 and beta = 0, all simulated CL values equal 4 L/h. This changes the model; it does not establish that weight has no effect in a real population.'), hints: [l('Un exposant nul annule l’effet du rapport WT/70.', 'A zero exponent removes the effect of WT/70.')] },
      numeric('variance', l('Pour omega = 0,3, quelle est la variance de l’ETA ?', 'For omega = 0.3, what is the ETA variance?'), 0.09, '', l('La variance vaut omega² = 0,09, et non 0,3. Elle porte sur l’ETA de log(CL), pas sur CL en L/h.', 'The variance is omega² = 0.09, not 0.3. It applies to the ETA of log(CL), not to CL in L/h.'), { tolerance: { kind: 'absolute', value: 0.001 } })
    ]
  },
  {
    id: 'cov-category-code', chapter: groups, minutes: 7, difficulty: 1,
    title: l('Coder un ratio de catégorie', 'Encode a category ratio'),
    objective: l('Passer d’un ratio à un coefficient sur l’échelle logarithmique.', 'Convert a ratio to a coefficient on the log scale.'),
    context: l('B est la référence : CLB = 4 L/h. CL = 4 exp(betaA × I(A) + betaC × I(C)), ETA = 0. Ratios A/B = 0,7 et C/B = 1,3.', 'B is the reference: CLB = 4 L/h. CL = 4 exp(betaA × I(A) + betaC × I(C)), ETA = 0. Ratios A/B = 0.7 and C/B = 1.3.'), sources: ['monolix-covariates'],
    steps: [
      numeric('coefficient', l('Quelle valeur faut-il coder pour betaA ?', 'What value should be used for betaA?'), Math.log(0.7), '', l('betaA = ln(0,7) ≈ −0,3567. exp(betaA) restitue le ratio 0,7.', 'betaA = ln(0.7) ≈ −0.3567. exp(betaA) recovers the ratio 0.7.'), { tolerance: { kind: 'absolute', value: 0.005 }, commonErrors: [{ value: 0.7, feedback: l('0,7 est le ratio, pas son logarithme. exp(0,7) ferait augmenter CL.', '0.7 is the ratio, not its logarithm. exp(0.7) would increase CL.') }], hints: [l('Résolvez exp(betaA) = 0,7.', 'Solve exp(betaA) = 0.7.')] }),
      numeric('category', l('Calculez CL pour la catégorie C, puis comparez les catégories dans l’animation.', 'Calculate CL for category C, then compare categories in the animation.'), 5.2, 'L/h', l('CL(C) = 4 × 1,3 = 5,2 L/h. Les codes A/B/C sont des catégories, pas une échelle numérique continue.', 'CL(C) = 4 × 1.3 = 5.2 L/h. A/B/C are categories, not a continuous numeric scale.'), { visual: { lesson: 'groups', value: 2 } }),
      reflect('unseen', l('Un nouveau patient a une catégorie D absente des données. Comment traiter cette situation ?', 'A new patient belongs to category D, absent from the data. How should this be handled?'), [l('Ne pas interpoler entre codes arbitraires.', 'Do not interpolate between arbitrary codes.'), l('Ne pas remplacer D silencieusement par B.', 'Do not silently replace D with B.'), l('Documenter une règle justifiée ou signaler que le modèle ne couvre pas D.', 'Document a justified rule or report that the model does not cover D.')], l('Une catégorie inconnue n’a pas d’effet estimé. Une règle de regroupement ou de repli doit être justifiée et évaluée ; le code informatique seul ne peut inventer ce contraste.', 'An unknown category has no estimated effect. Grouping or fallback rules need justification and evaluation; software alone cannot invent the contrast.'))
    ]
  },
  {
    id: 'cov-threshold', chapter: groups, minutes: 8, difficulty: 2,
    title: l('Deux patients de part et d’autre d’un seuil', 'Two patients on either side of a threshold'),
    objective: l('Identifier une discontinuité artificielle et une fuite d’information.', 'Identify an artificial discontinuity and information leakage.'),
    context: l('Paliers fictifs : CL = 2,8 L/h si WT < 60 kg, 4 si 60 ≤ WT < 90, 5,2 sinon. Ce ne sont pas des seuils cliniques.', 'Fictional thresholds: CL = 2.8 L/h if WT < 60 kg, 4 if 60 ≤ WT < 90, and 5.2 otherwise. These are not clinical thresholds.'), sources: ['sanghavi-covariates', 'hastie-esl'],
    steps: [
      numeric('jump', l('Quel saut de CL le modèle impose-t-il entre 59,9 et 60,1 kg ?', 'What CL jump does the model impose between 59.9 and 60.1 kg?'), 1.2, 'L/h', l('Le saut vaut 4 − 2,8 = 1,2 L/h pour seulement 0,2 kg de différence. Il provient du palier imposé.', 'The jump is 4 − 2.8 = 1.2 L/h for only 0.2 kg difference. It comes from the imposed threshold.'), { visual: { lesson: 'groups', value: 59.9, settings: { grouping: 'threshold' } } }),
      select('validation', l('Vous souhaitez apprendre des groupes. Quelles étapes évitent la fuite d’information ?', 'You want to learn groups. Which steps avoid information leakage?'), [l('Apprendre la standardisation et les groupes dans l’entraînement.', 'Learn standardization and groups within training.'), l('Figer l’affectation avant l’évaluation indépendante.', 'Freeze assignment before independent evaluation.'), l('Utiliser l’AUC du test pour choisir ses groupes.', 'Use test AUC to choose its groups.'), l('Réestimer les étapes apprises dans chaque pli d’entraînement.', 'Re-estimate learned steps inside each training fold.')], [0, 1, 3], l('Les observations de test ne doivent déterminer ni la transformation ni les groupes. L’appartenance doit pouvoir être calculée avec les informations disponibles au moment de la prédiction.', 'Test observations must determine neither transformations nor groups. Membership must be computable from information available at prediction time.')),
      reflect('decision', l('Le modèle à paliers ajuste mieux l’entraînement. Est-ce suffisant pour le préférer à une relation continue ?', 'The threshold model fits training better. Is this enough to prefer it over a continuous relationship?'), [l('Comparer les performances hors entraînement.', 'Compare held-out performance.'), l('Examiner les patients proches du seuil et la plausibilité du saut.', 'Examine patients near the threshold and plausibility of the jump.'), l('Tenir compte de l’incertitude et des effectifs par groupe.', 'Consider uncertainty and group sizes.')], l('Non. Le gain d’ajustement peut provenir de la flexibilité ou de la sélection du seuil. Une décision défendable examine validation, stabilité et utilité du découpage.', 'No. Better fit may reflect flexibility or threshold selection. A defensible decision examines validation, stability and usefulness of the grouping.'))
    ]
  },
  {
    id: 'cov-maturation', chapter: phys, minutes: 8, difficulty: 2,
    title: l('Retrouver PMA50 par manipulation', 'Identify PMA50 through manipulation'),
    objective: l('Lire et contrôler une relation de Hill.', 'Read and check a Hill relationship.'),
    context: l('Illustration à taille fixée : CL = 4 PMA³ / (PMA50³ + PMA³) L/h. PMA et PMA50 sont en semaines. Aucune population pédiatrique réelle n’est représentée.', 'Fixed-size illustration: CL = 4 PMA³ / (PMA50³ + PMA³) L/h. PMA and PMA50 are in weeks. No real pediatric population is represented.'), sources: ['anderson-holford-allometry', 'goutelle-hill'],
    steps: [
      numeric('half', l('Si PMA = PMA50 = 50 semaines, quelle est CL ?', 'If PMA = PMA50 = 50 weeks, what is CL?'), 2, 'L/h', l('Numérateur et terme PMA50³ sont égaux : la fraction vaut 1/2 et CL vaut 2 L/h.', 'The numerator equals the PMA50³ term: the fraction is 1/2 and CL is 2 L/h.')),
      { id: 'identify', type: 'tune', prompt: l('Un point typique fictif donne CL = 2 L/h à PMA = 60 semaines. Retrouvez PMA50 dans l’animation, en gardant Hill = 3.', 'A fictional typical point gives CL = 2 L/h at PMA = 60 weeks. Find PMA50 in the animation, keeping Hill = 3.'), visual: { lesson: 'physiology', value: 60 }, targets: { half: 60, hill: 3 }, correction: l('PMA50 = 60 semaines. Un seul point à mi-hauteur fixe PMA50 si CLmax est connu, mais ne renseigne pas la pente de Hill ; celle-ci était fixée à 3.', 'PMA50 = 60 weeks. A single midpoint identifies PMA50 when CLmax is known, but does not identify the Hill slope; that was fixed at 3.'), hints: [l('Cherchez l’abscisse correspondant à la moitié de 4 L/h.', 'Find the x value corresponding to half of 4 L/h.')] },
      reflect('scope', l('Pourquoi cette courbe ne suffit-elle pas à constituer un PBPK ?', 'Why is this curve not sufficient to constitute a PBPK model?'), [l('Décrire le rôle limité de la fonction de maturation.', 'Describe the limited role of the maturation function.'), l('Mentionner la structure d’organes et les processus physiologiques absents.', 'Mention missing organ structure and physiological processes.')], l('La relation de Hill modifie un paramètre. Elle ne définit à elle seule ni organes, ni débits, ni distribution et élimination mécanistes.', 'The Hill relationship modifies one parameter. By itself it defines no organs, flows, or mechanistic distribution and elimination.'))
    ]
  },
  {
    id: 'cov-organ', chapter: phys, minutes: 6, difficulty: 2,
    title: l('Ne pas multiplier toute la clairance', 'Do not scale all clearance'),
    objective: l('Appliquer une covariable à la composante concernée.', 'Apply a covariate to the relevant component.'),
    context: l('Modèle fictif additif : CLtot = CLnr + CLr. À la référence : CLnr = 2 L/h et CLr = 3 L/h. Seule CLr est multipliée par le facteur rénal, qui vaut ici 0,4.', 'Fictional additive model: CLtot = CLnr + CLr. At reference: CLnr = 2 L/h and CLr = 3 L/h. Only CLr is scaled by the renal factor, here 0.4.'), sources: ['jones-rowland-yeo'],
    steps: [
      numeric('total', l('Calculez la clairance totale.', 'Calculate total clearance.'), 3.2, 'L/h', l('CLtot = 2 + 3 × 0,4 = 3,2 L/h. Multiplier 5 par 0,4 modifierait aussi la composante non rénale, contrairement aux hypothèses.', 'CLtot = 2 + 3 × 0.4 = 3.2 L/h. Multiplying 5 by 0.4 would also change nonrenal clearance, contrary to the assumptions.'), { commonErrors: [{ value: 2, feedback: l('Vous avez probablement multiplié toute la clairance par 0,4. La composante non rénale reste ici à 2 L/h.', 'You probably scaled all clearance by 0.4. Nonrenal clearance remains 2 L/h here.') }] }),
      numeric('limit', l('Sous ces hypothèses, quelle est CLtot lorsque le facteur rénal tend vers zéro ?', 'Under these assumptions, what is CLtot as the renal factor approaches zero?'), 2, 'L/h', l('CLtot tend vers CLnr = 2 L/h. Cette limite vérifie le code ; elle ne prouve pas que CLnr resterait constante chez de vrais patients.', 'CLtot approaches CLnr = 2 L/h. This limit checks the code; it does not prove CLnr would remain constant in real patients.')),
      reflect('assumptions', l('Quelle hypothèse faudrait-il vérifier avant d’appliquer cette règle à des patients ?', 'Which assumption should be examined before applying this rule to patients?'), [l('Vérifier quelles voies sont affectées et si CLnr peut changer.', 'Check which pathways are affected and whether CLnr may change.'), l('Vérifier la définition, les unités et le domaine du facteur rénal.', 'Check the definition, units and domain of the renal factor.')], l('La séparation des voies et leur dépendance aux covariables sont des hypothèses du modèle. Les limites numériques sont nécessaires, mais une validation dans la population visée reste distincte.', 'Pathway separation and covariate dependence are model assumptions. Numerical checks are necessary, but validation in the intended population is a separate requirement.'))
    ]
  },
  {
    id: 'cov-extrapolation', chapter: symbolic, minutes: 8, difficulty: 2,
    title: l('Une formule calculable hors de sa plage', 'A computable formula outside its range'),
    objective: l('Séparer calcul mathématique et domaine validé.', 'Separate mathematical calculation from validated scope.'),
    context: l('Formule candidate : CL = 4 (WT/70)^0,75 L/h. Le développement ne comprend que des poids entre 40 et 90 kg. Les courbes de l’étape suivante sont construites, pas ajustées aux patients simulés.', 'Candidate formula: CL = 4 (WT/70)^0.75 L/h. Development includes only weights from 40 to 90 kg. Curves in the next step are constructed, not fitted to simulated patients.'), sources: ['sanghavi-covariates', 'wahlquist-symbolic-covariates'],
    steps: [
      numeric('outside', l('Calculez la valeur renvoyée par la formule à 35 kg. Il s’agit uniquement d’un calcul.', 'Calculate the value returned by the formula at 35 kg. This is only a calculation.'), cl(35), 'L/h', l('La formule renvoie environ 2,378 L/h. 35 kg est hors de 40–90 kg : ce nombre n’établit pas une prédiction validée.', 'The formula returns about 2.378 L/h. 35 kg lies outside 40–90 kg: this number does not establish a validated prediction.')),
      select('domain', l('Explorez 20 et 200 kg. Quelles conclusions sont justifiées ?', 'Explore 20 and 200 kg. Which conclusions are justified?'), [l('Les courbes candidates peuvent diverger hors plage.', 'Candidate curves can diverge out of range.'), l('La formule la plus courte est automatiquement valide à 200 kg.', 'The shortest formula is automatically valid at 200 kg.'), l('Une extrapolation exige une justification et une validation spécifiques.', 'Extrapolation requires specific justification and validation.'), l('Un faible écart RMS entre courbes prouve une utilité clinique.', 'A small RMS deviation between curves proves clinical utility.')], [0, 2], l('L’accord des courbes dans la plage étudiée ne garantit pas leur comportement ailleurs. L’écart RMS illustré n’est pas une validation sur de nouveaux patients.', 'Agreement within the studied range does not guarantee behavior elsewhere. The illustrated RMS deviation is not validation on new patients.'), { visual: { lesson: 'symbolic', value: 200 } }),
      reflect('within', l('Un patient de 70 kg est-il automatiquement couvert par le modèle ?', 'Is a 70 kg patient automatically covered by the model?'), [l('Mentionner les autres covariables et la population.', 'Mention other covariates and the population.'), l('Distinguer une condition nécessaire d’une validation suffisante.', 'Distinguish a necessary condition from sufficient validation.')], l('Non : âge, pathologie, fonction d’organe, voie et conditions d’utilisation peuvent différer. Rester dans la plage de poids ne suffit pas à démontrer la transportabilité.', 'No: age, disease, organ function, route and use conditions may differ. Being within the weight range does not establish transportability.'))
    ]
  },
  {
    id: 'cov-symbolic-validation', chapter: symbolic, minutes: 7, difficulty: 3,
    title: l('Choisir une formule sans contaminer le test', 'Select a formula without contaminating the test'),
    objective: l('Séparer fidélité au réseau et performance prédictive.', 'Separate network fidelity from predictive performance.'),
    context: l('Chaque patient possède plusieurs prélèvements. Vous comparez un réseau et deux équations symboliques candidates.', 'Each patient has multiple samples. You compare a network and two candidate symbolic equations.'), sources: ['wahlquist-symbolic-covariates', 'hastie-esl'],
    steps: [
      select('split', l('Quelles décisions protègent l’évaluation finale ?', 'Which decisions protect the final evaluation?'), [l('Séparer les patients, pas leurs prélèvements.', 'Split patients, not their samples.'), l('Choisir l’équation sur le test final.', 'Choose the equation using the final test set.'), l('Apprendre les transformations uniquement dans l’entraînement.', 'Learn transformations only within training.'), l('Figer l’équation avant son évaluation finale.', 'Freeze the equation before final evaluation.')], [0, 2, 3], l('La sélection utilise entraînement et validation. Le test final évalue la procédure figée ; le réutiliser pour choisir la formule introduit de l’optimisme.', 'Selection uses training and validation. The final test evaluates the frozen procedure; reusing it to select the formula introduces optimism.')),
      reflect('zero', l('Une formule reproduit exactement le réseau : erreur formule–réseau = 0. Que manque-t-il pour conclure ?', 'A formula exactly reproduces the network: equation–network error = 0. What is still missing?'), [l('Évaluer les prédictions contre des observations indépendantes.', 'Evaluate predictions against independent observations.'), l('Examiner biais, précision, incertitude et domaine.', 'Examine bias, precision, uncertainty and domain.'), l('Ne pas confondre fidélité au réseau, causalité et utilité clinique.', 'Do not confuse network fidelity, causality and clinical utility.')], l('La fidélité à un prédicteur ne prouve pas que ce prédicteur est correct. Il faut évaluer l’équation finale, y compris sa variabilité et ses limites, sur des observations non utilisées pour la sélectionner.', 'Fidelity to a predictor does not prove that predictor is correct. Evaluate the final equation, including variability and limitations, against observations not used to select it.'))
    ]
  },
  {
    id: 'cov-code-check', chapter: impl, minutes: 9, difficulty: 2,
    title: l('Retrouver une erreur dans le code', 'Find an error in the code'),
    objective: l('Contrôler référence, exposant et cibles multiples.', 'Check reference, exponent and multiple targets.'),
    context: l('Contrat : CL = 4 (WT/70)^0,75 × 1,3^GENO ; V = 30 WT/70 ; ETA = 0. GENO vaut 0 ou 1. Contrôle : WT = 50 kg, GENO = 1.', 'Contract: CL = 4 (WT/70)^0.75 × 1.3^GENO; V = 30 WT/70; ETA = 0. GENO is 0 or 1. Check: WT = 50 kg, GENO = 1.'), sources: ['monolix-covariates', 'mrgsolve'],
    steps: [
      numeric('cl', l('Quelle CL devrait produire une implémentation correcte ?', 'What CL should a correct implementation produce?'), cl(50) * 1.3, 'L/h', l('CL = 4 × (50/70)^0,75 × 1,3 ≈ 4,040 L/h.', 'CL = 4 × (50/70)^0.75 × 1.3 ≈ 4.040 L/h.')),
      numeric('v', l('Quel V doit-elle produire ? Le génotype agit uniquement sur CL.', 'What V should it produce? Genotype acts only on CL.'), 30 * 50 / 70, 'L', l('V = 30 × 50/70 ≈ 21,429 L. L’exposant du poids sur V vaut 1 ; ce n’est pas celui de CL.', 'V = 30 × 50/70 ≈ 21.429 L. The weight exponent on V is 1, not the exponent on CL.'), { visual: { lesson: 'implementation', value: 50, settings: { genotype: 1 } } }),
      select('bugs', l('Ce code respecte-t-il le contrat ? Sélectionnez les deux erreurs.', 'Does this code match the contract? Select both errors.'), [l('L’unité du poids doit être la minute.', 'Weight must use minutes.'), l('La division doit être à l’intérieur de pow pour CL.', 'The division must be inside pow for CL.'), l('Le génotype ne doit pas multiplier V.', 'Genotype must not scale V.'), l('CL et V doivent forcément avoir le même exposant.', 'CL and V must have the same exponent.')], [1, 2], l('Corrections : pow(WT/70.0, 0.75) dans CL ; V = 30*WT/70.0. Tester uniquement WT = 70 et GENO = 0 ne détecterait pas tous les problèmes possibles.', 'Corrections: pow(WT/70.0, 0.75) in CL; V = 30*WT/70.0. Testing only WT = 70 and GENO = 0 would not detect all possible problems.'), { code: 'double CL = 4*pow(WT, 0.75)/70.0*pow(1.3, GENO);\ndouble V = 30*WT/70.0*pow(1.3, GENO);' })
    ]
  },
  {
    id: 'cov-omega-time', chapter: impl, minutes: 8, difficulty: 3,
    title: l('OMEGA et covariable dépendante du temps', 'OMEGA and a time-varying covariate'),
    objective: l('Vérifier une covariance et les informations disponibles à la prédiction.', 'Check covariance and information available at prediction time.'),
    context: l('OMEGA = [[0,09 ; 0,03], [0,03 ; 0,04]]. Une fonction d’organe est mesurée à t = 0 h et à t = 12 h. La prévision est produite à t = 6 h.', 'OMEGA = [[0.09, 0.03], [0.03, 0.04]]. Organ function is measured at t = 0 h and t = 12 h. The forecast is made at t = 6 h.'), sources: ['simulx-individual', 'monolix-covariates'],
    steps: [
      numeric('correlation', l('Calculez la corrélation entre les deux ETA.', 'Calculate the correlation between the two ETAs.'), 0.5, '', l('rho = 0,03 / (sqrt(0,09) × sqrt(0,04)) = 0,5. La covariance 0,03 n’est pas la corrélation.', 'rho = 0.03 / (sqrt(0.09) × sqrt(0.04)) = 0.5. The covariance 0.03 is not the correlation.'), { commonErrors: [{ value: 0.03, feedback: l('Divisez la covariance par le produit des écarts-types.', 'Divide covariance by the product of standard deviations.') }] }),
      select('time', l('À t = 6 h, quelles affirmations sont correctes ?', 'At t = 6 h, which statements are correct?'), [l('La mesure future à 12 h est déjà disponible.', 'The future 12 h measurement is already available.'), l('Reporter la valeur de 0 h est une hypothèse possible, à expliciter.', 'Carrying the 0 h value forward is a possible assumption to state explicitly.'), l('Interpoler avec la future mesure de 12 h ferait fuiter de l’information.', 'Interpolating with the future 12 h measurement would leak information.'), l('LOCF garantit que la fonction d’organe est réellement constante.', 'LOCF guarantees organ function is truly constant.')], [1, 2], l('Une analyse rétrospective peut utiliser des données ultérieures si cela est explicite. Une prévision à 6 h ne doit pas bénéficier de la mesure de 12 h ; LOCF reste une hypothèse, pas une certitude.', 'A retrospective analysis may use later data if explicit. A forecast at 6 h must not benefit from the 12 h measurement; LOCF remains an assumption, not a certainty.'))
    ]
  },
  {
    id: 'cov-synthesis', chapter: impl, minutes: 15, difficulty: 3,
    title: l('Cas de synthèse : même C0, même exposition ?', 'Integrated case: same C0, same exposure?'),
    objective: l('Relier covariables, profil PK, exposition et domaine d’application.', 'Connect covariates, PK profile, exposure and applicability.'),
    context: l('Cas synthétique : bolus IV unique de 100 mg à t = 0 ; aucun traitement antérieur ; V = 30 L identique ; CL = 4 (WT/70)^0,75 ; ETA et erreur de mesure nuls. A pèse 50 kg, B 80 kg. Domaine du modèle : 40–90 kg. C0 désigne ici C(0+) après bolus, pas une résiduelle.', 'Synthetic case: single 100 mg IV bolus at t = 0; no previous treatment; same V = 30 L; CL = 4 (WT/70)^0.75; no ETA or measurement error. A weighs 50 kg, B 80 kg. Model domain: 40–90 kg. Here C0 means C(0+) after bolus, not a trough.'), sources: ['sanghavi-covariates', 'monolix-covariates'],
    steps: [
      numeric('initial', l('Calculez C(0+) commune aux deux patients.', 'Calculate C(0+), shared by both patients.'), 100 / 30, 'mg/L', l('C(0+) = Dose/V = 100/30 ≈ 3,333 mg/L. Ce point initial ne dépend pas de CL dans ce modèle.', 'C(0+) = Dose/V = 100/30 ≈ 3.333 mg/L. This initial point does not depend on CL in this model.'), { units: ['mg/L', 'mg.h/L', 'L/h'] }),
      numeric('exposure', l('Calculez le ratio AUC(0,infini) de A sur B avant de voir les profils.', 'Calculate A/B AUC(0,infinity) ratio before seeing the profiles.'), cl(80) / cl(50), '', l('AUC = Dose/CL pour ce bolus IV linéaire. AUC(A)/AUC(B) = CL(B)/CL(A) ≈ 1,423. AUC(A) ≈ 32,18 et AUC(B) ≈ 22,62 mg.h/L.', 'AUC = Dose/CL for this linear IV bolus. AUC(A)/AUC(B) = CL(B)/CL(A) ≈ 1.423. AUC(A) ≈ 32.18 and AUC(B) ≈ 22.62 mg.h/L.'), { tolerance: { kind: 'relative', value: 0.01 }, hints: [l('À dose identique, le ratio d’AUC est l’inverse du ratio des clairances.', 'At the same dose, the AUC ratio is the inverse of the clearance ratio.')], commonErrors: [{ value: cl(50) / cl(80), feedback: l('Vous avez inversé le ratio : une CL plus faible donne ici une AUC plus élevée.', 'You inverted the ratio: lower CL gives higher AUC here.') }] }),
      reflect('profiles', l('Expliquez comment C(0+) peut être identique alors que les expositions diffèrent. Que manque-t-il si l’on ne connaît que deux concentrations résiduelles égales ?', 'Explain how C(0+) can be identical while exposures differ. What is missing if all we know is that two trough concentrations are equal?'), [l('Relier C(0+) à Dose/V et la décroissance à CL/V.', 'Relate C(0+) to Dose/V and decline to CL/V.'), l('Distinguer concentration ponctuelle et intégrale AUC.', 'Distinguish a single concentration from the AUC integral.'), l('Pour des résiduelles : préciser doses, horaires, voie, état stationnaire et modèle.', 'For troughs: specify doses, times, route, steady state and model.')], l('Les profils partent au même niveau, mais A décroît plus lentement. Deux résiduelles égales sans autre information ne déterminent pas les AUC : la conclusion du cas dépend des hypothèses explicites.', 'Profiles start at the same level, but A declines more slowly. Equal troughs alone do not determine AUCs: this case conclusion depends on the explicit assumptions.')),
      reflect('decision', l('Un troisième patient pèse 200 kg. Vous obtenez une CL en évaluant la formule. Rédigez votre conclusion et les vérifications nécessaires avant utilisation.', 'A third patient weighs 200 kg. Evaluating the formula returns a CL. Write your conclusion and the checks needed before use.'), [l('Identifier explicitement l’extrapolation hors de 40–90 kg.', 'Explicitly identify extrapolation outside 40–90 kg.'), l('Demander une justification et une évaluation dans la population visée.', 'Require justification and evaluation in the intended population.'), l('Ne pas proposer une adaptation clinique à partir de ce seul exemple fictif.', 'Do not propose clinical adjustment from this fictional example alone.')], l('La formule est calculable, mais son emploi à 200 kg n’est pas validé par cet exercice. Des données adaptées, la plausibilité de la structure et l’incertitude doivent être examinées avant toute utilisation.', 'The formula is computable, but its use at 200 kg is not validated by this exercise. Appropriate data, structural plausibility and uncertainty must be examined before use.'))
    ]
  }
];

/** @param {string} slug */
export const activitiesForChapter = slug => covariateActivities.filter(activity => activity.chapter === slug);

export const covariateObjectives = [
  l('Séparer effet fixe, ETA, OMEGA et erreur de mesure.', 'Separate fixed effects, ETA, OMEGA and measurement error.'),
  l('Calculer, manipuler et interpréter une relation covariable–paramètre.', 'Calculate, manipulate and interpret a covariate–parameter relationship.'),
  l('Choisir des contrôles numériques et une stratégie de validation.', 'Choose numerical checks and a validation strategy.'),
  l('Reconnaître les limites de la population et de la plage étudiées.', 'Recognize population and studied-range limitations.')
];
