// Exercices interactifs de pharmacométrie, inspirés des corrigés M2.
// Chaque exercice porte un champ `chapter` (slug) : il s'affiche sur la page globale
// /exercices (groupé par `cat`) ET à la fin du chapitre correspondant.
// Bilingue : `q`/`explain`/`options` en français ; `en:{q,explain,options}` en anglais
// (repli sur le FR si absent). L'ordre des options et l'index `correct` sont partagés.
// type "num" : réponse numérique (tolérance relative tol) ; type "mcq" : choix.

/** @typedef {{q:string, explain:string, options?:string[]}} ExerciseI18n */
/** @typedef {{cat:string, chapter:string, type:'num'|'mcq', q:string, unit?:string, answer?:number, tol?:number, options?:string[], correct?:number, explain:string, en?:ExerciseI18n}} Exercise */

/** @type {Exercise[]} */
export const exercises = [
  // ═══ CŒUR : paramètres PK & compartiments ═══
  { cat: 'Pharmacocinétique de base', chapter: 'clairance-volume-demi-vie', type: 'num', unit: 'h', answer: 3.47, tol: 0.05,
    q: "Après un bolus IV, la droite ln(C) vs temps a une pente de −0,20 /h. Quelle est la demi-vie d'élimination ?",
    explain: "La pente donne ke = 0,20 /h. t½ = ln(2)/ke = 0,693/0,20 ≈ 3,47 h.",
    en: { q: "After an IV bolus, the ln(C) vs time line has a slope of −0.20 /h. What is the elimination half-life?", explain: "The slope gives ke = 0.20 /h. t½ = ln(2)/ke = 0.693/0.20 ≈ 3.47 h." } },
  { cat: 'Pharmacocinétique de base', chapter: 'clairance-volume-demi-vie', type: 'num', unit: 'L', answer: 5, tol: 0.02,
    q: "Bolus IV de 10 mg. L'ordonnée à l'origine de ln(C) donne C₀ = 2 mg/L. Quel est le volume de distribution Vd ?",
    explain: "Vd = Dose / C₀ = 10 mg / 2 mg/L = 5 L.",
    en: { q: "IV bolus of 10 mg. The ln(C) intercept gives C₀ = 2 mg/L. What is the volume of distribution Vd?", explain: "Vd = Dose / C₀ = 10 mg / 2 mg/L = 5 L." } },
  { cat: 'Pharmacocinétique de base', chapter: 'clairance-volume-demi-vie', type: 'num', unit: 'L/h', answer: 1, tol: 0.05,
    q: "Avec ke = 0,20 /h et Vd = 5 L, quelle est la clairance CL ?",
    explain: "CL = ke · Vd = 0,20 × 5 = 1 L/h.",
    en: { q: "With ke = 0.20 /h and Vd = 5 L, what is the clearance CL?", explain: "CL = ke · Vd = 0.20 × 5 = 1 L/h." } },
  { cat: 'Pharmacocinétique de base', chapter: 'clairance-volume-demi-vie', type: 'num', unit: 'h', answer: 3.47, tol: 0.05,
    q: "Un modèle donne CL = 6 L/h et V = 30 L. Quelle est la demi-vie ?",
    explain: "t½ = ln(2)·V/CL = 0,693 × 30 / 6 ≈ 3,47 h.",
    en: { q: "A model gives CL = 6 L/h and V = 30 L. What is the half-life?", explain: "t½ = ln(2)·V/CL = 0.693 × 30 / 6 ≈ 3.47 h." } },
  { cat: 'Pharmacocinétique de base', chapter: 'clairance-volume-demi-vie', type: 'mcq', correct: 0,
    q: "La clairance représente…",
    options: ["le volume de sang totalement épuré par unité de temps", "la quantité totale de médicament", "la vitesse d'absorption"],
    explain: "CL = volume épuré / temps ; c'est le paramètre d'élimination fondamental (AUC = Dose/CL).",
    en: { q: "Clearance represents…", options: ["the volume of blood fully cleared per unit time", "the total amount of drug", "the absorption rate"], explain: "CL = volume cleared / time; the fundamental elimination parameter (AUC = Dose/CL)." } },

  // ═══ Intro & approches ═══
  { cat: 'Pharmacocinétique de base', chapter: 'pourquoi-pharmacometrie', type: 'mcq', correct: 1,
    q: "La pharmacocinétique (PK) décrit…",
    options: ["l'effet du médicament sur le corps", "ce que le corps fait au médicament (ADME)", "la structure chimique"],
    explain: "PK = devenir du médicament (absorption, distribution, métabolisme, excrétion). La PD = effet du médicament.",
    en: { q: "Pharmacokinetics (PK) describes…", options: ["the drug's effect on the body", "what the body does to the drug (ADME)", "the chemical structure"], explain: "PK = the drug's fate (absorption, distribution, metabolism, excretion). PD = the drug's effect." } },
  { cat: 'Pharmacocinétique de base', chapter: 'trois-approches', type: 'mcq', correct: 2,
    q: "Pour extrapoler via la physiologie (inter-espèces, pédiatrie), on choisit…",
    options: ["la NCA", "un modèle empirique de population seul", "la PBPK"],
    explain: "La PBPK repose sur des organes/débits physiologiques, ce qui permet l'extrapolation mécaniste.",
    en: { q: "To extrapolate via physiology (cross-species, paediatrics), you choose…", options: ["NCA", "an empirical population model alone", "PBPK"], explain: "PBPK rests on physiological organs/flows, enabling mechanistic extrapolation." } },

  // ═══ Absorption, perfusion & doses ═══
  { cat: 'Absorption, perfusion & doses', chapter: 'absorption-orale', type: 'mcq', correct: 0,
    q: "Un phénomène de « flip-flop » survient quand…",
    options: ["l'absorption est plus lente que l'élimination (ka < ke)", "la dose est trop forte", "le volume est nul"],
    explain: "Si ka < ke, la pente terminale reflète l'absorption, pas l'élimination : les rôles s'inversent.",
    en: { q: "A 'flip-flop' phenomenon occurs when…", options: ["absorption is slower than elimination (ka < ke)", "the dose is too high", "the volume is zero"], explain: "If ka < ke, the terminal slope reflects absorption, not elimination: the roles swap." } },
  { cat: 'Absorption, perfusion & doses', chapter: 'perfusion', type: 'num', unit: 'mg/L', answer: 6, tol: 0.02,
    q: "Perfusion IV à débit R₀ = 30 mg/h, clairance CL = 5 L/h. Quelle est la concentration à l'équilibre Css ?",
    explain: "Css = R₀ / CL = 30 / 5 = 6 mg/L (indépendant du volume).",
    en: { q: "IV infusion at rate R₀ = 30 mg/h, clearance CL = 5 L/h. What is the steady-state concentration Css?", explain: "Css = R₀ / CL = 30 / 5 = 6 mg/L (independent of volume)." } },
  { cat: 'Absorption, perfusion & doses', chapter: 'perfusion', type: 'mcq', correct: 0,
    q: "Doubler le débit de perfusion R₀…",
    options: ["double la Css, sans changer le temps pour l'atteindre", "atteint la Css deux fois plus vite", "ne change pas la Css"],
    explain: "R₀ fixe le niveau (Css = R₀/CL) ; le temps d'atteinte (~4–5 t½) dépend de la demi-vie, pas du débit.",
    en: { q: "Doubling the infusion rate R₀…", options: ["doubles Css, without changing the time to reach it", "reaches Css twice as fast", "does not change Css"], explain: "R₀ sets the level (Css = R₀/CL); the time to reach it (~4–5 t½) depends on half-life, not rate." } },
  { cat: 'Absorption, perfusion & doses', chapter: 'doses-repetees', type: 'num', unit: 'mg/L', answer: 2.5, tol: 0.02,
    q: "Doses répétées : 100 mg toutes les 8 h, CL = 5 L/h. Quelle est la Css moyenne ?",
    explain: "Css,moy = Dose / (CL · τ) = 100 / (5 × 8) = 2,5 mg/L.",
    en: { q: "Repeated doses: 100 mg every 8 h, CL = 5 L/h. What is the average Css?", explain: "Css,avg = Dose / (CL · τ) = 100 / (5 × 8) = 2.5 mg/L." } },
  { cat: 'Absorption, perfusion & doses', chapter: 'doses-repetees', type: 'num', unit: '', answer: 1.82, tol: 0.05,
    q: "Bolus répétés, ke = 0,10 /h, intervalle τ = 8 h. Quel est le ratio d'accumulation Rac = 1/(1 − e^(−ke·τ)) ?",
    explain: "e^(−0,10×8) = e^(−0,8) ≈ 0,449 ; Rac = 1/(1 − 0,449) ≈ 1,82.",
    en: { q: "Repeated boluses, ke = 0.10 /h, interval τ = 8 h. What is the accumulation ratio Rac = 1/(1 − e^(−ke·τ))?", explain: "e^(−0.10×8) = e^(−0.8) ≈ 0.449; Rac = 1/(1 − 0.449) ≈ 1.82." } },
  { cat: 'Absorption, perfusion & doses', chapter: 'doses-repetees', type: 'mcq', correct: 2,
    q: "Une dose de charge sert surtout à…",
    options: ["diminuer la Css finale", "changer la demi-vie", "atteindre plus vite la fenêtre thérapeutique"],
    explain: "La dose de charge amène tout de suite dans la fenêtre ; l'entretien maintient la Css.",
    en: { q: "A loading dose mainly serves to…", options: ["lower the final Css", "change the half-life", "reach the therapeutic window faster"], explain: "The loading dose brings you into the window immediately; maintenance keeps Css." } },

  // ═══ Cinétique ═══
  { cat: 'Pharmacocinétique de base', chapter: 'perfusion', type: 'mcq', correct: 1,
    q: "Une vitesse d'élimination CONSTANTE, quelle que soit la concentration, correspond à…",
    options: ["un ordre 1", "un ordre 0", "un ordre 2"],
    explain: "Ordre 0 : vitesse constante (ex. enzyme saturée, perfusion). Ordre 1 : vitesse proportionnelle à C.",
    en: { q: "A CONSTANT elimination rate, regardless of concentration, corresponds to…", options: ["first order", "zero order", "second order"], explain: "Zero order: constant rate (e.g. saturated enzyme, infusion). First order: rate proportional to C." } },

  // ═══ Variabilité ═══
  { cat: 'Maths & covariables', chapter: 'variabilite-iiv-iov', type: 'mcq', correct: 1,
    q: "La variabilité inter-individuelle (IIV) décrit…",
    options: ["l'erreur de mesure de l'automate", "les différences de paramètres entre patients", "la variation d'une dose à l'autre chez un même patient"],
    explain: "IIV = différences entre patients (η) ; l'IOV varie entre occasions ; l'erreur résiduelle inclut la mesure.",
    en: { q: "Inter-individual variability (IIV) describes…", options: ["the assay measurement error", "parameter differences between patients", "the dose-to-dose variation within one patient"], explain: "IIV = differences between patients (η); IOV varies between occasions; residual error includes measurement." } },

  // ═══ Covariables & maths ═══
  { cat: 'Maths & covariables', chapter: 'allometrie', type: 'num', unit: 'L/h', answer: 2.97, tol: 0.05,
    q: "Allométrie : CL₇₀ = 5 L/h (patient de 70 kg). Quelle CL pour un enfant de 35 kg (exposant 0,75) ?",
    explain: "CL = 5 · (35/70)^0,75 = 5 · 0,5^0,75 ≈ 5 × 0,595 ≈ 2,97 L/h. Un enfant n'est pas un petit adulte.",
    en: { q: "Allometry: CL₇₀ = 5 L/h (70 kg patient). What CL for a 35 kg child (exponent 0.75)?", explain: "CL = 5 · (35/70)^0.75 = 5 · 0.5^0.75 ≈ 5 × 0.595 ≈ 2.97 L/h. A child is not a small adult." } },
  { cat: 'Maths & covariables', chapter: 'allometrie', type: 'mcq', correct: 0,
    q: "Centrer le poids à 70 kg dans le modèle permet surtout de…",
    options: ["garder le paramètre typique interprétable", "rendre tous les patients à 70 kg", "supprimer les diagnostics"],
    explain: "Le centrage fait de CL₇₀ la clairance du patient de référence et décorrèle θ de l'effet covariable.",
    en: { q: "Centering weight at 70 kg in the model mainly serves to…", options: ["keep the typical parameter interpretable", "make all patients 70 kg", "remove diagnostics"], explain: "Centering makes CL₇₀ the reference patient's clearance and decorrelates θ from the covariate effect." } },
  { cat: 'Maths & covariables', chapter: 'math-edo', type: 'num', unit: 'mg', answer: 36.8, tol: 0.03,
    q: "dA/dt = −k·A avec A₀ = 100 mg et k = 0,10 /h. Quelle quantité reste-t-il à t = 10 h ?",
    explain: "A(t) = A₀·e^(−kt) = 100·e^(−1) ≈ 36,8 mg.",
    en: { q: "dA/dt = −k·A with A₀ = 100 mg and k = 0.10 /h. How much remains at t = 10 h?", explain: "A(t) = A₀·e^(−kt) = 100·e^(−1) ≈ 36.8 mg." } },
  { cat: 'Maths & covariables', chapter: 'math-edo', type: 'mcq', correct: 0,
    q: "Sur une échelle semi-logarithmique, une décroissance d'ordre 1 apparaît…",
    options: ["comme une droite", "comme une parabole", "comme un plateau"],
    explain: "ln C = ln C₀ − k·t : une droite de pente −k. Deux droites = bi-compartimental.",
    en: { q: "On a semi-log scale, first-order decay looks like…", options: ["a straight line", "a parabola", "a plateau"], explain: "ln C = ln C₀ − k·t: a straight line of slope −k. Two lines = two-compartment." } },
  { cat: 'Maths & covariables', chapter: 'math-regression', type: 'num', unit: '/h', answer: 0.2, tol: 0.05,
    q: "Régression log-linéaire : ln(C) passe de 2,0 (t=0) à 0,0 (t=10 h). Quelle est la constante ke (−pente) ?",
    explain: "pente = (0 − 2)/10 = −0,20 /h ⇒ ke = 0,20 /h.",
    en: { q: "Log-linear regression: ln(C) goes from 2.0 (t=0) to 0.0 (t=10 h). What is ke (−slope)?", explain: "slope = (0 − 2)/10 = −0.20 /h ⇒ ke = 0.20 /h." } },
  { cat: 'Maths & covariables', chapter: 'math-bayes', type: 'mcq', correct: 0,
    q: "L'estimation MAP (maximum a posteriori) combine…",
    options: ["l'information a priori (population) et les données du patient", "seulement la dernière mesure", "seulement la dose"],
    explain: "posterior ∝ vraisemblance × prior ; le MAP prend le sommet du posterior.",
    en: { q: "MAP (maximum a posteriori) estimation combines…", options: ["the prior (population) information and the patient's data", "only the last measurement", "only the dose"], explain: "posterior ∝ likelihood × prior; MAP takes the peak of the posterior." } },
  { cat: 'Maths & covariables', chapter: 'math-stats', type: 'num', unit: 'L/h', answer: 5.98, tol: 0.02,
    q: "Estimation CL = 5 L/h avec SE = 0,5. Quelle est la borne haute de l'IC à 95 % (≈ est + 1,96·SE) ?",
    explain: "5 + 1,96 × 0,5 = 5,98 L/h. La borne basse serait 4,02.",
    en: { q: "Estimate CL = 5 L/h with SE = 0.5. What is the upper bound of the 95% CI (≈ est + 1.96·SE)?", explain: "5 + 1.96 × 0.5 = 5.98 L/h. The lower bound would be 4.02." } },
  { cat: 'Maths & covariables', chapter: 'math-stats', type: 'mcq', correct: 0,
    q: "Une clairance individuelle est le plus souvent modélisée par une loi…",
    options: ["log-normale (positive, asymétrique)", "normale centrée en zéro", "uniforme"],
    explain: "CL = CL_pop·e^η, η ~ N(0,ω²) : la clairance est log-normale (toujours positive).",
    en: { q: "An individual clearance is most often modelled with a…", options: ["log-normal law (positive, skewed)", "normal law centred at zero", "uniform law"], explain: "CL = CL_pop·e^η, η ~ N(0,ω²): clearance is log-normal (always positive)." } },
  { cat: 'Maths & covariables', chapter: 'math-fisher', type: 'mcq', correct: 0,
    q: "Un RSE de 80 % sur un paramètre indique…",
    options: ["qu'il est mal identifié par les données", "qu'il est parfaitement estimé", "que la dose est trop faible"],
    explain: "RSE = SE/estimation ; élevé ⇒ paramètre imprécis. Le design optimal (FIM) vise à le réduire.",
    en: { q: "An RSE of 80% on a parameter indicates…", options: ["it is poorly identified by the data", "it is perfectly estimated", "the dose is too low"], explain: "RSE = SE/estimate; high ⇒ imprecise parameter. Optimal design (FIM) aims to reduce it." } },
  { cat: 'Maths & covariables', chapter: 'math-copula', type: 'mcq', correct: 0,
    q: "Simuler poids et ClCr indépendamment (sans copule)…",
    options: ["crée des patients impossibles (ex. 45 kg + ClCr 160)", "n'a aucune conséquence", "améliore le modèle"],
    explain: "Les covariables sont corrélées ; une copule reproduit la dépendance tout en gardant les marges.",
    en: { q: "Simulating weight and CrCl independently (without a copula)…", options: ["creates impossible patients (e.g. 45 kg + CrCl 160)", "has no consequence", "improves the model"], explain: "Covariates are correlated; a copula reproduces the dependence while keeping the margins." } },
  { cat: 'Maths & covariables', chapter: 'math-covariates', type: 'mcq', correct: 0,
    q: "La sélection pas-à-pas (SCM) tend à…",
    options: ["sur-sélectionner et surestimer les effets (données réutilisées)", "toujours donner le vrai modèle", "ignorer les covariables"],
    explain: "Tester beaucoup de covariables sur les mêmes données biaise la sélection ; préférer des formes pré-spécifiées.",
    en: { q: "Stepwise selection (SCM) tends to…", options: ["over-select and overestimate effects (data reused)", "always give the true model", "ignore covariates"], explain: "Testing many covariates on the same data biases selection; prefer pre-specified forms." } },

  // ═══ PK/PD & pharmacodynamie ═══
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pkpd', type: 'mcq', correct: 0,
    q: "L'EC50 est la concentration qui produit…",
    options: ["la moitié de l'effet maximal (Emax)", "un effet nul", "le double de l'effet de base"],
    explain: "EC50 = concentration donnant ½ Emax. Mal estimée si les données ne couvrent que 20–80 % de l'effet.",
    en: { q: "EC50 is the concentration producing…", options: ["half the maximal effect (Emax)", "no effect", "double the baseline effect"], explain: "EC50 = concentration giving ½ Emax. Poorly estimated if data only cover 20–80% of the effect." } },
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pkpd', type: 'mcq', correct: 0,
    q: "Un pic d'effet qui survient APRÈS le pic plasmatique évoque…",
    options: ["un compartiment d'effet / une hystérèse", "une erreur de dosage", "une cinétique d'ordre 0"],
    explain: "Le décalage (modèle de Sheiner, ke0) crée une boucle d'hystérèse effet–concentration.",
    en: { q: "An effect peak occurring AFTER the plasma peak suggests…", options: ["an effect compartment / hysteresis", "a dosing error", "zero-order kinetics"], explain: "The lag (Sheiner model, ke0) creates an effect–concentration hysteresis loop." } },
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pd-direct', type: 'num', unit: '', answer: 75, tol: 0.02,
    q: "Modèle Emax (n=1) : Emax = 100, EC50 = 2 mg/L. Quel effet à C = 6 mg/L (E = Emax·C/(EC50+C)) ?",
    explain: "E = 100 × 6/(2+6) = 100 × 0,75 = 75.",
    en: { q: "Emax model (n=1): Emax = 100, EC50 = 2 mg/L. What effect at C = 6 mg/L (E = Emax·C/(EC50+C))?", explain: "E = 100 × 6/(2+6) = 100 × 0.75 = 75." } },
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pd-indirect', type: 'mcq', correct: 0,
    q: "Dans un modèle de réponse indirecte, le délai de l'effet vient…",
    options: ["du renouvellement (kout) de la réponse, pas de la PK", "de la vitesse d'absorption", "du volume de distribution"],
    explain: "R0 = kin/kout ; le délai dépend de kout. Augmenter la dose n'accélère pas le délai.",
    en: { q: "In an indirect-response model, the effect delay comes from…", options: ["the turnover (kout) of the response, not the PK", "the absorption rate", "the volume of distribution"], explain: "R0 = kin/kout; the delay depends on kout. Raising the dose does not shorten it." } },
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pd-effect-compartment', type: 'num', unit: 'h', answer: 1.98, tol: 0.05,
    q: "Compartiment d'effet avec ke0 = 0,35 /h. Quelle est la demi-vie d'équilibration (ln2/ke0) ?",
    explain: "t½,ke0 = 0,693/0,35 ≈ 1,98 h : elle résume le retard plasma → site d'effet.",
    en: { q: "Effect compartment with ke0 = 0.35 /h. What is the equilibration half-life (ln2/ke0)?", explain: "t½,ke0 = 0.693/0.35 ≈ 1.98 h: it summarises the plasma → effect-site delay." } },
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pd-tolerance', type: 'mcq', correct: 0,
    q: "Un effet qui décroît alors que les concentrations restent stables évoque…",
    options: ["une tolérance pharmacodynamique", "une auto-induction du métabolisme", "une erreur de dose"],
    explain: "Concentrations stables + effet qui baisse = tolérance (PD). Si l'exposition baisse aussi, penser auto-induction (PK).",
    en: { q: "An effect that fades while concentrations stay stable suggests…", options: ["pharmacodynamic tolerance", "metabolic auto-induction", "a dosing error"], explain: "Stable concentrations + fading effect = tolerance (PD). If exposure also falls, think auto-induction (PK)." } },
  { cat: 'PK/PD & pharmacodynamie', chapter: 'pd-survival', type: 'mcq', correct: 0,
    q: "La différence entre OS et PFS est que…",
    options: ["l'OS mesure le temps jusqu'au décès, la PFS jusqu'à progression ou décès", "l'OS est toujours plus courte", "ce sont des synonymes"],
    explain: "La PFS chute avant l'OS. Un bon effet PFS ne garantit pas un gain d'OS (substitut imparfait).",
    en: { q: "The difference between OS and PFS is that…", options: ["OS measures time to death, PFS time to progression or death", "OS is always shorter", "they are synonyms"], explain: "PFS falls before OS. A good PFS effect does not guarantee an OS gain (imperfect surrogate)." } },

  // ═══ NCA ═══
  { cat: 'NCA', chapter: 'nca-auc', type: 'num', unit: 'mg·h/L', answer: 12, tol: 0.02,
    q: "Trapèze : C = 8 mg/L à t = 1 h et C = 4 mg/L à t = 3 h. Quelle est l'aire de ce segment ?",
    explain: "ΔAUC = (8+4)/2 × (3−1) = 6 × 2 = 12 mg·h/L.",
    en: { q: "Trapezoid: C = 8 mg/L at t = 1 h and C = 4 mg/L at t = 3 h. What is the area of this segment?", explain: "ΔAUC = (8+4)/2 × (3−1) = 6 × 2 = 12 mg·h/L." } },
  { cat: 'NCA', chapter: 'nca-auc', type: 'num', unit: 'mg·h/L', answer: 100, tol: 0.02,
    q: "AUC₀–last = 90, dernière concentration Clast = 2 mg/L, λz = 0,20 /h. Quelle est l'AUC₀–∞ ?",
    explain: "AUC∞ = AUClast + Clast/λz = 90 + 2/0,20 = 90 + 10 = 100 mg·h/L.",
    en: { q: "AUC₀–last = 90, last concentration Clast = 2 mg/L, λz = 0.20 /h. What is AUC₀–∞?", explain: "AUC∞ = AUClast + Clast/λz = 90 + 2/0.20 = 90 + 10 = 100 mg·h/L." } },
  { cat: 'NCA', chapter: 'nca-params', type: 'num', unit: 'L/h', answer: 5, tol: 0.02,
    q: "Dose IV de 200 mg, AUC₀–∞ = 40 mg·h/L. Quelle est la clairance ?",
    explain: "CL = Dose / AUC∞ = 200 / 40 = 5 L/h.",
    en: { q: "IV dose of 200 mg, AUC₀–∞ = 40 mg·h/L. What is the clearance?", explain: "CL = Dose / AUC∞ = 200 / 40 = 5 L/h." } },
  { cat: 'NCA', chapter: 'nca-params', type: 'num', unit: 'L', answer: 50, tol: 0.02,
    q: "Avec CL = 5 L/h et λz = 0,10 /h, quel est le volume Vz (= CL/λz) ?",
    explain: "Vz = CL/λz = 5/0,10 = 50 L.",
    en: { q: "With CL = 5 L/h and λz = 0.10 /h, what is the volume Vz (= CL/λz)?", explain: "Vz = CL/λz = 5/0.10 = 50 L." } },
  { cat: 'NCA', chapter: 'nca-absorption', type: 'num', unit: '', answer: 0.5, tol: 0.05,
    q: "Même dose PO et IV : AUC_orale = 40, AUC_IV = 80 mg·h/L. Quelle est la biodisponibilité absolue F ?",
    explain: "F = AUC_orale / AUC_IV (dose égale) = 40/80 = 0,5 (50 %).",
    en: { q: "Same PO and IV dose: AUC_oral = 40, AUC_IV = 80 mg·h/L. What is the absolute bioavailability F?", explain: "F = AUC_oral / AUC_IV (equal dose) = 40/80 = 0.5 (50%)." } },
  { cat: 'NCA', chapter: 'nca-intro', type: 'mcq', correct: 0,
    q: "La NCA suppose principalement une cinétique…",
    options: ["linéaire (AUC proportionnelle à la dose)", "toujours non linéaire", "sans élimination"],
    explain: "La NCA ne suppose pas de compartiments, mais bien la linéarité et une phase terminale bien échantillonnée.",
    en: { q: "NCA mainly assumes kinetics that are…", options: ["linear (AUC proportional to dose)", "always non-linear", "without elimination"], explain: "NCA assumes no compartments, but does assume linearity and a well-sampled terminal phase." } },

  // ═══ PBPK ═══
  { cat: 'PBPK', chapter: 'pbpk-intro', type: 'mcq', correct: 0,
    q: "Un organe « perfusion-limited » est limité par…",
    options: ["le débit sanguin qui l'irrigue", "la couleur du tissu", "la dose administrée"],
    explain: "Quand la membrane ne freine pas, l'entrée est limitée par le débit Q_T (bilan de masse perfusion-limité).",
    en: { q: "A 'perfusion-limited' organ is limited by…", options: ["the blood flow supplying it", "the tissue colour", "the administered dose"], explain: "When the membrane does not slow entry, uptake is limited by the flow Q_T (perfusion-limited mass balance)." } },
  { cat: 'PBPK', chapter: 'pbpk-distribution', type: 'mcq', correct: 0,
    q: "Une molécule très lipophile aura tendance à…",
    options: ["s'accumuler dans les tissus gras (grand volume)", "rester uniquement dans le plasma", "être éliminée sans distribution"],
    explain: "Grand Kp graisse ⇒ grand volume de distribution, demi-vie allongée. Seule la fraction libre agit.",
    en: { q: "A highly lipophilic molecule will tend to…", options: ["accumulate in fatty tissues (large volume)", "stay only in plasma", "be eliminated without distributing"], explain: "Large fat Kp ⇒ large volume of distribution, longer half-life. Only the free fraction acts." } },
  { cat: 'PBPK', chapter: 'pbpk-absorption', type: 'num', unit: '', answer: 0.405, tol: 0.05,
    q: "Biodisponibilité orale F = fa·Fg·Fh avec fa = 0,9, Fg = 0,9, Fh = 0,5. Quelle est F ?",
    explain: "F = 0,9 × 0,9 × 0,5 = 0,405 (≈ 40 %). Un fort premier passage (Fh bas) peut dominer.",
    en: { q: "Oral bioavailability F = fa·Fg·Fh with fa = 0.9, Fg = 0.9, Fh = 0.5. What is F?", explain: "F = 0.9 × 0.9 × 0.5 = 0.405 (≈ 40%). A strong first-pass (low Fh) can dominate." } },
  { cat: 'PBPK', chapter: 'pbpk-applications', type: 'num', unit: 'L/h', answer: 22.5, tol: 0.03,
    q: "Modèle well-stirred : Qh = 90 L/h, fu·CLint = 30 L/h. Quelle est CLh = Qh·fu·CLint/(Qh + fu·CLint) ?",
    explain: "CLh = 90 × 30 / (90 + 30) = 2700/120 = 22,5 L/h.",
    en: { q: "Well-stirred model: Qh = 90 L/h, fu·CLint = 30 L/h. What is CLh = Qh·fu·CLint/(Qh + fu·CLint)?", explain: "CLh = 90 × 30 / (90 + 30) = 2700/120 = 22.5 L/h." } },

  // ═══ Oncologie ═══
  { cat: 'Oncologie', chapter: 'onco-tgi', type: 'mcq', correct: 0,
    q: "Dans le modèle de Claret, l'effet du traitement sur la tumeur…",
    options: ["s'épuise avec le temps (résistance)", "est constant à vie", "ne dépend pas de l'exposition"],
    explain: "Le terme de rétrécissement K·expo·e^(−λt) décroît : la résistance apparaît, la tumeur peut ré-échapper.",
    en: { q: "In the Claret model, the treatment effect on the tumour…", options: ["fades over time (resistance)", "is constant forever", "does not depend on exposure"], explain: "The shrinkage term K·expo·e^(−λt) decays: resistance appears, the tumour can escape again." } },
  { cat: 'Oncologie', chapter: 'onco-tox', type: 'mcq', correct: 0,
    q: "Dans le modèle de Friberg, le nadir des neutrophiles survient…",
    options: ["avec un délai (maturation), après le pic de concentration", "exactement au pic plasmatique", "avant l'administration"],
    explain: "Le délai vient des compartiments de transit (MTT), pas de la PK ; la toxicité peut être cumulative.",
    en: { q: "In the Friberg model, the neutrophil nadir occurs…", options: ["with a delay (maturation), after the concentration peak", "exactly at the plasma peak", "before dosing"], explain: "The delay comes from the transit compartments (MTT), not the PK; toxicity can be cumulative." } },
  { cat: 'Oncologie', chapter: 'onco-models', type: 'mcq', correct: 0,
    q: "Le modèle de croissance de Gompertz décrit une croissance…",
    options: ["qui ralentit à mesure que la tumeur grossit (plateau)", "toujours exponentielle sans limite", "strictement linéaire"],
    explain: "Gompertz : dW/dt = λW·ln(W∞/W), la vitesse diminue à l'approche de W∞.",
    en: { q: "The Gompertz growth model describes growth that…", options: ["slows as the tumour grows (plateau)", "is always exponential without limit", "is strictly linear"], explain: "Gompertz: dW/dt = λW·ln(W∞/W); the rate decreases as W approaches W∞." } },

  // ═══ Infectiologie ═══
  { cat: 'Infectiologie', chapter: 'infectio-pkpd', type: 'mcq', correct: 0,
    q: "Pour les bêta-lactamines, l'indice PK/PD prédictif est…",
    options: ["le temps au-dessus de la CMI (T>CMI)", "le poids du patient", "la couleur de la solution"],
    explain: "Temps-dépendantes ⇒ optimisées par perfusions prolongées/continues (maximiser T>CMI).",
    en: { q: "For beta-lactams, the predictive PK/PD index is…", options: ["the time above the MIC (T>MIC)", "the patient's weight", "the colour of the solution"], explain: "Time-dependent ⇒ optimised by prolonged/continuous infusions (maximise T>MIC)." } },
  { cat: 'Infectiologie', chapter: 'infectio-pkpd', type: 'num', unit: '', answer: 200, tol: 0.02,
    q: "AUC₂₄ = 400 mg·h/L, CMI = 2 mg/L. Quel est l'indice AUC₂₄/CMI ?",
    explain: "AUC₂₄/CMI = 400/2 = 200. Pour la vancomycine, la cible est ≥ 400.",
    en: { q: "AUC₂₄ = 400 mg·h/L, MIC = 2 mg/L. What is the AUC₂₄/MIC index?", explain: "AUC₂₄/MIC = 400/2 = 200. For vancomycin, the target is ≥ 400." } },
  { cat: 'Infectiologie', chapter: 'infectio-tdm', type: 'num', unit: 'mg·h/L', answer: 500, tol: 0.02,
    q: "Vancomycine 2000 mg/j, clairance CL = 4 L/h. Quelle est l'AUC₂₄ (= dose/j ÷ CL) ?",
    explain: "AUC₂₄ = 2000 / 4 = 500 mg·h/L. Avec CMI = 1, AUC/CMI = 500 ≥ 400 : cible atteinte.",
    en: { q: "Vancomycin 2000 mg/day, clearance CL = 4 L/h. What is the AUC₂₄ (= daily dose ÷ CL)?", explain: "AUC₂₄ = 2000 / 4 = 500 mg·h/L. With MIC = 1, AUC/MIC = 500 ≥ 400: target met." } },
  { cat: 'Infectiologie', chapter: 'infectio-tdm', type: 'mcq', correct: 0,
    q: "En réanimation, une clairance rénale augmentée (ARC) tend à…",
    options: ["sous-doser les antibiotiques hydrophiles", "surdoser systématiquement", "ne rien changer"],
    explain: "L'ARC élimine vite : à dose standard, sous-exposition et risque d'échec ; le TDM bayésien l'ajuste.",
    en: { q: "In the ICU, augmented renal clearance (ARC) tends to…", options: ["under-dose hydrophilic antibiotics", "systematically overdose", "change nothing"], explain: "ARC eliminates fast: at a standard dose, under-exposure and risk of failure; Bayesian TDM adjusts it." } },
  { cat: 'Infectiologie', chapter: 'infectio-viral', type: 'mcq', correct: 0,
    q: "La décroissance biphasique de la charge virale sous traitement reflète…",
    options: ["la clairance du virus libre puis la perte des cellules infectées", "deux erreurs de mesure", "la dose et le poids"],
    explain: "Phase 1 rapide (clairance c, pilotée par l'efficacité ε), phase 2 lente (perte des cellules infectées δ).",
    en: { q: "The biphasic viral-load decline under treatment reflects…", options: ["free-virus clearance then loss of infected cells", "two measurement errors", "dose and weight"], explain: "Phase 1 fast (clearance c, driven by efficacy ε), phase 2 slow (loss of infected cells δ)." } },

  // ═══ Anticorps monoclonaux ═══
  { cat: 'Anticorps monoclonaux', chapter: 'mab-pk', type: 'mcq', correct: 0,
    q: "La demi-vie longue (semaines) des IgG s'explique surtout par…",
    options: ["le recyclage par le récepteur FcRn", "une forte lipophilie", "une élimination rénale rapide"],
    explain: "Le FcRn « sauve » les IgG de la dégradation ; petit volume, catabolisme lent, pas de rein/CYP.",
    en: { q: "The long half-life (weeks) of IgG is mainly explained by…", options: ["recycling by the FcRn receptor", "high lipophilicity", "fast renal elimination"], explain: "FcRn 'rescues' IgG from degradation; small volume, slow catabolism, no kidney/CYP." } },
  { cat: 'Anticorps monoclonaux', chapter: 'mab-tmdd', type: 'mcq', correct: 0,
    q: "En présence de TMDD, quand la dose augmente, la clairance…",
    options: ["diminue (la cible sature)", "augmente", "reste strictement constante"],
    explain: "À forte dose la voie cible sature ⇒ clairance plus faible, PK quasi linéaire ; doubler la dose plus que double l'exposition.",
    en: { q: "With TMDD, as the dose increases, clearance…", options: ["decreases (the target saturates)", "increases", "stays strictly constant"], explain: "At high dose the target route saturates ⇒ lower clearance, near-linear PK; doubling the dose more than doubles exposure." } },
  { cat: 'Anticorps monoclonaux', chapter: 'mab-ada', type: 'mcq', correct: 0,
    q: "L'apparition d'anticorps anti-médicament (ADA) tend à…",
    options: ["augmenter la clairance et faire chuter l'exposition", "diminuer la clairance", "n'avoir aucun effet"],
    explain: "Les ADA liants forment des complexes éliminés vite ⇒ résiduelles effondrées, perte de réponse secondaire.",
    en: { q: "The appearance of anti-drug antibodies (ADA) tends to…", options: ["increase clearance and collapse exposure", "decrease clearance", "have no effect"], explain: "Binding ADA form fast-cleared complexes ⇒ collapsed troughs, secondary loss of response." } },

  // ═══ IA & machine learning ═══
  { cat: 'IA & machine learning', chapter: 'ai-trees', type: 'mcq', correct: 0,
    q: "Une forêt aléatoire améliore un arbre unique en…",
    options: ["moyennant de nombreux arbres décorrélés (bagging)", "augmentant la profondeur d'un seul arbre", "supprimant les covariables"],
    explain: "Un arbre seul surajuste (marches) ; la forêt moyenne des arbres bootstrap + variables aléatoires.",
    en: { q: "A random forest improves a single tree by…", options: ["averaging many decorrelated trees (bagging)", "increasing the depth of one tree", "removing covariates"], explain: "A single tree overfits (steps); the forest averages bootstrap trees + random variables." } },
  { cat: 'IA & machine learning', chapter: 'ai-boosting', type: 'mcq', correct: 0,
    q: "Le principe du gradient boosting est de…",
    options: ["ajouter des arbres qui corrigent les résidus du précédent", "moyenner des arbres indépendants", "entraîner un seul très grand arbre"],
    explain: "F_m = F_{m−1} + ν·h_m ; puissant sur données tabulaires (XGBoost, CatBoost) mais surajuste sans arrêt précoce.",
    en: { q: "The principle of gradient boosting is to…", options: ["add trees that correct the previous one's residuals", "average independent trees", "train a single very large tree"], explain: "F_m = F_{m−1} + ν·h_m; powerful on tabular data (XGBoost, CatBoost) but overfits without early stopping." } },
  { cat: 'IA & machine learning', chapter: 'ai-svm', type: 'mcq', correct: 0,
    q: "Un SVM linéaire choisit la frontière qui…",
    options: ["maximise la marge entre les deux classes", "passe par tous les points", "minimise le nombre de covariables"],
    explain: "Seuls les vecteurs de support (points dans la marge) la définissent ; le kernel trick courbe la frontière.",
    en: { q: "A linear SVM chooses the boundary that…", options: ["maximises the margin between the two classes", "passes through every point", "minimises the number of covariates"], explain: "Only the support vectors (points in the margin) define it; the kernel trick bends the boundary." } },
  { cat: 'IA & machine learning', chapter: 'ai-featselect', type: 'mcq', correct: 0,
    q: "VSURF sélectionne les variables en…",
    options: ["deux temps (interprétation puis prédiction) via l'importance des forêts", "gardant toutes les variables", "tirant au hasard"],
    explain: "OrdinalForest gère en plus les réponses ordinales (grades). Attention : importance ≠ causalité.",
    en: { q: "VSURF selects variables by…", options: ["two steps (interpretation then prediction) via forest importance", "keeping all variables", "drawing at random"], explain: "OrdinalForest also handles ordinal responses (grades). Beware: importance ≠ causality." } },
  { cat: 'IA & machine learning', chapter: 'ai-llm', type: 'mcq', correct: 0,
    q: "Un risque majeur d'un LLM en contexte clinique est…",
    options: ["l'hallucination (affirmations fausses mais plausibles)", "l'impossibilité de produire du texte", "une vitesse trop faible"],
    explain: "Le LLM complète du texte plausible : toute sortie doit être vérifiée à la source ; il assiste, il ne décide pas.",
    en: { q: "A major risk of an LLM in a clinical context is…", options: ["hallucination (false but plausible statements)", "the inability to produce text", "being too slow"], explain: "An LLM completes plausible text: every output must be checked at the source; it assists, it does not decide." } },
  { cat: 'IA & machine learning', chapter: 'ai-ml-tdm', type: 'mcq', correct: 0,
    q: "L'apport principal du ML pour le TDM est de…",
    options: ["prédire l'exposition (AUC) à partir de peu de prélèvements", "remplacer le clinicien", "supprimer la validation externe"],
    explain: "Modèles d'arbres/boosting ou hybrides PopPK+ML ; exigent une validation externe et de la prudence à l'extrapolation.",
    en: { q: "The main contribution of ML to TDM is to…", options: ["predict exposure (AUC) from few samples", "replace the clinician", "remove external validation"], explain: "Tree/boosting or hybrid PopPK+ML models; they require external validation and caution when extrapolating." } },
  { cat: 'IA & machine learning', chapter: 'neural-ode', type: 'mcq', correct: 0,
    q: "Un modèle « grey-box » (Neural ODE) cherche à…",
    options: ["garder la structure mécaniste connue et apprendre la partie mal décrite", "abandonner toute pharmacologie", "ignorer les données"],
    explain: "Il combine ODE mécanistes et réseaux : flexibilité tout en gardant l'interprétabilité physiologique.",
    en: { q: "A 'grey-box' model (Neural ODE) aims to…", options: ["keep the known mechanistic structure and learn the poorly described part", "abandon all pharmacology", "ignore the data"], explain: "It combines mechanistic ODEs and networks: flexibility while keeping physiological interpretability." } },

  // ═══ Validation de modèle ═══
  { cat: 'Validation de modèle', chapter: 'validation-vpc', type: 'mcq', correct: 1,
    q: "Sur une VPC, les observations sortent nettement des bandes simulées. Cela signifie…",
    options: ["le modèle est validé", "le modèle ne reproduit pas les données (à revoir)", "il faut plus de patients seulement"],
    explain: "Si les percentiles observés sortent des tunnels simulés, le modèle simule mal — il faut le réviser (structure/variabilité).",
    en: { q: "On a VPC, the observations fall clearly outside the simulated bands. This means…", options: ["the model is validated", "the model does not reproduce the data (to revise)", "only more patients are needed"], explain: "If observed percentiles leave the simulated tunnels, the model simulates poorly — revise it (structure/variability)." } },
  { cat: 'Validation de modèle', chapter: 'valid-gof', type: 'mcq', correct: 0,
    q: "Une tendance des CWRES en fonction du temps indique…",
    options: ["une mauvaise spécification du modèle structural", "un bon ajustement", "une erreur d'unité"],
    explain: "Les CWRES doivent être centrés sur 0, sans tendance, ~95 % dans ±2.",
    en: { q: "A trend of CWRES versus time indicates…", options: ["a misspecified structural model", "a good fit", "a unit error"], explain: "CWRES should be centred on 0, without trend, ~95% within ±2." } },
  { cat: 'Validation de modèle', chapter: 'valid-uncertainty', type: 'num', unit: '%', answer: 10, tol: 0.02,
    q: "Un paramètre est estimé à 5 L/h avec SE = 0,5. Quel est son RSE en % (SE/estimation ×100) ?",
    explain: "RSE = 0,5/5 × 100 = 10 %. Un RSE faible = paramètre bien identifié.",
    en: { q: "A parameter is estimated at 5 L/h with SE = 0.5. What is its RSE in % (SE/estimate ×100)?", explain: "RSE = 0.5/5 × 100 = 10%. A low RSE = a well-identified parameter." } },
  { cat: 'Validation de modèle', chapter: 'valid-npde', type: 'mcq', correct: 0,
    q: "Si le modèle est correct, les NPDE suivent une loi…",
    options: ["normale standard N(0,1)", "uniforme", "exponentielle"],
    explain: "On teste moyenne (0), variance (1) et normalité, et on stratifie par covariable/temps.",
    en: { q: "If the model is correct, the NPDE follow a…", options: ["standard normal law N(0,1)", "uniform law", "exponential law"], explain: "We test mean (0), variance (1) and normality, and stratify by covariate/time." } },
  { cat: 'Validation de modèle', chapter: 'valid-shrinkage', type: 'num', unit: '%', answer: 30, tol: 0.05,
    q: "eta-shrinkage : SD(η̂) = 0,21 et ω = 0,30. Quel est le shrinkage en % (1 − SD/ω) ?",
    explain: "1 − 0,21/0,30 = 1 − 0,70 = 0,30 = 30 %. Au-delà de ~20–30 %, les diagnostics par EBE trompent.",
    en: { q: "eta-shrinkage: SD(η̂) = 0.21 and ω = 0.30. What is the shrinkage in % (1 − SD/ω)?", explain: "1 − 0.21/0.30 = 1 − 0.70 = 0.30 = 30%. Beyond ~20–30%, EBE-based diagnostics mislead." } },
  { cat: 'Validation de modèle', chapter: 'valid-shrinkage', type: 'mcq', correct: 0,
    q: "Un shrinkage élevé (> 30 %) sur les EBE implique que…",
    options: ["les diagnostics graphiques basés sur les EBE peuvent tromper", "le modèle est forcément excellent", "la dose doit être doublée"],
    explain: "EBE tirés vers la population (données pauvres) ; s'appuyer plutôt sur VPC/NPDE et simplifier l'IIV.",
    en: { q: "High shrinkage (> 30%) on the EBEs implies that…", options: ["EBE-based diagnostic plots can mislead", "the model is necessarily excellent", "the dose must be doubled"], explain: "EBEs pulled toward the population (sparse data); rely instead on VPC/NPDE and simplify the IIV." } },

  // ═══ Essais cliniques ═══
  { cat: 'Essais cliniques', chapter: 'trials-fih', type: 'mcq', correct: 0,
    q: "Pour une molécule très active (agoniste immunitaire), la dose de départ se fonde plutôt sur…",
    options: ["le MABEL (plus faible effet biologique anticipé)", "la dose maximale tolérée", "le poids du patient"],
    explain: "Le NOAEL peut sous-estimer le risque humain (leçon TGN1412) ; le MABEL, fondé sur l'occupation de la cible, est plus prudent.",
    en: { q: "For a highly active molecule (immune agonist), the starting dose is based rather on…", options: ["the MABEL (minimal anticipated biological effect level)", "the maximum tolerated dose", "the patient's weight"], explain: "The NOAEL can underestimate human risk (TGN1412 lesson); the MABEL, based on target occupancy, is more conservative." } },
  { cat: 'Essais cliniques', chapter: 'trials-cts', type: 'mcq', correct: 0,
    q: "La simulation d'essais cliniques (CTS) sert surtout à…",
    options: ["évaluer designs, doses et puissance avant de lancer l'essai", "remplacer définitivement les essais réels", "mesurer une concentration"],
    explain: "On « rejoue » l'essai sur des populations virtuelles ; il faut propager l'incertitude des paramètres.",
    en: { q: "Clinical trial simulation (CTS) mainly serves to…", options: ["evaluate designs, doses and power before launching the trial", "permanently replace real trials", "measure a concentration"], explain: "We 'replay' the trial on virtual populations; parameter uncertainty must be propagated." } },
  { cat: 'Essais cliniques', chapter: 'trials-interpretation', type: 'mcq', correct: 0,
    q: "Un effet de covariable est cliniquement pertinent s'il…",
    options: ["sort de la zone jugée sans conséquence (ex. ±20 %)", "est simplement statistiquement significatif", "concerne beaucoup de patients"],
    explain: "Sur un grand jeu, presque tout est significatif : c'est l'ampleur (hors bande + IC ne croisant pas 1) qui compte.",
    en: { q: "A covariate effect is clinically relevant if it…", options: ["leaves the zone deemed inconsequential (e.g. ±20%)", "is merely statistically significant", "concerns many patients"], explain: "On a large dataset almost everything is significant: it is the magnitude (outside the band + CI not crossing 1) that matters." } },
  { cat: 'Essais cliniques', chapter: 'trials-adaptive', type: 'mcq', correct: 0,
    q: "Un design adaptatif doit impérativement être…",
    options: ["entièrement pré-spécifié et validé par simulation", "modifié librement en cours de route", "dépourvu de groupe témoin"],
    explain: "Changer les règles en cours d'essai gonfle l'erreur de type I ; MCP-Mod estime la dose via une moyenne de modèles.",
    en: { q: "An adaptive design must imperatively be…", options: ["fully pre-specified and validated by simulation", "modified freely mid-way", "without a control group"], explain: "Changing the rules mid-trial inflates the type-I error; MCP-Mod estimates the dose via model averaging." } },

  // ═══ TDM (cœur) ═══
  { cat: 'PK/PD & pharmacodynamie', chapter: 'tdm', type: 'mcq', correct: 0,
    q: "Le principe du TDM bayésien est de…",
    options: ["mesurer, estimer le profil individuel par Bayes, puis ajuster la dose", "doubler la dose systématiquement", "ignorer la fonction rénale"],
    explain: "Une ou deux concentrations + le modèle de population donnent l'estimation individuelle et l'ajustement.",
    en: { q: "The principle of Bayesian TDM is to…", options: ["measure, estimate the individual profile by Bayes, then adjust the dose", "systematically double the dose", "ignore renal function"], explain: "One or two concentrations + the population model give the individual estimate and the adjustment." } },

  // ═══ Bayes (cœur) ═══
  { cat: 'Validation de modèle', chapter: 'bayes-ebes', type: 'mcq', correct: 0,
    q: "Un EBE (empirical Bayes estimate) est…",
    options: ["l'estimation de l'écart individuel (η) informée par la population", "une concentration mesurée", "une dose de charge"],
    explain: "CL_i = CL_typ·e^η̂ ; quand les données sont pauvres, η̂ est tiré vers 0 (shrinkage).",
    en: { q: "An EBE (empirical Bayes estimate) is…", options: ["the estimate of the individual deviation (η) informed by the population", "a measured concentration", "a loading dose"], explain: "CL_i = CL_typ·e^η̂; when data are sparse, η̂ is pulled toward 0 (shrinkage)." } },

  // ═══ Compléments de couverture ═══
  { cat: 'NCA', chapter: 'nca', type: 'mcq', correct: 0,
    q: "La NCA se distingue d'un modèle compartimental car elle…",
    options: ["ne suppose aucune structure de compartiments", "exige toujours 3 compartiments", "ignore les concentrations"],
    explain: "La NCA « laisse parler les données » : AUC par trapèzes et pente terminale λz, sans modèle structural.",
    en: { q: "NCA differs from a compartmental model because it…", options: ["assumes no compartmental structure", "always requires 3 compartments", "ignores concentrations"], explain: "NCA 'lets the data speak': AUC by trapezoids and terminal slope λz, without a structural model." } },
  { cat: 'Maths & covariables', chapter: 'outils-estimation', type: 'mcq', correct: 0,
    q: "Estimer par maximum de vraisemblance, c'est chercher les paramètres qui…",
    options: ["rendent les données observées les plus plausibles (OFV minimal)", "annulent tous les résidus", "maximisent le nombre de paramètres"],
    explain: "On minimise l'OFV (−2 log L) ; l'AIC/BIC arbitre la complexité. Le SAEM est un algorithme robuste pour les NLME.",
    en: { q: "Maximum likelihood estimation seeks the parameters that…", options: ["make the observed data most plausible (minimal OFV)", "cancel all residuals", "maximise the number of parameters"], explain: "We minimise the OFV (−2 log L); AIC/BIC arbitrate complexity. SAEM is a robust algorithm for NLME." } },
  { cat: 'Validation de modèle', chapter: 'valid-vpc', type: 'mcq', correct: 0,
    q: "La pcVPC (prediction-corrected VPC) sert surtout à…",
    options: ["corriger la variabilité due aux différences de dose/covariables entre sujets", "supprimer des observations", "augmenter la variabilité simulée"],
    explain: "Elle normalise chaque observation par sa prédiction typique, clarifiant la VPC quand le protocole mélange plusieurs doses.",
    en: { q: "The pcVPC (prediction-corrected VPC) mainly serves to…", options: ["correct variability from dose/covariate differences between subjects", "remove observations", "increase the simulated variability"], explain: "It normalises each observation by its typical prediction, clarifying the VPC when the protocol mixes several doses." } }
];

export const exerciseCategories = [
  'Pharmacocinétique de base',
  'Absorption, perfusion & doses',
  'NCA',
  'PBPK',
  'Maths & covariables',
  'PK/PD & pharmacodynamie',
  'Oncologie',
  'Infectiologie',
  'Anticorps monoclonaux',
  'IA & machine learning',
  'Validation de modèle',
  'Essais cliniques'
];

/** Exercices d'un chapitre donné (par slug). @param {string} slug */
export function exercisesForChapter(slug) {
  return exercises.filter((e) => e.chapter === slug);
}
