/** @type {Record<string, string>} */
export const categoryEnglish = {
  'Fondamentaux': 'Fundamentals',
  'Paramètres PK': 'PK parameters',
  'Modèles': 'Models',
  'Approches': 'Approaches',
  'Variabilité': 'Variability',
  'Covariables': 'Covariates',
  'Estimation': 'Estimation',
  'Diagnostics': 'Diagnostics',
  'Bayésien & TDM': 'Bayesian methods & TDM',
  'PK/PD': 'PK/PD',
  'Infectiologie': 'Infectious diseases',
  'IA': 'AI',
  'Outils': 'Tools',
  'Concepts': 'Concepts'
};

/** @type {Record<string, [string, string]>} */
export const glossaryEnglish = {
  'PK': ['Pharmacokinetics', 'What the body does to a drug through absorption, distribution, metabolism and elimination; it describes concentration over time.'],
  'PD': ['Pharmacodynamics', 'What a drug does to the body: the relationship between exposure or concentration and therapeutic or toxic response.'],
  'ADME': ['Absorption, Distribution, Metabolism, Elimination', 'The four main processes governing drug disposition and the basis of structural PK models.'],
  'CL': ['Clearance', 'The volume of plasma cleared of drug per unit time. It is a capacity, not an amount or a rate of concentration decline.'],
  'CLr': ['Renal clearance', 'The renal contribution to total clearance through filtration, secretion and reabsorption.'],
  'E': ['Extraction ratio', 'The fraction removed by an organ during one passage; organ clearance can be written as blood flow times extraction ratio.'],
  'DFG': ['Glomerular filtration rate', 'The volume of plasma filtered by the glomeruli per unit time, used as an indicator of renal function.'],
  'V': ['Volume of distribution', 'An apparent volume linking amount in the body to plasma concentration. It need not equal a physiological volume.'],
  'Vss': ['Steady-state volume of distribution', 'The apparent distribution volume once distribution equilibrium has been reached.'],
  'Q': ['Intercompartmental clearance', 'The exchange clearance connecting central and peripheral compartments in a multicompartment model.'],
  'Ka': ['Absorption rate constant', 'A first-order absorption rate constant. Its effect on peak timing and height depends on the full model.'],
  'ke': ['Elimination rate constant', 'A first-order elimination rate constant, equal to CL/V in a one-compartment linear model.'],
  'C0': ['Initial concentration', 'The concentration immediately after an ideal IV bolus, equal to Dose/V in a one-compartment model.'],
  'Cmax / Tmax': ['', 'The observed maximum concentration and its time. They are curve summaries, not structural parameters.'],
  't½': ['Half-life', 'The time for concentration to decrease by half. In a one-compartment linear model, t1/2 = ln(2)V/CL.'],
  'AUC': ['Area under the curve', 'The integral of concentration over time, used to quantify total exposure.'],
  'F': ['Bioavailability', 'The fraction of an administered dose reaching systemic circulation unchanged.'],
  'Tlag': ['Lag time', 'A delay between administration and the onset of absorption in the selected model.'],
  'Compartiments de transit': ['Transit compartments', 'A chain of compartments used to represent a distributed absorption delay.'],
  'Michaelis-Menten': ['Michaelis-Menten elimination', 'A saturable process with rate Vmax*C/(Km+C); the apparent clearance changes with concentration.'],
  'Phases α et β': ['Alpha and beta phases', 'Hybrid distribution and terminal phases of a two-compartment concentration-time profile.'],
  'Modèle compartimental': ['Compartmental model', 'A representation using well-mixed compartments connected by flows and differential equations.'],
  'Modèle structural': ['Structural model', 'The deterministic part of a model: compartments, inputs, exchanges and elimination.'],
  'EDO': ['Ordinary differential equation', 'An equation describing how a state changes over time, such as dA/dt.'],
  'NCA': ['Noncompartmental analysis', 'A descriptive analysis of exposure and terminal slope with limited structural assumptions.'],
  'PopPK': ['Population pharmacokinetics', 'Mixed-effects modelling of typical PK parameters and their variability in a population.'],
  'PBPK': ['Physiologically based pharmacokinetics', 'A mechanistic model built from organ physiology, flows, binding and drug-specific properties.'],
  'Effets mixtes': ['Mixed effects', 'A model combining fixed population effects with random between- or within-subject effects.'],
  'θ': ['Fixed effect', 'A typical population parameter estimated for the studied population.'],
  'η': ['Individual random effect', 'A subject-specific deviation from the typical parameter, usually modelled with mean zero.'],
  'IIV': ['Interindividual variability', 'Variability in model parameters between individuals from the target population.'],
  'IOV': ['Interoccasion variability', 'Variability in an individual parameter between occasions.'],
  'ω / Ω': ['Random-effect standard deviation / covariance matrix', 'Omega describes variances and covariances of random effects.'],
  'ε / σ': ['Residual error / standard deviation', 'Residual error describes observation noise and model-data discrepancy not captured elsewhere.'],
  'Erreur additive': ['Additive error', 'Residual error with an approximately constant absolute standard deviation.'],
  'Erreur proportionnelle': ['Proportional error', 'Residual error whose standard deviation scales with the prediction.'],
  'Erreur combinée': ['Combined error', 'A residual error model combining additive and proportional components.'],
  'Distribution normale': ['Normal distribution', 'A symmetric distribution on the real line, often used for additive quantities or random effects.'],
  'Distribution lognormale': ['Lognormal distribution', 'A positive distribution obtained by exponentiating a normal variable.'],
  'Distribution logit-normale': ['Logit-normal distribution', 'A distribution bounded between 0 and 1 obtained through an inverse-logit transformation.'],
  'Covariable': ['Covariate', 'A measured characteristic used to explain systematic parameter differences between subjects or occasions.'],
  'Allométrie': ['Allometry', 'A power-law relationship commonly used to scale clearance and volume with body size.'],
  'Centrage': ['Centering', 'Expressing a covariate relative to a reference value to improve interpretation and numerical stability.'],
  'Sélection forward/backward': ['Forward inclusion / backward elimination', 'A stepwise covariate procedure whose conclusions remain conditional on the tested candidates and thresholds.'],
  'Vraisemblance': ['Likelihood', 'The probability density of the observed data viewed as a function of model parameters.'],
  'OFV': ['Objective function value', 'A software criterion often related to minus twice the log-likelihood and used for conditional model comparisons.'],
  'FOCE-I': ['First-order conditional estimation with interaction', 'A conditional approximation used to estimate nonlinear mixed-effects models.'],
  'SAEM': ['Stochastic approximation expectation-maximisation', 'A stochastic algorithm for estimating nonlinear mixed-effects models.'],
  'MCMC': ['Markov chain Monte Carlo', 'Sampling algorithms used to approximate posterior distributions in Bayesian inference.'],
  'AIC / BIC': ['Information criteria', 'Likelihood-based criteria penalising model complexity; lower values support a relative trade-off within the compared set.'],
  'DoF': ['Degrees of freedom', 'A context-dependent measure of independent information remaining after estimation; N-P is exact only in specific settings.'],
  'Identifiabilité': ['Identifiability', 'Whether distinct parameter values can be distinguished from the available design and observations.'],
  'FIM': ['Fisher information matrix', 'A local measure of information about parameters; its inverse is linked to asymptotic covariance under regularity conditions.'],
  'RSE': ['Relative standard error', 'A standard error divided by its estimate. It quantifies approximate relative precision, not identifiability by itself.'],
  'Bootstrap': ['Bootstrap', 'Repeated resampling used to study estimator variability and model stability.'],
  'GOF': ['Goodness-of-fit', 'Plots comparing observations, predictions and residuals to identify systematic lack of fit.'],
  'PRED / IPRED': ['', 'Population and individual predictions. Their observation plots answer different diagnostic questions.'],
  'Résidus (WRES/CWRES/IWRES/NPDE)': ['Residuals (WRES/CWRES/IWRES/NPDE)', 'Standardised discrepancies between observations and predictions, interpreted under their construction assumptions.'],
  'VPC': ['Visual predictive check', 'A comparison of observed summaries with their distribution in replicated data simulated under the fitted model and design.'],
  'Binning': ['Binning', 'Grouping time or another independent variable to estimate stable observed and simulated summaries.'],
  'Théorème de Bayes': ['Bayes theorem', 'Posterior information is proportional to likelihood times prior information.'],
  'A priori / prior': ['Prior', 'Information specified before using the current individual data.'],
  'A posteriori / posterior': ['Posterior', 'The updated parameter distribution after combining prior information with current data.'],
  'MAP': ['Maximum a posteriori', 'The parameter value maximising the posterior density.'],
  'EBE': ['Empirical Bayes estimate', 'An individual random-effect estimate obtained using estimated population parameters.'],
  'Shrinkage': ['Shrinkage', 'The pull of weakly informed individual estimates towards the population centre.'],
  'TDM': ['Therapeutic drug monitoring', 'The contextual interpretation of measured concentrations to support individual dosing decisions.'],
  'Precision dosing': ['Precision dosing', 'Dose individualisation using patient data, a model and an explicit therapeutic objective.'],
  'MAP-BE': ['Maximum a posteriori Bayesian estimation', 'Individual estimation combining patient observations, residual error and a population prior.'],
  'Model averaging': ['Model averaging', 'A weighted combination of predictions from compatible models under an explicit weighting rule.'],
  'Emax': ['Emax model', 'A phenomenological saturating exposure-response model; it does not by itself prove receptor saturation.'],
  'EC50 / CE50': ['Half-maximal effective concentration', 'The concentration producing half of Emax in the specified model.'],
  'Coefficient de Hill': ['Hill coefficient', 'A shape parameter controlling the steepness of a sigmoidal Emax relationship.'],
  'Réponse indirecte / turnover': ['Indirect response / turnover', 'A model in which drug action changes production or loss of a response variable.'],
  'Compartiment d’effet (ke0)': ['Effect compartment (ke0)', 'A hypothetical compartment used to represent equilibration delay between plasma concentration and effect.'],
  'Hystérèse': ['Hysteresis', 'A loop in an effect-versus-concentration plot caused by a time-dependent mismatch between the two signals.'],
  'CMI': ['Minimum inhibitory concentration', 'The lowest tested concentration preventing visible growth under standardised conditions; it is method dependent.'],
  'PTA': ['Probability of target attainment', 'The proportion of simulated subjects attaining a specified PK/PD target under a defined model and scenario.'],
  'fT > CMI': ['fT > MIC', 'The fraction of an interval during which unbound concentration exceeds the MIC.'],
  'fAUC / CMI': ['fAUC / MIC', 'The ratio of unbound area under the curve to MIC, with an explicitly stated AUC horizon.'],
  'White / black / grey box': ['White / black / grey box', 'Mechanistic, data-driven or hybrid model structures, respectively.'],
  'Neural ODE': ['Neural ODE', 'A differential-equation model in which a neural network represents part of the dynamics.'],
  'VSURF': ['VSURF', 'A random-forest variable-selection method used for screening and interpretation.'],
  'XGBoost': ['XGBoost', 'Gradient-boosted decision trees used for prediction from structured features.'],
  'Jumeau numérique': ['Digital twin', 'A patient-specific computational representation updated with data for conditional simulation or decision support.'],
  'NONMEM': ['NONMEM', 'Software widely used for nonlinear mixed-effects modelling and regulatory analyses.'],
  'Monolix': ['Monolix', 'Software for nonlinear mixed-effects modelling using SAEM and related methods.'],
  'nlmixr2 / rxode2': ['nlmixr2 / rxode2', 'Open-source R tools for mixed-effects estimation and ODE-based simulation.'],
  'mrgsolve': ['mrgsolve', 'An R package for fast simulation of ODE-based PK/PD models.'],
  'mapbayr': ['mapbayr', 'An R package for MAP Bayesian estimation using compatible mrgsolve models.'],
  'MLXTRAN': ['MLXTRAN', 'The MonolixSuite language for structural, statistical and observation models.'],
  'Flip-flop': ['Flip-flop kinetics', 'A situation in which absorption is slower than elimination and therefore governs the observed terminal slope.']
};

/** @param {string} fr @param {string} en */
const both = (fr, en) => ({ fr, en });

/** @type {Record<string, any>} */
export const glossaryDetails = {
  'CL': { unit: 'L/h', equation: 'AUC = Dose / CL', intuition: both("Capacité d'épuration du système.", 'Capacity of the system to clear drug.'), limitation: both("Ce n'est ni un débit massique ni une vitesse de décroissance isolée.", 'It is neither a mass flow nor an isolated decay rate.'), example: both('À dose identique, une CL doublée divise approximativement l’AUC par deux en PK linéaire.', 'At the same dose, doubling CL approximately halves AUC in linear PK.'), chapter: 'clairance-volume-demi-vie', lab: 'distribution' },
  'V': { unit: 'L', equation: 'C = A / V', intuition: both('Facteur reliant quantité et concentration.', 'Scaling factor linking amount and concentration.'), limitation: both("Un volume apparent n'est pas forcément un volume anatomique.", 'An apparent volume need not be an anatomical volume.'), chapter: 'clairance-volume-demi-vie', lab: 'distribution' },
  'Ka': { unit: '1/h', equation: 'dAdep/dt = -Ka × Adep', intuition: both("Vitesse d'entrée d'une absorption d'ordre 1.", 'Input speed for first-order absorption.'), limitation: both("Son effet sur Cmax dépend aussi de CL, V, F et du modèle d'absorption.", 'Its effect on Cmax also depends on CL, V, F and the absorption model.'), chapter: 'absorption-orale', lab: 'absorption' },
  'Cmax / Tmax': { unit: 'mg/L ; h', intuition: both('Hauteur et temps du maximum observé.', 'Height and time of the observed maximum.'), limitation: both('Tlag peut décaler Tmax sans diminuer Cmax dans un simple modèle translaté.', 'Tlag can delay Tmax without lowering Cmax in a simple shifted model.'), chapter: 'absorption-orale', lab: 'absorption' },
  't½': { unit: 'h', equation: 't½ = ln(2) × V / CL', assumption: both('Formule simple valable pour un modèle monocompartimental linéaire.', 'Simple formula for a linear one-compartment model.'), chapter: 'clairance-volume-demi-vie', lab: 'distribution' },
  'AUC': { unit: 'mg·h/L', equation: 'AUC = ∫ C(t)dt', intuition: both('Exposition cumulée sur un horizon défini.', 'Cumulative exposure over a defined horizon.'), limitation: both("Toujours préciser l'horizon et la concentration totale ou libre.", 'Always state the horizon and whether concentration is total or unbound.'), chapter: 'micro-macro' },
  'DoF': { equation: 'N − P (cas linéaire simple)', limitation: both("N − P n'est pas une mesure générale d'identifiabilité en NLME.", 'N-P is not a general identifiability measure in NLME.'), chapter: 'math-stats' },
  'RSE': { unit: '%', equation: '100 × SE(θ̂) / |θ̂|', limitation: both("Mesure une précision approximative, pas l'identifiabilité à elle seule.", 'Measures approximate precision, not identifiability by itself.'), chapter: 'valid-uncertainty' },
  'PRED / IPRED': { intuition: both('PRED teste la tendance populationnelle ; IPRED inclut les ajustements individuels.', 'PRED checks population trend; IPRED includes individual adjustment.'), limitation: both("Une diagonale IPRED-DV ne suffit pas à valider le modèle.", 'An IPRED-DV diagonal is not sufficient to validate a model.'), chapter: 'valid-gof' },
  'Résidus (WRES/CWRES/IWRES/NPDE)': { intuition: both('Chercher centrage, dispersion attendue et absence de structure.', 'Look for centring, expected dispersion and lack of structure.'), limitation: both('±2 est un repère probabiliste, pas une frontière de validité.', '±2 is a probabilistic reference, not a validity boundary.'), chapter: 'valid-gof' },
  'VPC': { intuition: both('Comparer les données aux réplications du modèle sous le même plan.', 'Compare data with model replications under the same design.'), limitation: both('Le résultat dépend du binning, du plan simulé et des hypothèses du modèle.', 'The result depends on binning, simulated design and model assumptions.'), chapter: 'validation-vpc' },
  'Shrinkage': { unit: '%', intuition: both('Mesure combien les estimations individuelles reviennent vers la population.', 'Measures how strongly individual estimates return towards the population.'), limitation: both('20–30 % est une heuristique ; les diagnostics ETA deviennent progressivement moins informatifs.', '20–30% is a heuristic; ETA diagnostics become progressively less informative.'), chapter: 'bayes-ebes' },
  'Emax': { equation: 'E = E0 + Emax × C / (EC50 + C)', intuition: both('Relation phénoménologique avec plateau.', 'Phenomenological relationship with a plateau.'), limitation: both('Le plateau ne prouve pas une saturation des récepteurs.', 'The plateau does not prove receptor saturation.'), chapter: 'pd-direct', lab: 'pd-general' },
  'CMI': { unit: 'mg/L', intuition: both('Mesure microbiologique discrète et dépendante de la méthode.', 'Discrete microbiological measurement that depends on method.'), limitation: both('Ne pas la traiter comme une constante exacte du patient.', 'Do not treat it as an exact patient constant.'), chapter: 'infectio-pkpd', lab: 'pd-infectiology' },
  'PTA': { unit: '%', intuition: both('Fréquence simulée d’atteinte d’une cible définie.', 'Simulated frequency of attaining a defined target.'), limitation: both('Conditionnelle au modèle, à la population, au schéma et à la cible.', 'Conditional on model, population, regimen and target.'), chapter: 'infectio-pkpd', lab: 'pd-infectiology' }
};
