import {
  describe, oneSampleT, welchT, pairedT, mannWhitney, wilcoxonSignedRank,
  welchAnova, kruskalWallis, pearson, spearman, linearRegression,
  autoCategorical, mcnemar, logRank
} from './engine.js';
import { friedmanLong } from './advanced-engine.js';
import { logisticRegression } from './regression-engine.js';
import { multivariableLinearRegression } from './multivariable-engine.js';

const page=document.body.dataset.statsPage||'landing';
const dict={
  fr:{
    open:'Ouvrir l’outil',home:'Accueil',tools:'Outils & projets',methods:'Méthodes',language:'English',ready:'Données lues',rows:'lignes',columns:'colonnes',run:'Analyser',parse:'Lire les données',demo:'Charger une démo',chooseColumns:'Associez les colonnes',result:'Résultat',primary:'Analyse principale',sensitivity:'Analyse de sensibilité',assumptions:'À vérifier avant d’interpréter',
    pExplain:'La p-value mesure la compatibilité des données avec l’hypothèse nulle. Elle ne mesure ni la taille ni l’importance clinique de l’effet.',ciExplain:'L’intervalle de confiance à 95 % indique la plage de valeurs compatibles avec les données et le modèle, avec l’incertitude d’échantillonnage.',effectExplain:'La taille d’effet quantifie l’amplitude de la différence ou de l’association. Elle doit être lue avec son intervalle de confiance et le contexte clinique.',
    error:'Impossible de lancer l’analyse',noData:'Collez des données ou chargez une démo puis cliquez sur « Lire les données ».',h0Compatible:'Les données restent compatibles avec l’hypothèse nulle au seuil de 5 %. Cela ne prouve pas l’absence d’effet.',h0Low:'Les données sont peu compatibles avec l’hypothèse nulle au seuil de 5 %. La taille d’effet et son incertitude restent nécessaires pour juger l’importance du résultat.',browser:'Calcul effectué localement dans votre navigateur. Aucune donnée n’est envoyée à un serveur.',autoNote:'Le mode automatique n’utilise pas un test de normalité comme interrupteur. Pour une variable continue, il privilégie Welch et affiche le test de rang comme analyse de sensibilité.',
    selectTwo:'Cette analyse nécessite exactement deux groupes.',selectTwoSurv:'Le log-rank actuel compare exactement deux groupes.',nSmall:'Effectif insuffisant pour ce test.',binary:'McNemar nécessite deux modalités.',repeatedFew:'Friedman nécessite au moins trois conditions et au moins deux sujets complets.',duplicateRepeated:'Chaque couple sujet × condition doit apparaître une seule fois.',logisticBinary:'La régression logistique nécessite exactement deux modalités non manquantes pour la réponse.',logisticClassSmall:'Il faut au moins deux événements et deux non-événements parmi les observations analysables.',logisticConstant:'Le prédicteur quantitatif doit varier entre les observations.',multivarPredictors:'Sélectionnez au moins deux prédicteurs quantitatifs.',multivarDf:'Effectif insuffisant par rapport au nombre de prédicteurs pour estimer ce modèle.',multivarCollinear:'Les prédicteurs sont exactement ou presque exactement colinéaires. Retirez ou reformulez les variables redondantes.',multivarOutcomeConstant:'La variable réponse doit varier entre les observations.',generic:'Vérifiez le format et les colonnes sélectionnées.'
  },
  en:{
    open:'Open the tool',home:'Home',tools:'Tools & projects',methods:'Methods',language:'Français',ready:'Data parsed',rows:'rows',columns:'columns',run:'Analyze',parse:'Parse data',demo:'Load demo',chooseColumns:'Map columns',result:'Result',primary:'Primary analysis',sensitivity:'Sensitivity analysis',assumptions:'Check before interpreting',
    pExplain:'The p-value measures compatibility of the data with the null hypothesis. It does not measure effect size or clinical importance.',ciExplain:'A 95% confidence interval gives a range of values compatible with the data and model, reflecting sampling uncertainty.',effectExplain:'Effect size quantifies the magnitude of a difference or association. Read it with its confidence interval and clinical context.',
    error:'Analysis could not be run',noData:'Paste data or load a demo, then click “Parse data”.',h0Compatible:'The data remain compatible with the null hypothesis at the 5% threshold. This does not prove absence of an effect.',h0Low:'The data are relatively incompatible with the null hypothesis at the 5% threshold. Effect size and uncertainty are still needed to judge importance.',browser:'Computation is performed locally in your browser. No data are sent to a server.',autoNote:'Automatic mode does not use a normality test as an on/off switch. For continuous outcomes it defaults to Welch and displays a rank-based sensitivity analysis.',
    selectTwo:'This analysis requires exactly two groups.',selectTwoSurv:'The current log-rank module compares exactly two groups.',nSmall:'Sample size is too small for this test.',binary:'McNemar requires two categories.',repeatedFew:'Friedman requires at least three conditions and at least two complete subjects.',duplicateRepeated:'Each subject × condition combination must appear only once.',logisticBinary:'Logistic regression requires exactly two non-missing outcome categories.',logisticClassSmall:'At least two events and two non-events are required among analyzable observations.',logisticConstant:'The numeric predictor must vary across observations.',multivarPredictors:'Select at least two numeric predictors.',multivarDf:'Sample size is too small for the number of predictors in this model.',multivarCollinear:'Predictors are exactly or nearly exactly collinear. Remove or reformulate redundant variables.',multivarOutcomeConstant:'The outcome must vary across observations.',generic:'Check the data format and selected columns.'
  }
};
let lang=localStorage.getItem('stats-language')||'fr';
const t=key=>dict[lang][key]||key;
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-fr][data-en]').forEach(el=>{el.textContent=el.dataset[lang];});document.querySelectorAll('[data-lang-toggle]').forEach(b=>b.textContent=t('language'));localStorage.setItem('stats-language',lang);if(page==='tool')updateMethodGuide();}
document.addEventListener('click',e=>{const toggle=e.target.closest('[data-lang-toggle]');if(toggle){lang=lang==='fr'?'en':'fr';applyLanguage();}});

const tooltip=document.createElement('div');tooltip.className='stats-tooltip';tooltip.setAttribute('role','tooltip');tooltip.hidden=true;document.body.appendChild(tooltip);
function showTooltip(el){tooltip.textContent=el.dataset.help||'';tooltip.hidden=false;const r=el.getBoundingClientRect(),w=Math.min(330,window.innerWidth-24);tooltip.style.width=`${w}px`;const left=Math.min(window.innerWidth-w-12,Math.max(12,r.left+r.width/2-w/2));let top=r.bottom+8;if(top+140>window.innerHeight)top=Math.max(12,r.top-148);tooltip.style.left=`${left}px`;tooltip.style.top=`${top}px`;}
document.addEventListener('mouseover',e=>{const el=e.target.closest('[data-help]');if(el)showTooltip(el);});document.addEventListener('focusin',e=>{const el=e.target.closest('[data-help]');if(el)showTooltip(el);});document.addEventListener('mouseout',e=>{if(e.target.closest?.('[data-help]'))tooltip.hidden=true;});document.addEventListener('focusout',e=>{if(e.target.closest?.('[data-help]'))tooltip.hidden=true;});

if(page==='tool')initTool();applyLanguage();

function parseLine(line,delimiter){const out=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++;}else quote=!quote;}else if(ch===delimiter&&!quote){out.push(cur.trim());cur='';}else cur+=ch;}out.push(cur.trim());return out;}
function parseTable(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('NO_DATA');const first=lines[0],delimiter=first.includes('\t')?'\t':first.includes(';')?';':',';const headers=parseLine(first,delimiter).map((h,i)=>h||`col_${i+1}`);const rows=lines.slice(1).map(line=>{const vals=parseLine(line,delimiter),r={};headers.forEach((h,i)=>r[h]=vals[i]??'');return r;});return {headers,rows};}
function fmt(x,d=3){if(!Number.isFinite(x))return '—';const a=Math.abs(x);if(a!==0&&(a>=10000||a<0.001))return x.toExponential(2);return x.toFixed(d).replace(/\.000$/,'');}
function fmtP(p){if(!Number.isFinite(p))return '—';if(p<0.0001)return '< 0.0001';return '= '+p.toFixed(4);}
const ci=value=>value&&value.length===2?`[${fmt(value[0])} ; ${fmt(value[1])}]`:'—';
const escapeHtml=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

let parsed=null;
const demos={
  compare2:`group,value\nControl,11.2\nControl,10.8\nControl,12.1\nControl,9.9\nControl,11.5\nControl,10.4\nTreatment,8.2\nTreatment,9.1\nTreatment,7.8\nTreatment,8.7\nTreatment,9.4\nTreatment,8.5`,
  paired:`before,after\n18.2,15.1\n16.9,15.7\n20.1,17.4\n17.5,16.2\n19.3,16.8\n15.8,14.9\n21.0,18.3\n18.7,16.5`,
  repeatedk:`subject,condition,value\nS1,A,0\nS1,B,1\nS1,C,20\nS2,A,0\nS2,B,2\nS2,C,22\nS3,A,0\nS3,B,3\nS3,C,24\nS4,A,0\nS4,B,4\nS4,C,26\nS5,A,0\nS5,B,5\nS5,C,28\nS6,A,0\nS6,B,6\nS6,C,30\nS7,A,0\nS7,B,7\nS7,C,32\nS8,A,0\nS8,B,8\nS8,C,34`,
  comparek:`group,value\nA,10.1\nA,11.2\nA,9.8\nA,10.7\nB,12.9\nB,13.5\nB,11.8\nB,14.1\nC,16.0\nC,15.2\nC,17.1\nC,16.4`,
  categorical:`treatment,response\nA,yes\nA,yes\nA,no\nA,yes\nA,no\nA,yes\nB,no\nB,no\nB,yes\nB,no\nB,no\nB,yes`,
  mcnemar:`before,after\nno,yes\nno,yes\nyes,yes\nyes,no\nno,no\nyes,yes\nno,yes\nyes,yes\nno,no\nyes,no`,
  association:`x,y\n1,2.2\n2,2.8\n3,4.1\n4,4.8\n5,6.2\n6,6.5\n7,8.1\n8,8.6\n9,10.1\n10,10.7`,
  logistic:`x,outcome\n1,no\n2,no\n3,no\n4,no\n5,yes\n6,no\n7,yes\n8,yes\n9,yes\n10,yes`,
  multivariable:`age,biomarker,outcome\n30,1.2,12.1\n35,0.8,13.8\n40,1.5,14.4\n45,1.1,16.2\n50,1.9,17.5\n55,1.4,18.0\n60,2.2,20.7\n65,1.7,21.2\n70,2.5,23.5\n75,2.0,24.1\n38,0.9,14.0\n48,1.6,17.1\n58,1.3,19.0\n68,2.1,22.4`,
  survival:`group,time,event\nA,3,1\nA,5,1\nA,7,0\nA,8,1\nA,11,0\nA,12,1\nB,4,1\nB,7,1\nB,9,1\nB,10,0\nB,13,0\nB,14,1`,
  descriptive:`value\n12.1\n10.8\n11.4\n13.2\n9.9\n12.5\n11.7\n10.6`,oneSample:`value\n102\n98\n101\n105\n99\n103\n100\n104`
};

function initTool(){const mode=document.querySelector('#analysis-mode'),textarea=document.querySelector('#data-input'),parseBtn=document.querySelector('#parse-data'),demoBtn=document.querySelector('#load-demo'),runBtn=document.querySelector('#run-analysis');mode.addEventListener('change',()=>{parsed=null;document.querySelector('#mapping').hidden=true;document.querySelector('#results').innerHTML='';document.querySelector('#logistic-event-wrap')?.remove();document.querySelector('#multivariable-predictors-wrap')?.remove();updateMethodGuide();});demoBtn.addEventListener('click',()=>{textarea.value=demos[mode.value]||demos.compare2;parseCurrent();});parseBtn.addEventListener('click',parseCurrent);runBtn.addEventListener('click',runAnalysis);updateMethodGuide();}
function parseCurrent(){try{parsed=parseTable(document.querySelector('#data-input').value);const status=document.querySelector('#parse-status');status.className='parse-status ok';status.textContent=`${t('ready')} · ${parsed.rows.length} ${t('rows')} · ${parsed.headers.length} ${t('columns')}`;populateMapping();}catch(e){parsed=null;showError(t('noData'));}}
function modeConfig(){const m=document.querySelector('#analysis-mode').value;const cfg={compare2:[['group','Groupe','Group'],['value','Variable quantitative','Numeric outcome']],paired:[['x','Avant / mesure 1','Before / measure 1'],['y','Après / mesure 2','After / measure 2']],repeatedk:[['subject','Sujet / unité','Subject / unit'],['condition','Condition / temps','Condition / time'],['value','Variable quantitative','Numeric outcome']],comparek:[['group','Groupe','Group'],['value','Variable quantitative','Numeric outcome']],categorical:[['x','Facteur / exposition','Factor / exposure'],['y','Réponse catégorielle','Categorical outcome']],mcnemar:[['x','Avant','Before'],['y','Après','After']],association:[['x','Variable X','Variable X'],['y','Variable Y','Variable Y']],logistic:[['x','Prédicteur quantitatif','Numeric predictor'],['y','Réponse binaire','Binary outcome']],multivariable:[['y','Variable réponse quantitative','Quantitative outcome']],survival:[['group','Groupe','Group'],['time','Temps','Time'],['event','Événement (1=oui, 0=censuré)','Event (1=yes, 0=censored)']],descriptive:[['value','Variable quantitative','Numeric variable']],oneSample:[['value','Variable quantitative','Numeric variable']]};return cfg[m]||cfg.compare2;}
function syncLogisticEvent(){
  document.querySelector('#logistic-event-wrap')?.remove();
  if(!parsed||document.querySelector('#analysis-mode')?.value!=='logistic')return;
  const yKey=selected('y');if(!yKey)return;
  const categories=[...new Set(parsed.rows.map(r=>String(r[yKey]??'').trim()).filter(Boolean))];
  const host=document.querySelector('.mapping-options');if(!host)return;
  const label=document.createElement('label');label.id='logistic-event-wrap';label.innerHTML=`<span data-fr="Modalité considérée comme événement (Y=1)" data-en="Category treated as event (Y=1)">${lang==='fr'?'Modalité considérée comme événement (Y=1)':'Category treated as event (Y=1)'}</span><select id="logistic-event">${categories.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('')}</select>`;host.appendChild(label);
}
function numericColumn(name){const values=parsed.rows.map(r=>String(r[name]??'').trim()).filter(Boolean);return values.length>0&&values.every(v=>Number.isFinite(Number(v.replace(',','.'))));}
function syncMultivariablePredictors(){
  document.querySelector('#multivariable-predictors-wrap')?.remove();
  if(!parsed||document.querySelector('#analysis-mode')?.value!=='multivariable')return;
  const yKey=selected('y');if(!yKey)return;
  const candidates=parsed.headers.filter(h=>h!==yKey&&numericColumn(h));
  const host=document.querySelector('.mapping-options');if(!host)return;
  const fieldset=document.createElement('fieldset');fieldset.id='multivariable-predictors-wrap';fieldset.className='predictor-picker';
  fieldset.innerHTML=`<legend>${lang==='fr'?'Prédicteurs quantitatifs (2 ou plus)':'Numeric predictors (2 or more)'}</legend><div class="predictor-options">${candidates.map(h=>`<label><input type="checkbox" name="multivariable-predictor" value="${escapeHtml(h)}" checked> <span>${escapeHtml(h)}</span></label>`).join('')}</div><small>${lang==='fr'?'Seules les colonnes entièrement numériques sont proposées. Les lignes incomplètes sont exclues par cas complet.':'Only fully numeric columns are offered. Incomplete rows are excluded by complete-case analysis.'}</small>`;
  host.appendChild(fieldset);
}
function populateMapping(){const wrap=document.querySelector('#column-selectors');wrap.innerHTML='';for(const [id,fr,en] of modeConfig()){const label=document.createElement('label');label.innerHTML=`<span>${lang==='fr'?fr:en}</span><select id="col-${id}">${parsed.headers.map(h=>`<option value="${escapeHtml(h)}">${escapeHtml(h)}</option>`).join('')}</select>`;wrap.appendChild(label);}modeConfig().forEach(([id],i)=>{const sel=document.querySelector(`#col-${id}`);if(parsed.headers[i])sel.value=parsed.headers[i];});const mode=document.querySelector('#analysis-mode').value;if(mode==='multivariable'&&parsed.headers.includes('outcome'))document.querySelector('#col-y').value='outcome';document.querySelector('#reference-wrap').hidden=mode!=='oneSample';document.querySelector('#method-wrap').hidden=!['compare2','paired','comparek'].includes(mode);document.querySelector('#mapping').hidden=false;if(mode==='logistic'){document.querySelector('#col-y')?.addEventListener('change',syncLogisticEvent);syncLogisticEvent();}else document.querySelector('#logistic-event-wrap')?.remove();if(mode==='multivariable'){document.querySelector('#col-y')?.addEventListener('change',syncMultivariablePredictors);syncMultivariablePredictors();}else document.querySelector('#multivariable-predictors-wrap')?.remove();}
const selected=id=>document.querySelector(`#col-${id}`)?.value;
const col=name=>parsed.rows.map(r=>r[name]);
function splitGroups(gKey,vKey){const names=[...new Set(parsed.rows.map(r=>String(r[gKey])).filter(Boolean))];return names.map(name=>({name,values:parsed.rows.filter(r=>String(r[gKey])===name).map(r=>r[vKey])}));}

function updateMethodGuide(){
  if(page!=='tool')return;const mode=document.querySelector('#analysis-mode')?.value||'compare2',guide=document.querySelector('#method-guide');if(!guide)return;
  const fr={compare2:['Deux groupes indépendants','Welch t par défaut + Mann–Whitney en sensibilité','Welch compare les moyennes sans supposer des variances égales. Le test de rang répond à une question différente et est affiché comme sensibilité.'],paired:['Deux mesures appariées','t apparié + Wilcoxon signé','Les deux colonnes doivent correspondre aux mêmes sujets ou unités, dans le même ordre.'],repeatedk:['Au moins trois mesures répétées','Friedman + Wilcoxon appariés avec Holm','Le format long sujet / condition / valeur conserve l’appariement. Friedman classe les conditions au sein de chaque sujet ; les sujets incomplets sont signalés et exclus du bloc commun.'],comparek:['Plus de deux groupes indépendants','ANOVA de Welch + Kruskal–Wallis','Welch évite l’hypothèse de variances égales. Kruskal–Wallis fournit une analyse de rang complémentaire.'],categorical:['Deux variables catégorielles','χ² ou Fisher exact automatiquement','Fisher est choisi pour un tableau 2×2 lorsque les effectifs attendus sont faibles.'],mcnemar:['Réponse binaire appariée','McNemar','Conçu pour un avant/après binaire ou deux mesures appariées.'],association:['Deux variables quantitatives','Pearson + Spearman + régression linéaire','Pearson/régression quantifient l’association linéaire ; Spearman et Kendall quantifient une association monotone par les rangs.'],logistic:['Réponse binaire et prédicteur quantitatif','Régression logistique binaire','Le modèle estime comment les odds de la modalité choisie comme événement varient pour +1 unité du prédicteur. Le codage de Y=1 est toujours affiché explicitement.'],multivariable:['Réponse quantitative et plusieurs prédicteurs','Régression linéaire multivariable','Le modèle estime l’association de chaque prédicteur avec la réponse en maintenant les autres prédicteurs du modèle constants. Les VIF et diagnostics d’influence sont affichés sans suppression automatique.'],survival:['Temps jusqu’à événement','Log-rank, deux groupes','Compare les courbes de survie en utilisant les événements observés et les sujets encore à risque.'],descriptive:['Décrire une variable','Moyenne, écart-type, médiane, IQR, IC95 %','Aucun test d’hypothèse : uniquement une description de l’échantillon.'],oneSample:['Comparer une moyenne à une valeur','t à un échantillon','Teste si la moyenne est compatible avec une valeur de référence fixée à l’avance.']};
  const en={compare2:['Two independent groups','Welch t by default + Mann–Whitney sensitivity','Welch compares means without assuming equal variances. The rank test answers a different question and is shown as a sensitivity analysis.'],paired:['Two paired measurements','Paired t + signed-rank Wilcoxon','The two columns must refer to the same subjects or units in the same order.'],repeatedk:['At least three repeated measurements','Friedman + paired Wilcoxon with Holm','Long-format subject / condition / value data preserve pairing. Friedman ranks conditions within subjects; incomplete subjects are reported and excluded from the common block.'],comparek:['More than two independent groups','Welch ANOVA + Kruskal–Wallis','Welch avoids the equal-variance assumption. Kruskal–Wallis provides a complementary rank-based analysis.'],categorical:['Two categorical variables','χ² or Fisher exact automatically','Fisher is selected for a 2×2 table when expected counts are small.'],mcnemar:['Paired binary outcome','McNemar','Designed for binary before/after data or two paired binary measurements.'],association:['Two numeric variables','Pearson + Spearman + linear regression','Pearson/regression quantify linear association; Spearman and Kendall quantify monotonic rank association.'],logistic:['Binary outcome and numeric predictor','Binary logistic regression','The model estimates how the odds of the category chosen as the event change for a +1-unit increase in the predictor. Y=1 coding is always shown explicitly.'],multivariable:['Quantitative outcome and multiple predictors','Multivariable linear regression','The model estimates each predictor association with the outcome while holding the other included predictors constant. VIF and influence diagnostics are shown without automatic deletion.'],survival:['Time-to-event outcome','Log-rank, two groups','Compares survival curves using observed events and participants still at risk.'],descriptive:['Describe one variable','Mean, SD, median, IQR, 95% CI','No hypothesis test: descriptive summary only.'],oneSample:['Compare a mean with a value','One-sample t','Tests whether the mean is compatible with a pre-specified reference value.']};
  const a=(lang==='fr'?fr:en)[mode];guide.innerHTML=`<span class="method-kicker">${a[0]}</span><strong>${a[1]}</strong><p>${a[2]}</p>${['compare2','paired','comparek'].includes(mode)?`<small>${t('autoNote')}</small>`:''}`;
}
function showError(message){document.querySelector('#results').innerHTML=`<div class="result-error"><strong>${t('error')}</strong><p>${escapeHtml(message)}</p></div>`;}
function errorMessage(e){const m=String(e.message||e);if(m.includes('CONDITIONS_TOO_FEW'))return t('repeatedFew');if(m.includes('DUPLICATE_REPEATED_CELL'))return t('duplicateRepeated');if(m.includes('LOGISTIC_OUTCOME_NOT_BINARY'))return t('logisticBinary');if(m.includes('LOGISTIC_CLASS_TOO_SMALL'))return t('logisticClassSmall');if(m.includes('MULTIVARIABLE_PREDICTORS_TOO_FEW'))return t('multivarPredictors');if(m.includes('MULTIVARIABLE_DF_TOO_SMALL'))return t('multivarDf');if(m.includes('MULTIVARIABLE_COLLINEAR'))return t('multivarCollinear');if(m.includes('OUTCOME_CONSTANT'))return t('multivarOutcomeConstant');if(m.includes('PREDICTOR_CONSTANT'))return t('logisticConstant');if(m.includes('GROUPS_TOO_FEW')||m.includes('NOT_2X2'))return t('selectTwo');if(m.includes('SURVIVAL_TWO_GROUPS'))return t('selectTwoSurv');if(m.includes('N_TOO_SMALL'))return t('nSmall');if(m.includes('NOT_BINARY'))return t('binary');return t('generic');}
const pInterpret=p=>p<0.05?t('h0Low'):t('h0Compatible');
function statBlock(label,value,help=''){return `<div class="metric"><span>${label}${help?` <button class="help" type="button" data-help="${escapeHtml(help)}" aria-label="Help">?</button>`:''}</span><strong>${value}</strong></div>`;}
function testTitle(test){const names={welch_t:'Welch t',mann_whitney:'Mann–Whitney',paired_t:lang==='fr'?'t apparié':'Paired t',wilcoxon_signed_rank:'Wilcoxon signed-rank',friedman:'Friedman',welch_anova:'Welch ANOVA',anova:'ANOVA',kruskal_wallis:'Kruskal–Wallis',chi_square:'χ²',fisher_exact:'Fisher exact',mcnemar:'McNemar',pearson:'Pearson',spearman:'Spearman',linear_regression:lang==='fr'?'Régression linéaire':'Linear regression',multivariable_linear_regression:lang==='fr'?'Régression linéaire multivariable':'Multivariable linear regression',logistic_regression:lang==='fr'?'Régression logistique':'Logistic regression',log_rank:'Log-rank',one_sample_t:lang==='fr'?'t à un échantillon':'One-sample t'};return names[test]||test;}
function renderCard(r,label=t('primary')){
  let metrics='',detail='';
  if(r.test==='welch_t')metrics=statBlock(lang==='fr'?'Différence de moyennes':'Mean difference',fmt(r.estimate))+statBlock('IC95 %',ci(r.ci),t('ciExplain'))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('Hedges g',fmt(r.hedges_g),t('effectExplain'));
  else if(r.test==='paired_t')metrics=statBlock(lang==='fr'?'Différence moyenne':'Mean difference',fmt(r.estimate))+statBlock('IC95 %',ci(r.ci),t('ciExplain'))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('dz',fmt(r.dz),t('effectExplain'));
  else if(r.test==='mann_whitney')metrics=statBlock('U',fmt(r.U))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('Cliff δ',fmt(r.cliffs_delta),t('effectExplain'))+statBlock(lang==='fr'?'Médianes':'Medians',`${fmt(r.median1)} / ${fmt(r.median2)}`);
  else if(r.test==='wilcoxon_signed_rank')metrics=statBlock('W+',fmt(r.Wplus))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock(lang==='fr'?'Différence médiane':'Median difference',fmt(r.median_difference))+statBlock(lang==='fr'?'Corrélation bisérielle de rang':'Rank-biserial correlation',fmt(r.rank_biserial),t('effectExplain'));
  else if(r.test==='friedman'){metrics=statBlock('Q',fmt(r.Q))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('Kendall W',fmt(r.kendallW),t('effectExplain'))+statBlock(lang==='fr'?'Sujets complets':'Complete subjects',String(r.n))+statBlock(lang==='fr'?'Conditions':'Conditions',String(r.k));if(r.excludedSubjects>0)detail+=`<p class="plain-interpretation">${escapeHtml(lang==='fr'?`${r.excludedSubjects} sujet(s) incomplet(s) exclu(s) du bloc commun.`:`${r.excludedSubjects} incomplete subject(s) excluded from the common block.`)}</p>`;}
  else if(r.test==='welch_anova'||r.test==='anova')metrics=statBlock('F',fmt(r.F))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('η²',fmt(r.eta2),t('effectExplain'))+statBlock(lang==='fr'?'Groupes':'Groups',String(r.k));
  else if(r.test==='kruskal_wallis')metrics=statBlock('H',fmt(r.H))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('df',fmt(r.df,0));
  else if(r.test==='chi_square')metrics=statBlock('χ²',fmt(r.x2))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('Cramér V',fmt(r.cramers_v),t('effectExplain'))+statBlock(lang==='fr'?'Effectif attendu min.':'Min expected count',fmt(r.minExpected));
  else if(r.test==='fisher_exact')metrics=statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('Odds ratio',fmt(r.odds_ratio),t('effectExplain'));
  else if(r.test==='mcnemar')metrics=statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('b / c',`${r.b} / ${r.c}`)+statBlock(lang==='fr'?'Méthode':'Method',r.exact?'Exact':'χ²');
  else if(r.test==='pearson')metrics=statBlock('r',fmt(r.r),t('effectExplain'))+statBlock('IC95 %',ci(r.ci),t('ciExplain'))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('n',String(r.n));
  else if(r.test==='spearman')metrics=statBlock('ρ',fmt(r.rho),t('effectExplain'))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('n',String(r.n));
  else if(r.test==='linear_regression')metrics=statBlock(lang==='fr'?'Pente β':'Slope β',fmt(r.slope),t('effectExplain'))+statBlock('IC95 %',ci(r.ci),t('ciExplain'))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('R²',fmt(r.r2));
  else if(r.test==='logistic_regression'){
    metrics=statBlock(lang==='fr'?'Odds ratio (+1 unité)':'Odds ratio (+1 unit)',fmt(r.oddsRatio),t('effectExplain'))+statBlock('IC95 % OR',ci(r.oddsRatioCI),t('ciExplain'))+statBlock('p Wald',fmtP(r.p),t('pExplain'))+statBlock(lang==='fr'?'p rapport de vraisemblance':'Likelihood-ratio p',fmtP(r.pLikelihoodRatio),t('pExplain'))+statBlock('McFadden R²',fmt(r.mcfaddenR2))+statBlock('n',String(r.n));
    detail+=`<p class="group-order"><strong>Y=1:</strong> ${escapeHtml(r.event)} · <strong>Y=0:</strong> ${escapeHtml(r.reference)} · ${escapeHtml(r.predictorName)}</p>`;
    if(r.separationLikely)detail+=`<p class="result-warning"><strong>${escapeHtml(lang==='fr'?'Alerte de stabilité':'Stability warning')}</strong> — ${escapeHtml(lang==='fr'?'Le modèle ne fournit pas une MLE stable (non-convergence, matrice quasi-singulière ou séparation probable). Les OR et p-values ne doivent pas être interprétés comme un résultat standard ; une régression pénalisée ou exacte est à envisager.':'The model does not provide a stable MLE (non-convergence, near-singular information matrix or likely separation). ORs and p-values should not be interpreted as a standard result; penalized or exact logistic regression should be considered.')}</p>`;
    else detail+=`<p class="plain-interpretation">${pInterpret(r.p)}</p>`;
    detail+=`<p class="model-note">${escapeHtml(lang==='fr'?`Convergence en ${r.iterations} itération(s). ${r.events} événement(s), ${r.nonEvents} non-événement(s).`:`Converged in ${r.iterations} iteration(s). ${r.events} event(s), ${r.nonEvents} non-event(s).`)}</p>`;
  }
  else if(r.test==='log_rank')metrics=statBlock('χ²',fmt(r.x2))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock(lang==='fr'?'Événements':'Events',String(r.events))+statBlock('n',String(r.n));
  else if(r.test==='one_sample_t')metrics=statBlock(lang==='fr'?'Différence à la référence':'Difference from reference',fmt(r.estimate))+statBlock('IC95 %',ci(r.ci),t('ciExplain'))+statBlock('p',fmtP(r.p),t('pExplain'))+statBlock('n',String(r.n));
  if(Number.isFinite(r.p)&&r.test!=='logistic_regression')detail+=`<p class="plain-interpretation">${pInterpret(r.p)}</p>`;
  return `<article class="result-card"><div class="result-card-head"><span>${label}</span><h3>${testTitle(r.test)}</h3></div><div class="metrics">${metrics}</div>${detail}</article>`;
}
function renderMultivariable(r){
  const coeffRows=r.coefficients.map((coef,i)=>`<tr><td><strong>${escapeHtml(coef.name)}</strong></td><td>${fmt(coef.estimate)}</td><td>${fmt(coef.se)}</td><td>${ci(coef.ci)}</td><td>${fmt(coef.t)}</td><td>${fmtP(coef.p)}</td><td>${i===0?'—':fmt(coef.vif)}</td></tr>`).join('');
  const flagged=r.influential.slice(0,10).map(row=>`<tr><td>${row.row}</td><td>${fmt(row.cook)}</td><td>${fmt(row.leverage)}</td><td>${fmt(row.standardizedResidual)}</td></tr>`).join('');
  const vifWarning=r.maxVIF>5?`<p class="result-warning"><strong>${escapeHtml(lang==='fr'?'Colinéarité à examiner':'Collinearity to review')}</strong> — ${escapeHtml(lang==='fr'?`VIF maximal = ${fmt(r.maxVIF)}. Un VIF élevé signale qu’un coefficient peut être instable ; ce seuil est un repère, pas une règle de suppression.`:`Maximum VIF = ${fmt(r.maxVIF)}. A high VIF indicates that a coefficient may be unstable; this threshold is a diagnostic guide, not an automatic deletion rule.`)}</p>`:'';
  return `<article class="result-card multivariable-result"><div class="result-card-head"><span>${t('primary')}</span><h3>${testTitle(r.test)}</h3></div><div class="metrics">${statBlock('R²',fmt(r.r2),t('effectExplain'))}${statBlock('R² ajusté',fmt(r.adjustedR2))}${statBlock('F',fmt(r.f))}${statBlock('p global',fmtP(r.pGlobal),t('pExplain'))}${statBlock(lang==='fr'?'Erreur résiduelle':'Residual SE',fmt(r.residualSE))}${statBlock('n',String(r.n))}</div><p class="plain-interpretation">${pInterpret(r.pGlobal)}</p>${r.droppedRows>0?`<p class="model-note">${escapeHtml(lang==='fr'?`${r.droppedRows} ligne(s) exclue(s) car au moins une variable du modèle était manquante ou non numérique.`:`${r.droppedRows} row(s) excluded because at least one model variable was missing or non-numeric.`)}</p>`:''}<section class="posthoc-section"><h3>${escapeHtml(lang==='fr'?'Coefficients ajustés':'Adjusted coefficients')}</h3><div class="posthoc-wrap"><table class="posthoc-table multivariable-coefficients"><thead><tr><th>${escapeHtml(lang==='fr'?'Terme':'Term')}</th><th>β</th><th>SE</th><th>IC95 %</th><th>t</th><th>p</th><th>VIF</th></tr></thead><tbody>${coeffRows}</tbody></table></div></section><section class="diagnostic-section multivariable-diagnostics"><h3>${escapeHtml(lang==='fr'?'Diagnostics d’influence':'Influence diagnostics')}</h3><div class="metrics">${statBlock('Cook max',fmt(r.maxCook))}${statBlock(lang==='fr'?'Levier max':'Max leverage',fmt(r.maxLeverage))}${statBlock(lang==='fr'?'|résidu standardisé| max':'Max |standardized residual|',fmt(r.maxAbsStandardizedResidual))}${statBlock('VIF max',fmt(r.maxVIF))}</div><p>${escapeHtml(lang==='fr'?`Repères affichés : Cook > 4/n = ${fmt(r.cookThreshold)}, levier > 2(p+1)/n = ${fmt(r.leverageThreshold)}, |résidu standardisé| > 3. Ils servent à examiner des observations, jamais à les supprimer automatiquement.`:`Displayed guides: Cook > 4/n = ${fmt(r.cookThreshold)}, leverage > 2(p+1)/n = ${fmt(r.leverageThreshold)}, |standardized residual| > 3. They identify observations to review, never observations to delete automatically.`)}</p>${flagged?`<div class="posthoc-wrap"><table class="posthoc-table influence-table"><thead><tr><th>${escapeHtml(lang==='fr'?'Ligne':'Row')}</th><th>Cook</th><th>${escapeHtml(lang==='fr'?'Levier':'Leverage')}</th><th>${escapeHtml(lang==='fr'?'Résidu std.':'Std. residual')}</th></tr></thead><tbody>${flagged}</tbody></table></div>`:`<p class="model-note">${escapeHtml(lang==='fr'?'Aucune observation ne dépasse les repères d’influence affichés.':'No observation exceeds the displayed influence guides.')}</p>`}</section>${vifWarning}</article>`;
}
function assumptionList(mode){
  const fr={compare2:['Observations indépendantes entre groupes.','La variable est réellement quantitative si vous interprétez une différence de moyennes.','Les valeurs extrêmes doivent être examinées et justifiées, pas supprimées automatiquement.'],paired:['Chaque ligne relie correctement les deux mesures du même sujet ou de la même unité.','Pour le t apparié, c’est la distribution des différences qui importe.'],repeatedk:['Chaque identifiant correspond à la même unité suivie dans toutes les conditions.','Friedman utilise des blocs complets : un sujet sans l’une des conditions est exclu du test global et des post-hoc affichés.','Une différence globale doit être localisée avec des post-hoc appariés corrigés ; Kendall W quantifie la concordance/ampleur globale des rangs.'],comparek:['Observations indépendantes entre groupes.','Le test global indique qu’au moins un groupe diffère ; des comparaisons post-hoc corrigées sont nécessaires pour localiser les différences.'],categorical:['Utiliser des effectifs, pas des pourcentages déjà agrégés.','Les observations doivent être indépendantes. Fisher est utilisé en 2×2 si les effectifs attendus sont faibles.'],mcnemar:['Mesures réellement appariées et réponse binaire aux deux temps.'],association:['Relation linéaire pour Pearson/régression ; relation monotone pour Spearman/Kendall.','Une corrélation ne démontre pas une causalité.','Inspecter les valeurs influentes et la forme de la relation.'],multivariable:['Relation approximativement linéaire entre chaque prédicteur quantitatif et la réponse conditionnellement aux autres variables du modèle.','Observations indépendantes et variance résiduelle suffisamment homogène pour les IC/tests OLS usuels.','Examiner colinéarité, résidus et observations influentes. Les diagnostics ne justifient pas une suppression automatique.','Le coefficient d’un prédicteur est conditionnel aux autres variables incluses ; il ne démontre pas une causalité.'],logistic:['Observations indépendantes et réponse réellement binaire.','Pour un prédicteur quantitatif, la relation doit être suffisamment linéaire sur l’échelle du logit ; cela n’équivaut pas à une relation linéaire avec la probabilité.','Vérifier le nombre d’événements et de non-événements ainsi que la séparation. Une alerte de séparation invalide l’interprétation MLE standard.','Un OR décrit une association conditionnelle au modèle et ne démontre pas une causalité.'],survival:['Censure indépendante du risque étudié.','Le log-rank est surtout sensible à une différence globale des courbes ; les risques proportionnels facilitent son interprétation.'],descriptive:['Vérifier les unités et les valeurs aberrantes ou impossibles.'],oneSample:['La valeur de référence doit être définie indépendamment des données.','Observations indépendantes.']};
  const en={compare2:['Observations are independent between groups.','The outcome is genuinely quantitative if you interpret a difference in means.','Extreme values should be examined and justified, not automatically deleted.'],paired:['Each row correctly links two measurements from the same subject or unit.','For a paired t test, the distribution of within-pair differences matters.'],repeatedk:['Each identifier refers to the same unit observed under every condition.','Friedman uses complete blocks: a subject missing any condition is excluded from the global test and displayed post-hoc comparisons.','A global difference should be localized with corrected paired post-hoc tests; Kendall W quantifies the overall rank effect.'],comparek:['Observations are independent between groups.','A global test only says at least one group differs; corrected post-hoc comparisons are needed to localize differences.'],categorical:['Use counts, not already aggregated percentages.','Observations should be independent. Fisher is used in 2×2 tables when expected counts are small.'],mcnemar:['Measurements are truly paired and binary at both time points.'],association:['Linear relationship for Pearson/regression; monotonic relationship for Spearman/Kendall.','Correlation does not establish causality.','Inspect influential values and the shape of the relationship.'],multivariable:['Approximately linear relationship between each numeric predictor and the outcome conditional on the other model variables.','Independent observations and sufficiently homogeneous residual variance for usual OLS confidence intervals/tests.','Review collinearity, residuals and influential observations. Diagnostics do not justify automatic deletion.','A predictor coefficient is conditional on the other included variables and does not establish causality.'],logistic:['Observations are independent and the outcome is genuinely binary.','For a numeric predictor, the relationship should be reasonably linear on the logit scale; this is not the same as linearity with probability.','Check the number of events/non-events and separation. A separation warning invalidates standard MLE interpretation.','An OR is a model-based association measure and does not establish causality.'],survival:['Censoring is independent of the risk under study.','Log-rank is most sensitive to an overall curve difference; proportional hazards ease interpretation.'],descriptive:['Check units and impossible or extreme values.'],oneSample:['The reference value must be defined independently of the observed data.','Observations are independent.']};return (lang==='fr'?fr:en)[mode];
}
const renderAssumptions=mode=>`<section class="assumptions"><h3>${t('assumptions')}</h3><ul>${assumptionList(mode).map(x=>`<li>${x}</li>`).join('')}</ul></section>`;
function renderDescriptive(d){return `<article class="result-card"><div class="result-card-head"><span>${t('result')}</span><h3>${lang==='fr'?'Résumé descriptif':'Descriptive summary'}</h3></div><div class="metrics">${statBlock('n',d.n)}${statBlock(lang==='fr'?'Moyenne':'Mean',fmt(d.mean))}${statBlock('SD',fmt(d.sd))}${statBlock(lang==='fr'?'Médiane':'Median',fmt(d.median))}${statBlock('IQR',`[${fmt(d.q1)} ; ${fmt(d.q3)}]`)}${statBlock(lang==='fr'?'IC95 % moyenne':'95% CI mean',ci(d.ci),t('ciExplain'))}</div></article>`;}
function runAnalysis(){
  if(!parsed){showError(t('noData'));return;}const mode=document.querySelector('#analysis-mode').value,method=document.querySelector('#method-choice')?.value||'auto';
  try{
    let html='';
    if(mode==='descriptive')html=renderDescriptive(describe(col(selected('value'))));
    else if(mode==='oneSample'){const ref=Number(document.querySelector('#reference-value').value);html=renderCard(oneSampleT(col(selected('value')),ref));}
    else if(mode==='compare2'){const gs=splitGroups(selected('group'),selected('value'));if(gs.length!==2)throw new Error('GROUPS_TOO_FEW');const p=welchT(gs[0].values,gs[1].values),s=mannWhitney(gs[0].values,gs[1].values);html=method==='rank'?renderCard(s):method==='parametric'?renderCard(p):renderCard(p)+renderCard(s,t('sensitivity'));html+=`<p class="group-order">${escapeHtml(gs[0].name)} − ${escapeHtml(gs[1].name)}</p>`;}
    else if(mode==='paired'){const a=col(selected('x')),b=col(selected('y')),p=pairedT(a,b),s=wilcoxonSignedRank(a,b);html=method==='rank'?renderCard(s):method==='parametric'?renderCard(p):renderCard(p)+renderCard(s,t('sensitivity'));}
    else if(mode==='repeatedk')html=renderCard(friedmanLong(parsed.rows,selected('subject'),selected('condition'),selected('value')));
    else if(mode==='comparek'){const gs=splitGroups(selected('group'),selected('value'));if(gs.length<3)throw new Error('GROUPS_TOO_FEW');const p=welchAnova(gs),s=kruskalWallis(gs);html=method==='rank'?renderCard(s):method==='parametric'?renderCard(p):renderCard(p)+renderCard(s,t('sensitivity'));}
    else if(mode==='categorical')html=renderCard(autoCategorical(parsed.rows,selected('x'),selected('y')));
    else if(mode==='mcnemar')html=renderCard(mcnemar(parsed.rows,selected('x'),selected('y')));
    else if(mode==='association'){const a=col(selected('x')),b=col(selected('y'));html=renderCard(pearson(a,b))+renderCard(spearman(a,b),t('sensitivity'))+renderCard(linearRegression(a,b),lang==='fr'?'Modèle complémentaire':'Additional model');}
    else if(mode==='multivariable'){
      const yKey=selected('y');
      const predictors=[...document.querySelectorAll('input[name="multivariable-predictor"]:checked')].map(el=>el.value);
      if(predictors.length<2)throw new Error('MULTIVARIABLE_PREDICTORS_TOO_FEW');
      const fit=multivariableLinearRegression(col(yKey),predictors.map(name=>col(name)),predictors);
      html=renderMultivariable(fit);
    }
    else if(mode==='logistic'){
      const xKey=selected('x'),yKey=selected('y');
      const categories=[...new Set(parsed.rows.map(r=>String(r[yKey]??'').trim()).filter(Boolean))];
      if(categories.length!==2)throw new Error('LOGISTIC_OUTCOME_NOT_BINARY');
      const event=document.querySelector('#logistic-event')?.value||categories[0],reference=categories.find(v=>v!==event);
      const rows=parsed.rows.map(r=>({outcome:String(r[yKey]??'').trim(),x:Number(String(r[xKey]??'').trim().replace(',','.'))})).filter(r=>categories.includes(r.outcome)&&Number.isFinite(r.x));
      const fit=logisticRegression(rows.map(r=>r.outcome===event?1:0),rows.map(r=>r.x));
      html=renderCard({...fit,event,reference,predictorName:xKey});
    }
    else if(mode==='survival')html=renderCard(logRank(parsed.rows,selected('group'),selected('time'),selected('event')));
    html+=renderAssumptions(mode)+`<p class="privacy-note">${t('browser')}</p>`;document.querySelector('#results').innerHTML=html;document.querySelector('#results').scrollIntoView({behavior:'smooth',block:'start'});
  }catch(e){console.error(e);showError(errorMessage(e));}
}
