// @ts-nocheck
import { test, expect } from '@playwright/test';
import { getSiteOrigin } from '../../site.config.js';

const origin=process.env.PORTAL_E2E_URL||'http://127.0.0.1:4181';
const publicOrigin=getSiteOrigin();

test.beforeEach(async({page})=>{await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());});

test('Stats landing page is public, local-first and links to the analyser',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(origin+'/stats/');expect(response.status()).toBe(200);await expect(page.locator('html')).toHaveAttribute('lang','fr');await expect(page.locator('h1')).toContainText('Les statistiques sans boîte noire');await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',publicOrigin+'/stats/');await expect(page.getByRole('link',{name:/Ouvrir l’outil/})).toHaveAttribute('href','/stats/tool/');await expect(page.locator('body')).toContainText('Aucun LLM ne choisit la méthode');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
});

test('Stats built-in demo runs exact rank sensitivity, visualization and local report export',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(origin+'/stats/tool/');expect(response.status()).toBe(200);await expect(page.locator('#analysis-mode')).toHaveValue('compare2');await page.locator('#load-demo').click();await expect(page.locator('#mapping')).toBeVisible();await expect(page.locator('#parse-status')).toContainText('Données lues');await expect(page.locator('#col-group')).toHaveValue('group');await expect(page.locator('#col-value')).toHaveValue('value');await page.locator('#run-analysis').click();await expect(page.locator('#results .result-card')).toHaveCount(2);await expect(page.locator('#results')).toContainText('Welch t');await expect(page.locator('#results')).toContainText('Mann–Whitney');await expect(page.locator('#results .rank-inference span')).toHaveText('Inférence');await expect(page.locator('#results .rank-inference strong')).toHaveText('Exacte');expect(await page.locator('#results .metric').count()).toBeGreaterThan(0);await expect(page.locator('#results .assumptions')).toBeVisible();await expect(page.locator('#results .privacy-note')).toContainText('Aucune donnée n’est envoyée à un serveur');await expect(page.locator('#results .stats-visual-section')).toBeVisible();await expect(page.locator('#results .stats-svg')).toBeVisible();await expect(page.locator('#results .diagnostic-section')).toBeVisible();await expect(page.locator('#results .qq-chart')).toBeVisible();await expect(page.locator('#results .stats-report-actions')).toBeVisible();const downloadPromise=page.waitForEvent('download');await page.locator('[data-report-download]').click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('stats-report.html');await page.locator('#data-input').fill('group,value\nA,1\nA,2\nA,2\nB,3\nB,4\nB,5');await page.locator('#parse-data').click();await page.locator('#run-analysis').click();await expect(page.locator('#results .rank-inference strong')).toHaveText('Asymptotique');expect(errors).toEqual([]);
});

test('Stats deterministic assistant routes repeated designs to Friedman rather than independent ANOVA',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await expect(page.locator('#decision-launch')).toBeVisible();await page.locator('#decision-launch').click();await expect(page.locator('#decision-recommendation')).toContainText('Welch t');await page.locator('#decision-paired').selectOption('yes');await expect(page.locator('#decision-recommendation')).toContainText('t apparié');await page.locator('#decision-groups').selectOption('k');await expect(page.locator('#decision-recommendation')).toContainText('Friedman');await expect(page.locator('#decision-recommendation')).toContainText('Wilcoxon appariés');await page.locator('#decision-apply').click();await expect(page.locator('#analysis-mode')).toHaveValue('repeatedk');expect(errors).toEqual([]);
});

test('Stats deterministic assistant routes binary modeling to logistic regression',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#decision-launch').click();await page.locator('#decision-outcome').selectOption('categorical');await page.locator('#decision-cat-goal').selectOption('model');await expect(page.locator('#decision-recommendation')).toContainText('Régression logistique binaire');await page.locator('#decision-apply').click();await expect(page.locator('#analysis-mode')).toHaveValue('logistic');await expect(page.locator('#method-guide')).toContainText('odds');expect(errors).toEqual([]);
});

test('Stats runs Friedman with Kendall W and corrected paired post-hoc comparisons',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('repeatedk');await page.locator('#load-demo').click();await expect(page.locator('#col-subject')).toHaveValue('subject');await expect(page.locator('#col-condition')).toHaveValue('condition');await expect(page.locator('#col-value')).toHaveValue('value');await page.locator('#run-analysis').click();await expect(page.locator('#results .result-card')).toHaveCount(1);await expect(page.locator('#results .result-card')).toContainText('Friedman');await expect(page.locator('#results .result-card')).toContainText('Kendall W');await expect(page.locator('#results .result-card')).toContainText('8');await expect(page.locator('#results .repeated-posthoc')).toBeVisible();await expect(page.locator('#results .repeated-posthoc h3')).toHaveText('Post-hoc appariés corrigés');await expect(page.locator('#results .repeated-posthoc tbody tr')).toHaveCount(3);await expect(page.locator('#results .repeated-posthoc')).toContainText('p Holm');await expect(page.locator('#results .repeated-posthoc')).toContainText('Exacte');expect(errors).toEqual([]);
});

test('Stats reports corrected pairwise post-hoc comparisons after a multi-group analysis',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('comparek');await page.locator('#load-demo').click();await page.locator('#run-analysis').click();await expect(page.locator('#results .posthoc-section')).toBeVisible();await expect(page.locator('#results .posthoc-section h3')).toHaveText('Comparaisons post-hoc corrigées');await expect(page.locator('#results .posthoc-table tbody tr')).toHaveCount(3);await expect(page.locator('#results .posthoc-section')).toContainText('p Holm');await expect(page.locator('#results .posthoc-section')).toContainText('A − B');expect(errors).toEqual([]);
});

test('Stats exposes explicit 2x2 orientation and RD, RR, OR with confidence intervals',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('categorical');await page.locator('#load-demo').click();await expect(page.locator('#effect-orientation')).toBeVisible();await expect(page.locator('#effect-group1')).toHaveValue('A');await expect(page.locator('#effect-event')).toHaveValue('yes');await page.locator('#run-analysis').click();await expect(page.locator('#results .categorical-effects')).toBeVisible();await expect(page.locator('#results .effect-card')).toHaveCount(3);await expect(page.locator('#results .categorical-effects')).toContainText('Différence de risque (RD)');await expect(page.locator('#results .categorical-effects')).toContainText('Risque relatif (RR)');await expect(page.locator('#results .categorical-effects')).toContainText('Odds ratio (OR)');await expect(page.locator('#results .categorical-effects')).toContainText('A vs B');expect(errors).toEqual([]);
});

test('Stats linear association adds Q-Q and residual-vs-fitted diagnostics',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('association');await page.locator('#load-demo').click();await page.locator('#run-analysis').click();await expect(page.locator('#results .diagnostic-section')).toBeVisible();await expect(page.locator('#results .qq-chart')).toBeVisible();await expect(page.locator('#results .residual-chart')).toBeVisible();await expect(page.locator('#results .diagnostic-section')).toContainText('pas un test de décision');expect(errors).toEqual([]);
});

test('Stats logistic regression uses explicit event coding and reports OR with likelihood information',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('logistic');await page.locator('#load-demo').click();await expect(page.locator('#col-x')).toHaveValue('x');await expect(page.locator('#col-y')).toHaveValue('outcome');await expect(page.locator('#logistic-event-wrap')).toBeVisible();await page.locator('#logistic-event').selectOption('yes');await page.locator('#run-analysis').click();const card=page.locator('#results .result-card');await expect(card).toHaveCount(1);await expect(card).toContainText('Régression logistique');await expect(card).toContainText('3.675');await expect(card).toContainText('0.708');await expect(card).toContainText('19.069');await expect(card).toContainText('0.0029');await expect(card).toContainText('McFadden R²');await expect(card).toContainText('Y=1: yes');await expect(card).toContainText('Y=0: no');await expect(card).toContainText('Convergence');await page.locator('#logistic-event').selectOption('no');await page.locator('#run-analysis').click();await expect(page.locator('#results .result-card')).toContainText('0.272');await expect(page.locator('#results .result-card')).toContainText('Y=1: no');expect(errors).toEqual([]);
});

test('Stats logistic regression surfaces likely complete separation instead of hiding instability',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('logistic');await page.locator('#data-input').fill('x,outcome\n1,no\n2,no\n3,no\n4,no\n5,no\n6,yes\n7,yes\n8,yes\n9,yes\n10,yes');await page.locator('#parse-data').click();await page.locator('#logistic-event').selectOption('yes');await page.locator('#run-analysis').click();await expect(page.locator('#results .result-warning')).toContainText('Alerte de stabilité');await expect(page.locator('#results .result-warning')).toContainText('séparation');expect(errors).toEqual([]);
});

test('Stats multivariable linear regression reports adjusted coefficients, VIF and influence diagnostics',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('multivariable');await page.locator('#load-demo').click();await expect(page.locator('#col-y')).toHaveValue('outcome');await expect(page.locator('#multivariable-predictors-wrap')).toBeVisible();await expect(page.locator('input[name="multivariable-predictor"]:checked')).toHaveCount(2);await page.locator('#run-analysis').click();const result=page.locator('#results .multivariable-result');await expect(result).toBeVisible();await expect(result).toContainText('Régression linéaire multivariable');await expect(result).toContainText('0.249');await expect(result).toContainText('0.758');await expect(result).toContainText('0.992');await expect(result).toContainText('2.690');await expect(page.locator('#results .multivariable-coefficients tbody tr')).toHaveCount(3);await expect(page.locator('#results .multivariable-diagnostics')).toContainText('Cook max');await expect(page.locator('#results .influence-table')).toBeVisible();await expect(page.locator('#results .influence-table tbody tr').first()).toContainText('2');expect(errors).toEqual([]);
});

test('Stats multivariable regression rejects exact collinearity instead of returning unstable coefficients',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('multivariable');await page.locator('#data-input').fill('x1,x2,outcome\n1,2,4\n2,4,5\n3,6,7\n4,8,8\n5,10,10\n6,12,11\n7,14,13\n8,16,14');await page.locator('#parse-data').click();await expect(page.locator('input[name="multivariable-predictor"]:checked')).toHaveCount(2);await page.locator('#run-analysis').click();await expect(page.locator('#results .result-error')).toContainText('colinéaires');expect(errors).toEqual([]);
});

test('Stats assistant routes adjusted quantitative questions to multivariable regression',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#decision-launch').click();await page.locator('#decision-goal').selectOption('model');await expect(page.locator('#decision-recommendation')).toContainText('Régression linéaire multivariable');await page.locator('#decision-apply').click();await expect(page.locator('#analysis-mode')).toHaveValue('multivariable');expect(errors).toEqual([]);
});

test('Stats survival workflow adds Kaplan-Meier summaries, risk table and oriented Cox HR',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('survival');await page.locator('#load-demo').click();await expect(page.locator('#survival-cox-orientation')).toBeVisible();await expect(page.locator('#cox-group1')).toHaveValue('A');await page.locator('#run-analysis').click();await expect(page.locator('#results .survival-summary')).toBeVisible();await expect(page.locator('#results .survival-summary-card')).toHaveCount(2);await expect(page.locator('#results .survival-summary')).toContainText('Médiane de survie');await expect(page.locator('#results .survival-risk-table tbody tr')).toHaveCount(4);const cox=page.locator('#results .cox-section');await expect(cox).toBeVisible();await expect(cox).toContainText('Cox PH · A vs B');await expect(cox).toContainText('1.802');await expect(cox).toContainText('0.398');await expect(cox).toContainText('8.163');await expect(cox).toContainText('0.4446');await expect(cox).toContainText('0.4414');await page.locator('#cox-group1').selectOption('B');await expect(page.locator('#results .cox-section')).toContainText('Cox PH · B vs A');await expect(page.locator('#results .cox-section')).toContainText('0.555');expect(errors).toEqual([]);
});

test('Stats Cox panel warns when one survival group has no events',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await page.locator('#analysis-mode').selectOption('survival');await page.locator('#data-input').fill(`group,time,event
A,1,1
A,2,1
A,3,1
A,4,1
B,5,0
B,6,0
B,7,0
B,8,0`);await page.locator('#parse-data').click();await page.locator('#run-analysis').click();await expect(page.locator('#results .cox-warning')).toContainText('Estimation instable');await expect(page.locator('#results .cox-warning')).toContainText('HR de Cox standard');expect(errors).toEqual([]);
});

test('Stats study planning computes sample size and dropout inflation',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/stats/tool/');await expect(page.locator('#study-planning')).toBeVisible();await expect(page.locator('#plan-design')).toHaveValue('two_means');await page.locator('#plan-run').click();await expect(page.locator('#plan-result strong')).toContainText('70 par groupe');await expect(page.locator('#plan-result strong')).toContainText('140 au total');await expect(page.locator('#plan-result small')).toContainText('63 par groupe');await page.locator('#plan-design').selectOption('paired_means');await page.locator('#plan-run').click();await expect(page.locator('#plan-result strong')).toContainText('36 participants au total');await expect(page.locator('#plan-result small')).toContainText('32');expect(errors).toEqual([]);
});

test('Stats remains usable on mobile and the bilingual switch updates the interface',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto(origin+'/stats/tool/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('[data-lang-toggle]').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('h1')).toContainText('Which test for your data?');await expect(page.locator('#load-demo')).toHaveText('Load demo');await expect(page.locator('#decision-launch')).toContainText('I do not know which test to choose');await expect(page.locator('#study-planning h2')).toHaveText('Plan a study');await expect(page.locator('#plan-run')).toHaveText('Calculate sample size');
});
