import { l, activity as a, numeric as n, select as s, reflect as r } from '../../learning/activityContent.js';
const pk = ['rowland-tozer', 'holford-clearance'];
export const coreActivities = [
  a('pourquoi-pharmacometrie', l('Même dose, deux expositions', 'Same dose, two exposures'), l('Distinguer dose, exposition et réponse.', 'Distinguish dose, exposure and response.'), l('Bolus IV fictif de 100 mg, PK linéaire. CL(A) = 5 et CL(B) = 10 L/h. AUC = Dose/CL.', 'Fictional 100 mg IV bolus, linear PK. CL(A) = 5 and CL(B) = 10 L/h. AUC = Dose/CL.'), pk, [
    n('auc', l('Calculez AUC(A).', 'Calculate AUC(A).'), 20, 'mg.h/L', l('100/5 = 20 mg.h/L. La dose seule ne définit pas l’exposition.', '100/5 = 20 mg.h/L. Dose alone does not define exposure.'), { units: ['mg.h/L', 'mg/L', 'mg'], hints: [l('Divisez la dose par la clairance.', 'Divide dose by clearance.')] }),
    n('ratio', l('Quel est le ratio AUC(B)/AUC(A) ?', 'What is AUC(B)/AUC(A)?'), 0.5, '', l('AUC(B) = 10 ; le ratio vaut 0,5.', 'AUC(B) = 10; the ratio is 0.5.')),
    r('response', l('B a-t-il nécessairement deux fois moins d’effet ?', 'Must B have half the effect?'), [l('Séparer PK et PD.', 'Separate PK and PD.'), l('Examiner forme de la relation et délai.', 'Examine the relationship shape and delay.')], l('Non : une réponse saturable ou retardée ne suit pas proportionnellement l’AUC. Un modèle PD et son domaine sont nécessaires.', 'No: a saturable or delayed response need not scale with AUC. A PD model and its domain are needed.'))
  ]),
  a('trois-approches', l('Choisir une approche selon la question', 'Choose an approach for the question'), l('Relier objectif, données et hypothèses.', 'Connect objectives, data and assumptions.'), l('Une étude a des profils IV riches ; une autre des prélèvements rares par patient ; une troisième vise une extrapolation physiologique.', 'One study has rich IV profiles, another sparse samples per patient, and a third seeks physiological extrapolation.'), ['yamaoka-moments', 'mould-upton', 'jones-rowland-yeo'], [
    n('nca', l('Profil riche : dose 80 mg, AUC 16 mg.h/L. Calculez CL.', 'Rich profile: dose 80 mg, AUC 16 mg.h/L. Calculate CL.'), 5, 'L/h', l('CL = 80/16 = 5 L/h pour cette administration IV.', 'CL = 80/16 = 5 L/h for this IV administration.')),
    s('choice', l('Quelles propositions sont défendables ?', 'Which statements are defensible?'), [l('La NCA dépend de la qualité de l’échantillonnage.', 'NCA depends on sampling quality.'), l('La PopPK peut partager l’information entre patients.', 'PopPK can share information across patients.'), l('La PBPK garantit toute extrapolation.', 'PBPK guarantees any extrapolation.')], [0, 1], l('Une structure mécaniste n’élimine pas les hypothèses ni le besoin d’évaluation.', 'A mechanistic structure does not remove assumptions or evaluation needs.')),
    r('design', l('Que demander avant de choisir la PBPK ?', 'What would you ask before choosing PBPK?'), [l('Définir population et question extrapolées.', 'Define the target population and question.'), l('Vérifier données physiologiques, paramètres et évaluation.', 'Check physiological data, parameters and evaluation.')], l('Le choix dépend de la question et des informations disponibles, pas du nombre de compartiments.', 'The choice depends on the question and available information, not compartment count.'))
  ]),
  a('micro-macro', l('Reconstruire les constantes de transfert', 'Reconstruct transfer rates'), l('Vérifier unités et conservation des flux.', 'Check units and flux conservation.'), l('Deux compartiments : CL = 4, Q = 6 L/h ; V1 = 20, V2 = 60 L. k12 = Q/V1, k21 = Q/V2.', 'Two compartments: CL = 4, Q = 6 L/h; V1 = 20, V2 = 60 L. k12 = Q/V1, k21 = Q/V2.'), ['gibaldi-perrier'], [
    n('forward', l('Calculez k12.', 'Calculate k12.'), 0.3, '1/h', l('6/20 = 0,3 par heure.', '6/20 = 0.3 per hour.'), { units: ['1/h', 'L/h', 'h'] }),
    n('backward', l('Calculez k21.', 'Calculate k21.'), 0.1, '1/h', l('6/60 = 0,1 par heure : même Q, constantes différentes.', '6/60 = 0.1 per hour: same Q, different rate constants.')),
    r('balance', l('À C1 = C2, le transfert net est-il nul malgré k12 différent de k21 ?', 'At C1 = C2, is net transfer zero even though k12 differs from k21?'), [l('Utiliser les quantités Ai = Vi Ci.', 'Use amounts Ai = Vi Ci.'), l('Comparer Q C1 et Q C2.', 'Compare Q C1 and Q C2.')], l('Oui : k12 A1 = Q C1 et k21 A2 = Q C2. Égaler les quantités ne serait pas équivalent.', 'Yes: k12 A1 = Q C1 and k21 A2 = Q C2. Equal amounts would not be equivalent.'))
  ]),
  a('clairance-volume-demi-vie', l('Séparer volume et clairance sur un profil', 'Separate volume and clearance in a profile'), l('Prédire puis manipuler un bolus IV.', 'Predict then manipulate an IV bolus.'), l('Bolus de 100 mg, V = 20 L, CL = 5 L/h, un compartiment, sans erreur.', '100 mg bolus, V = 20 L, CL = 5 L/h, one compartment, no error.'), pk, [
    n('initial', l('Calculez C(0+).', 'Calculate C(0+).'), 5, 'mg/L', l('C(0+) = 100/20 = 5 mg/L.', 'C(0+) = 100/20 = 5 mg/L.')),
    { id: 'change', type: 'tune', prompt: l('Doublez C(0+) en ne modifiant que V ; gardez CL = 5.', 'Double C(0+) by changing only V; keep CL = 5.'), experiment: { kind: 'bolus', controls: ['cl', 'v'] }, targets: { v: 10, cl: 5 }, correction: l('V = 10 L double C(0+), mais augmente aussi CL/V : la pente change.', 'V = 10 L doubles C(0+), but also increases CL/V: the slope changes.') },
    n('half', l('Après ce changement, calculez la demi-vie.', 'After this change, calculate half-life.'), Math.log(2) * 2, 'h', l('ln(2) × 10/5 = 1,386 h. AUC = Dose/CL reste inchangée.', 'ln(2) × 10/5 = 1.386 h. AUC = Dose/CL remains unchanged.'))
  ]),
  a('absorption-orale', l('Identifier un flip-flop', 'Identify flip-flop kinetics'), l('Ne pas confondre absorption et élimination terminale.', 'Do not confuse absorption with terminal elimination.'), l('Dose orale 100 mg, F = 1, V = 20 L, CL = 5 L/h. Ka peut passer de 1 à 0,1 par heure.', 'Oral dose 100 mg, F = 1, V = 20 L, CL = 5 L/h. Ka can change from 1 to 0.1 per hour.'), ['savic-transit', 'gibaldi-perrier'], [
    n('ke', l('Calculez ke.', 'Calculate ke.'), 0.25, '1/h', l('ke = CL/V = 0,25 par heure.', 'ke = CL/V = 0.25 per hour.')),
    { id: 'slow', type: 'tune', prompt: l('Placez Ka à 0,1 par heure et comparez les profils.', 'Set Ka to 0.1 per hour and compare profiles.'), experiment: { kind: 'oral', controls: ['ka'] }, targets: { ka: 0.1 }, correction: l('Ka devient inférieur à ke ; la phase terminale est alors limitée par l’absorption dans ce modèle.', 'Ka becomes smaller than ke; the terminal phase is now absorption-limited in this model.') },
    r('auc', l('Une absorption plus lente impose-t-elle une AUC plus faible ?', 'Does slower absorption imply a lower AUC?'), [l('Préciser F et CL fixés.', 'State that F and CL are fixed.'), l('Distinguer AUC complète et fenêtre limitée.', 'Distinguish complete AUC from a limited window.')], l('AUC(0,infini) = F Dose/CL reste 20 mg.h/L ici. Cmax, Tmax et une AUC tronquée peuvent changer.', 'AUC(0,infinity) = F Dose/CL remains 20 mg.h/L here. Cmax, Tmax and truncated AUC may change.'))
  ]),
  a('doses-repetees', l('Exposition moyenne et accumulation', 'Average exposure and accumulation'), l('Relier intervalle, plateau et demi-vie.', 'Connect interval, steady state and half-life.'), l('Bolus IV répétés de 100 mg toutes les 8 h. CL = 5 L/h, V = 20 L ; paramètres constants.', 'Repeated 100 mg IV boluses every 8 h. CL = 5 L/h, V = 20 L; constant parameters.'), pk, [
    n('average', l('Calculez la concentration moyenne à l’équilibre.', 'Calculate average steady-state concentration.'), 2.5, 'mg/L', l('Dose/(CL × intervalle) = 100/40 = 2,5.', 'Dose/(CL × interval) = 100/40 = 2.5.')),
    n('factor', l('Calculez le facteur d’accumulation 1/(1 − exp(−CL/V × 8)).', 'Calculate the accumulation factor 1/(1 − exp(−CL/V × 8)).'), 1 / (1 - Math.exp(-2)), '', l('Le facteur vaut environ 1,157 pour les pics immédiatement après bolus.', 'The factor is about 1.157 for immediate post-bolus peaks.')),
    r('schedule', l('50 mg toutes les 4 h donne-t-il le même profil ?', 'Does 50 mg every 4 h give the same profile?'), [l('Comparer le débit moyen de dose.', 'Compare average dose rates.'), l('Distinguer moyenne et fluctuations.', 'Distinguish average and fluctuations.')], l('La moyenne reste identique sous PK linéaire, mais les fluctuations diminuent. Cela ne suffit pas à une recommandation clinique.', 'The average remains the same under linear PK, but fluctuations decrease. This alone is not a clinical recommendation.'))
  ]),
  a('perfusion', l('Du débit au plateau', 'From rate to plateau'), l('Séparer durée de perfusion et élimination.', 'Separate infusion duration from elimination.'), l('Perfusion unique de 100 mg sur 2 h. CL = 5 L/h, V = 20 L, concentration initiale nulle.', 'Single 100 mg infusion over 2 h. CL = 5 L/h, V = 20 L, zero initial concentration.'), pk, [
    n('rate', l('Calculez R0.', 'Calculate R0.'), 50, 'mg/h', l('R0 = 100/2 = 50 mg/h.', 'R0 = 100/2 = 50 mg/h.')),
    n('end', l('Calculez C(2) = R0/CL × (1 − exp(−CL/V × 2)).', 'Calculate C(2) = R0/CL × (1 − exp(−CL/V × 2)).'), 10 * (1 - Math.exp(-0.5)), 'mg/L', l('C(2) = 3,935 mg/L : le plateau théorique de 10 mg/L n’a pas été atteint.', 'C(2) = 3.935 mg/L: the theoretical 10 mg/L plateau was not reached.'), { experiment: { kind: 'infusion', controls: ['duration'] } }),
    r('extend', l('Si la même dose est donnée sur 4 h, qu’advient-il du débit et de l’AUC complète ?', 'If the same dose is given over 4 h, what happens to rate and complete AUC?'), [l('Diviser le débit par deux.', 'Halve the rate.'), l('Garder Dose/CL pour l’AUC complète.', 'Keep Dose/CL for complete AUC.')], l('R0 devient 25 mg/h ; AUC reste 20 mg.h/L sous ces hypothèses linéaires. Le pic diminue.', 'R0 becomes 25 mg/h; AUC remains 20 mg.h/L under these linear assumptions. The peak decreases.'))
  ]),
  a('erreur-residuelle', l('Écart-type ou variance ?', 'Standard deviation or variance?'), l('Calculer une erreur combinée indépendante.', 'Calculate independent combined error.'), l('Y = C + epsilon_add + C × epsilon_prop ; erreurs indépendantes de SD 1 mg/L et 0,2.', 'Y = C + epsilon_add + C × epsilon_prop; independent errors with SD 1 mg/L and 0.2.'), ['berrah-residual', 'davidian-giltinan'], [
    n('sd', l('Pour C = 10 mg/L, calculez SD(Y|C).', 'For C = 10 mg/L, calculate SD(Y|C).'), Math.sqrt(5), 'mg/L', l('Les variances s’additionnent : sqrt(1² + (0,2 × 10)²) = 2,236.', 'Variances add: sqrt(1² + (0.2 × 10)²) = 2.236.'), { hints: [l('N’additionnez pas directement les écarts-types.', 'Do not add standard deviations directly.')] }),
    { id: 'prop', type: 'tune', prompt: l('Obtenez une erreur purement proportionnelle de SDprop = 0,2.', 'Obtain purely proportional error with SDprop = 0.2.'), experiment: { kind: 'error', controls: ['additive', 'proportional'] }, targets: { additive: 0, proportional: 0.2 }, correction: l('SDadd = 0 ; l’incertitude absolue tend vers zéro lorsque C tend vers zéro dans ce modèle.', 'SDadd = 0; absolute uncertainty approaches zero as C approaches zero in this model.') },
    r('low', l('Pourquoi examiner particulièrement les faibles concentrations ?', 'Why examine low concentrations in particular?'), [l('Comparer bruit absolu et relatif.', 'Compare absolute and relative noise.'), l('Examiner limite de quantification et censure.', 'Examine quantification limit and censoring.')], l('Une erreur proportionnelle seule peut sous-décrire le bruit absolu près de zéro. Les BLQ ne sont pas des zéros mesurés.', 'Proportional error alone may underdescribe absolute noise near zero. BLQ values are not measured zeros.'))
  ]),
  a('voies-absorption', l('Estimer F avec une référence IV', 'Estimate F with an IV reference'), l('Normaliser par la dose avant comparaison.', 'Dose-normalize before comparing.'), l('Même population, PK linéaire : oral 200 mg, AUC 24 ; IV 100 mg, AUC 20 mg.h/L.', 'Same population, linear PK: oral 200 mg, AUC 24; IV 100 mg, AUC 20 mg.h/L.'), ['rowland-tozer'], [
    n('f', l('Calculez F absolue.', 'Calculate absolute F.'), 0.6, '', l('F = (24/200)/(20/100) = 0,6.', 'F = (24/200)/(20/100) = 0.6.')),
    n('apparent', l('Sans les données IV, quel CL/F déduirait-on ?', 'Without IV data, what CL/F would be inferred?'), 200 / 24, 'L/h', l('Dose orale/AUC = 8,333 L/h, et non CL = 5 L/h.', 'Oral dose/AUC = 8.333 L/h, not CL = 5 L/h.')),
    r('change', l('Une hausse de CL/F après changement de formulation prouve-t-elle une hausse de CL ?', 'Does increased CL/F after a formulation change prove increased CL?'), [l('Considérer une variation de F.', 'Consider a change in F.'), l('Demander comparaison, observance et conditions d’administration.', 'Examine comparability, adherence and administration conditions.')], l('Non : une baisse de F suffit. Les données orales seules ne séparent généralement pas ces deux paramètres.', 'No: a decrease in F is sufficient. Oral data alone generally cannot separate these parameters.'))
  ]),
  a('parent-metabolite', l('Suivre le flux de formation', 'Track the formation flux'), l('Distinguer disparition du parent et apparition du métabolite.', 'Distinguish parent loss from metabolite formation.'), l('Quantités molaires : parent 100 micromol ; kformation = 0,1/h, kautre = 0,2/h. Rendement de formation = 1.', 'Molar amounts: parent 100 micromol; kformation = 0.1/h, kother = 0.2/h. Formation yield = 1.'), ['houston-metabolite', 'gibaldi-perrier'], [
    n('loss', l('Quel est le flux total de disparition du parent ?', 'What is total parent loss flux?'), 30, 'micromol/h', l('(0,1 + 0,2) × 100 = 30.', '(0.1 + 0.2) × 100 = 30.')),
    n('formation', l('Quel flux entre dans le compartiment métabolite ?', 'What flux enters the metabolite compartment?'), 10, 'micromol/h', l('Seule la voie de formation contribue : 0,1 × 100 = 10.', 'Only the formation pathway contributes: 0.1 × 100 = 10.')),
    r('terminal', l('Une longue demi-vie terminale du métabolite révèle-t-elle toujours sa propre élimination ?', 'Does a long metabolite terminal half-life always reveal its own elimination?'), [l('Envisager une cinétique limitée par la formation.', 'Consider formation-limited kinetics.'), l('Vérifier unités molaires et rendement.', 'Check molar units and yield.')], l('Non : la formation lente depuis le parent peut gouverner la pente terminale. Un bilan en masse nécessite aussi les masses molaires.', 'No: slow formation from the parent can govern the terminal slope. A mass-based balance also needs molecular weights.'))
  ]),
  a('variabilite-iiv-iov', l('Changer d’occasion, pas de patient', 'Change occasion, not patient'), l('Décomposer les effets aléatoires.', 'Decompose random effects.'), l('CLij = 5 exp(ETAi + KAPPAij). ETAi = 0,2 ; KAPPAi1 = −0,1 et KAPPAi2 = 0,1.', 'CLij = 5 exp(ETAi + KAPPAij). ETAi = 0.2; KAPPAi1 = −0.1 and KAPPAi2 = 0.1.'), ['karlsson-sheiner-iov'], [
    n('first', l('Calculez CL à la première occasion.', 'Calculate CL at the first occasion.'), 5 * Math.exp(0.1), 'L/h', l('5 exp(0,2 − 0,1) = 5,526.', '5 exp(0.2 − 0.1) = 5.526.')),
    n('ratio', l('Calculez CLi2/CLi1.', 'Calculate CLi2/CLi1.'), Math.exp(0.2), '', l('ETA commun s’annule : exp(0,1 − (−0,1)) = 1,221.', 'The shared ETA cancels: exp(0.1 − (−0.1)) = 1.221.')),
    r('sampling', l('Pourquoi ne pas tirer un nouvel ETA à chaque prélèvement ?', 'Why not draw a new ETA at every sample?'), [l('ETA est commun au patient.', 'ETA is shared within the patient.'), l('Séparer occasion et erreur de mesure.', 'Separate occasion and measurement error.')], l('Un nouveau tirage par ligne détruirait les corrélations intra-patient. Les observations partagent ETA, et KAPPA au sein d’une occasion.', 'A new draw per row would destroy within-patient correlations. Observations share ETA and, within an occasion, KAPPA.'))
  ]),
  a('allometrie', l('Normaliser sans extrapoler silencieusement', 'Normalize without silent extrapolation'), l('Distinguer exposants de CL et V.', 'Distinguish CL and V exponents.'), l('Illustration : CL = 4 (WT/70)^0,75 L/h ; V = 30 WT/70 L. Données disponibles entre 40 et 90 kg.', 'Illustration: CL = 4 (WT/70)^0.75 L/h; V = 30 WT/70 L. Available data span 40 to 90 kg.'), ['anderson-holford-allometry'], [
    n('cl', l('Calculez CL à 50 kg.', 'Calculate CL at 50 kg.'), 4 * (50 / 70) ** 0.75, 'L/h', l('CL = 3,108 L/h.', 'CL = 3.108 L/h.'), { visual: { lesson: 'basics', value: 50 } }),
    n('v', l('Calculez V à 50 kg.', 'Calculate V at 50 kg.'), 30 * 50 / 70, 'L', l('V = 21,429 L ; son exposant est 1.', 'V = 21.429 L; its exponent is 1.')),
    r('range', l('Le calcul à 20 kg est possible. Que faut-il préciser ?', 'Calculation at 20 kg is possible. What must be stated?'), [l('Signaler la sortie du domaine 40–90 kg.', 'Flag departure from the 40–90 kg domain.'), l('Examiner maturation, population et validation.', 'Examine maturation, population and validation.')], l('Un calcul hors plage n’est pas une validation. Une allométrie de taille ne remplace pas un modèle de maturation.', 'A calculation outside the range is not validation. Size allometry does not replace a maturation model.'))
  ]),
  a('pkpd', l('De la concentration à une réponse saturable', 'From concentration to saturable response'), l('Lire Emax sans attribuer un mécanisme non démontré.', 'Read Emax without claiming an unproven mechanism.'), l('E = 100 C/(2 + C), effet initial nul, C en mg/L. Modèle phénoménologique.', 'E = 100 C/(2 + C), zero baseline effect, C in mg/L. Phenomenological model.'), ['goutelle-hill', 'holford-sheiner-dose-effect'], [
    n('half', l('Calculez E à C = 2.', 'Calculate E at C = 2.'), 50, '', l('À EC50, l’effet incrémental est la moitié d’Emax.', 'At EC50, incremental effect is half of Emax.')),
    n('five', l('Calculez E à C = 10, soit 5 EC50.', 'Calculate E at C = 10, or 5 EC50.'), 100 * 5 / 6, '', l('5/6 = 83,33 % d’Emax, pas 100 %.', '5/6 = 83.33% of Emax, not 100%.'), { experiment: { kind: 'emax', controls: ['ec50', 'hill'] } }),
    r('delay', l('Un effet maximal après le pic de concentration invalide-t-il nécessairement la PK ?', 'Does maximal effect after peak concentration necessarily invalidate PK?'), [l('Envisager délai de distribution ou de turnover.', 'Consider distribution or turnover delay.'), l('Examiner données PK et PD séparément.', 'Examine PK and PD data separately.')], l('Non : un compartiment d’effet ou une réponse indirecte peut expliquer un délai. La sélection doit être étayée par les données.', 'No: an effect compartment or indirect response may explain a delay. Selection must be supported by data.'))
  ]),
  a('parametric-vs-nonparametric', l('Une distribution ne se résume pas à sa moyenne', 'A distribution is more than its mean'), l('Manipuler des supports pondérés.', 'Work with weighted support points.'), l('CL = 2, 5 et 10 L/h avec poids 0,2 ; 0,5 ; 0,3. Dose IV = 100 mg.', 'CL = 2, 5 and 10 L/h with weights 0.2, 0.5 and 0.3. IV dose = 100 mg.'), ['goutelle-parametric-nonparametric', 'neely-pmetrics'], [
    n('mean', l('Calculez la CL moyenne pondérée.', 'Calculate weighted mean CL.'), 5.9, 'L/h', l('0,2 × 2 + 0,5 × 5 + 0,3 × 10 = 5,9.', '0.2 × 2 + 0.5 × 5 + 0.3 × 10 = 5.9.')),
    n('auc', l('Calculez la moyenne pondérée des AUC individuelles.', 'Calculate the weighted average of individual AUCs.'), 23, 'mg.h/L', l('0,2 × 50 + 0,5 × 20 + 0,3 × 10 = 23 ; ce n’est pas 100/5,9.', '0.2 × 50 + 0.5 × 20 + 0.3 × 10 = 23; this is not 100/5.9.')),
    r('shape', l('Peut-on remplacer ce prior par une seule CL moyenne pour prédire une PTA ?', 'Can this prior be replaced by one mean CL to predict PTA?'), [l('La PTA dépend de la distribution des expositions.', 'PTA depends on the exposure distribution.'), l('Les transformations non linéaires ne commutent pas avec la moyenne.', 'Nonlinear transformations do not commute with averaging.')], l('Non en général. Conserver les points et leurs poids permet de calculer les probabilités sans perdre cette hétérogénéité.', 'Generally no. Retaining points and weights enables probability calculations without losing this heterogeneity.'))
  ]),
  a('pmetrics-nonparametric', l('Mettre à jour les poids du prior', 'Update prior weights'), l('Relier supports, vraisemblance et posterior.', 'Connect support points, likelihood and posterior.'), l('Deux supports : CL = 2 et 8 L/h ; prior = (0,5 ; 0,5). Vraisemblance de la mesure : (0,2 ; 0,8).', 'Two supports: CL = 2 and 8 L/h; prior = (0.5, 0.5). Measurement likelihood: (0.2, 0.8).'), ['pmetrics', 'neely-pmetrics'], [
    n('weight', l('Calculez le poids posterior du premier support.', 'Calculate posterior weight of the first support.'), 0.2, '', l('0,5 × 0,2 / (0,5 × 0,2 + 0,5 × 0,8) = 0,2.', '0.5 × 0.2 / (0.5 × 0.2 + 0.5 × 0.8) = 0.2.')),
    n('mean', l('Calculez la CL moyenne posterior.', 'Calculate posterior mean CL.'), 6.8, 'L/h', l('0,2 × 2 + 0,8 × 8 = 6,8. Le support le plus probable est 8, pas 6,8.', '0.2 × 2 + 0.8 × 8 = 6.8. The most probable support is 8, not 6.8.')),
    r('artifact', l('Quelles informations faut-il conserver pour reproduire la mise à jour ?', 'What must be retained to reproduce the update?'), [l('Structure, paramètres des supports et poids.', 'Structure, support parameters and weights.'), l('Modèle d’erreur, unités et historique d’administration.', 'Error model, units and dosing history.')], l('Le code structural seul ne suffit pas. Cet exercice discret illustre Bayes ; il n’exécute pas PM_model$map() ni NPAG.', 'Structural code alone is insufficient. This discrete exercise illustrates Bayes; it does not execute PM_model$map() or NPAG.'))
  ]),
  a('outils-estimation', l('Un minimum numérique ne suffit pas', 'A numerical minimum is not enough'), l('Comparer ajustement et complexité.', 'Compare fit and complexity.'), l('Même vraisemblance et mêmes données : modèle A, OFV = 120, k = 4 ; B, OFV = 116, k = 7. AIC = OFV + 2k, constantes identiques.', 'Same likelihood and data: model A, OFV = 120, k = 4; B, OFV = 116, k = 7. AIC = OFV + 2k, identical constants.'), ['akaike-aic', 'wang-nonmem-methods'], [
    n('a', l('Calculez AIC(A).', 'Calculate AIC(A).'), 128, '', l('120 + 2 × 4 = 128.', '120 + 2 × 4 = 128.')),
    n('b', l('Calculez AIC(B).', 'Calculate AIC(B).'), 130, '', l('116 + 2 × 7 = 130 : le gain d’OFV ne compense pas la pénalité.', '116 + 2 × 7 = 130: the OFV gain does not offset the penalty.')),
    r('choice', l('Choisir A dispense-t-il de vérifier la convergence ?', 'Does choosing A remove the need to check convergence?'), [l('Vérifier minimum, initialisations et précision.', 'Check minimum, initializations and precision.'), l('Examiner diagnostics et plausibilité.', 'Examine diagnostics and plausibility.')], l('Non : les critères comparent des ajustements comparables et correctement estimés ; ils ne certifient pas leur utilité.', 'No: criteria compare comparable, adequately estimated fits; they do not certify usefulness.'))
  ]),
  a('validation-vpc', l('Lire une couverture prédictive', 'Read predictive coverage'), l('Distinguer couverture et validation complète.', 'Distinguish coverage from complete validation.'), l('Une bande prédictive nominale à 90 % contient 72 des 100 observations fictives. Les observations peuvent être corrélées par patient.', 'A nominal 90% prediction band contains 72 of 100 fictional observations. Observations may be correlated within patients.'), ['karlsson-holford-vpc', 'bergstrand-pcvpc'], [
    n('coverage', l('Quelle est la couverture observée ?', 'What is observed coverage?'), 72, '%', l('72/100 × 100 = 72 %.', '72/100 × 100 = 72%.')),
    s('causes', l('Quelles explications faut-il examiner ?', 'Which explanations should be examined?'), [l('Variabilité sous-estimée.', 'Underestimated variability.'), l('Biais structural ou dessin de simulation incorrect.', 'Structural bias or incorrect simulation design.'), l('La CL est certainement deux fois trop élevée.', 'CL is certainly twice too high.')], [0, 1], l('Une couverture insuffisante ne donne pas une cause unique.', 'Insufficient coverage does not identify a unique cause.')),
    r('next', l('Proposez deux vérifications avant modification du modèle.', 'Propose two checks before changing the model.'), [l('Comparer doses, covariables et horaires simulés aux observations.', 'Compare simulated doses, covariates and times with observations.'), l('Stratifier et examiner médiane, dispersion et incertitude.', 'Stratify and examine median, spread and uncertainty.')], l('Un VPC est un diagnostic du modèle et du protocole de simulation ; la corrélation interdit de traiter naïvement toutes les lignes comme indépendantes.', 'A VPC diagnoses the model and simulation protocol; correlation prevents naively treating every row as independent.'))
  ]),
  a('bayes-ebes', l('Pondérer le prior et une mesure', 'Weight a prior and a measurement'), l('Calculer une mise à jour gaussienne pédagogique.', 'Calculate a teaching Gaussian update.'), l('Exemple scalaire, pas un ajustement PK : theta ~ N(5, 4), y = 9, variance de mesure 4. Les seconds arguments sont des variances.', 'Scalar example, not a PK fit: theta ~ N(5, 4), y = 9, measurement variance 4. Second arguments are variances.'), ['sheiner-forecasting', 'savic-karlsson-shrinkage'], [
    n('mean', l('Calculez la moyenne posterior par pondération des précisions.', 'Calculate posterior mean by precision weighting.'), 7, '', l('(5/4 + 9/4)/(1/4 + 1/4) = 7.', '(5/4 + 9/4)/(1/4 + 1/4) = 7.')),
    n('variance', l('Calculez la variance posterior.', 'Calculate posterior variance.'), 2, '', l('1/(1/4 + 1/4) = 2.', '1/(1/4 + 1/4) = 2.')),
    r('precision', l('Que se passe-t-il si la variance de mesure augmente ?', 'What happens if measurement variance increases?'), [l('La mesure reçoit moins de poids.', 'The measurement receives less weight.'), l('La moyenne se rapproche du prior.', 'The mean moves toward the prior.')], l('Moins d’information individuelle implique davantage de shrinkage dans cet exemple. Un posterior étroit ne garantit pas un prior pertinent.', 'Less individual information implies more shrinkage in this example. A narrow posterior does not guarantee a relevant prior.'))
  ]),
  a('tdm', l('Calculer sans prescrire', 'Calculate without prescribing'), l('Séparer calcul de dose et décision clinique.', 'Separate a dose calculation from a clinical decision.'), l('Patient fictif, PK linéaire stable à l’équilibre : dose journalière 400 mg, AUC24 estimée 80 mg.h/L. Cible pédagogique 100, sans indication clinique.', 'Fictional patient, stable linear steady-state PK: daily dose 400 mg, estimated AUC24 80 mg.h/L. Teaching target 100, not a clinical indication.'), ['minichmayr-mipd', 'sheiner-forecasting'], [
    n('scale', l('Calculez le facteur de dose suggéré par la proportionnalité.', 'Calculate the dose factor suggested by proportionality.'), 1.25, '', l('100/80 = 1,25 sous ces hypothèses.', '100/80 = 1.25 under these assumptions.')),
    n('dose', l('Quelle dose journalière mathématique en résulte ?', 'What mathematical daily dose results?'), 500, 'mg/day', l('400 × 1,25 = 500 mg/j ; ce n’est pas une prescription.', '400 × 1.25 = 500 mg/day; this is not a prescription.')),
    r('checks', l('Que vérifier avant toute utilisation réelle ?', 'What must be checked before real use?'), [l('Historique des prises, prélèvements, unités et transportabilité du modèle.', 'Dosing history, sample times, units and model transportability.'), l('Cible validée, toxicité, contraintes et incertitude.', 'Validated target, toxicity, constraints and uncertainty.')], l('La règle proportionnelle ne vérifie ni pertinence de la cible ni sécurité du changement ; l’intervalle et les pics peuvent aussi compter.', 'The proportional rule verifies neither target relevance nor safety; interval and peaks may also matter.'))
  ])
];
