import { l, activity as a, numeric as n, select as s, reflect as r } from '../../learning/activityContent.js';
export const domainActivities = [
  a('pbpk-intro', l('Fermer un bilan d’organe', 'Close an organ balance'), l('Convertir débits et concentrations en flux.', 'Convert flows and concentrations into fluxes.'), l('Organe bien mélangé, sans élimination : débit Q = 30 L/h, concentration entrante 2, sortante 1 mg/L ; volume 5 L.', 'Well-mixed organ, no elimination: Q = 30 L/h, inlet concentration 2, outlet 1 mg/L; volume 5 L.'), ['jones-rowland-yeo', 'kuepfer-pbpk'], [
    n('flux', l('Calculez le flux net entrant.', 'Calculate net inflow.'), 30, 'mg/h', l('Q × (Cin − Cout) = 30 × (2 − 1).', 'Q × (Cin − Cout) = 30 × (2 − 1).')),
    n('slope', l('Si le volume reste fixe, calculez dC/dt.', 'With fixed volume, calculate dC/dt.'), 6, 'mg/L/h', l('dC/dt = 30/5 = 6 mg/L/h à cet instant.', 'dC/dt = 30/5 = 6 mg/L/h at this instant.')),
    r('whole', l('Pourquoi vérifier le bilan global, pas seulement cet organe ?', 'Why check the whole-system balance, not just this organ?'), [l('Les flux internes doivent s’annuler.', 'Internal fluxes must cancel.'), l('Seules entrées et éliminations changent la quantité totale.', 'Only inputs and elimination change total amount.')], l('Un transfert compté deux fois ou un retour manquant crée ou détruit artificiellement du médicament.', 'A double-counted transfer or missing return artificially creates or destroys drug.'))
  ]),
  a('pbpk-distribution', l('Liaison et exposition libre', 'Binding and unbound exposure'), l('Éviter une conclusion automatique à partir de fu.', 'Avoid an automatic conclusion from fu.'), l('À un instant : Ctot = 10 mg/L, fu = 0,1. Exemple IV à faible extraction : CL ≈ fu × CLint ; CLint et débit de dose constants.', 'At one instant: Ctotal = 10 mg/L, fu = 0.1. Low-extraction IV example: CL ≈ fu × CLint; fixed CLint and dose rate.'), ['rodgers-rowland', 'jones-rowland-yeo'], [
    n('free', l('Calculez la concentration libre initiale.', 'Calculate initial unbound concentration.'), 1, 'mg/L', l('Cu = fu × Ctot = 1 mg/L.', 'Cu = fu × Ctotal = 1 mg/L.')),
    n('ratio', l('Dans l’approximation indiquée, si fu double, quel est le ratio des AUC libres complètes après la même dose IV ?', 'Under the stated approximation, if fu doubles, what is the ratio of complete unbound AUCs after the same IV dose?'), 1, '', l('AUCu ≈ fu × Dose/(fu × CLint) = Dose/CLint : fu s’annule.', 'AUCu ≈ fu × Dose/(fu × CLint) = Dose/CLint: fu cancels.')),
    r('limits', l('Pourquoi ne pas généraliser ce résultat à tous les médicaments ?', 'Why not generalize this result to every drug?'), [l('Préciser extraction, voie et modèle de clairance.', 'Specify extraction, route and clearance model.'), l('Distinguer changement transitoire et exposition intégrée.', 'Distinguish transient change and integrated exposure.')], l('Une modification de liaison peut changer CL et distribution. La fraction libre seule ne détermine ni exposition libre ni effet.', 'Binding changes may alter clearance and distribution. Unbound fraction alone determines neither unbound exposure nor effect.'))
  ]),
  a('pbpk-absorption', l('Décomposer la biodisponibilité', 'Decompose bioavailability'), l('Distinguer absorption et premiers passages.', 'Distinguish absorption from first-pass losses.'), l('Exemple : Fa = 0,8 ; Fg = 0,75 ; Fh = 0,5 ; F = Fa × Fg × Fh. Dose orale = 100 mg.', 'Example: Fa = 0.8; Fg = 0.75; Fh = 0.5; F = Fa × Fg × Fh. Oral dose = 100 mg.'), ['yu-amidon-acat', 'jones-rowland-yeo'], [
    n('f', l('Calculez F.', 'Calculate F.'), 0.3, '', l('0,8 × 0,75 × 0,5 = 0,30.', '0.8 × 0.75 × 0.5 = 0.30.')),
    n('amount', l('Quelle quantité de parent atteint la circulation systémique ?', 'What parent amount reaches systemic circulation?'), 30, 'mg', l('100 × 0,30 = 30 mg.', '100 × 0.30 = 30 mg.')),
    r('identification', l('Une mesure de F = 0,30 identifie-t-elle séparément Fa, Fg et Fh ?', 'Does measuring F = 0.30 identify Fa, Fg and Fh separately?'), [l('Un produit ne détermine pas ses trois facteurs.', 'A product does not determine its three factors.'), l('Demander des données supplémentaires ou des hypothèses justifiées.', 'Require additional data or justified assumptions.')], l('Non : de nombreuses combinaisons donnent le même F. Un mécanisme de faible biodisponibilité ne se déduit pas du seul ratio d’AUC.', 'No: many combinations give the same F. The mechanism of low bioavailability cannot be inferred from the AUC ratio alone.'))
  ]),
  a('pbpk-applications', l('Une interaction sur une fraction de clairance', 'An interaction on a fraction of clearance'), l('Appliquer l’inhibition uniquement à la voie concernée.', 'Apply inhibition only to the affected pathway.'), l('Modèle statique IV simplifié : fraction affectée fm = 0,6 ; activité restante de cette voie = 0,25 ; reste inchangé. CLinitiale = 10 L/h.', 'Simplified static IV model: affected fraction fm = 0.6; remaining pathway activity = 0.25; remainder unchanged. Initial CL = 10 L/h.'), ['rostami-hodjegan-ivive', 'jones-pbpk-industry'], [
    n('cl', l('Calculez CL après interaction.', 'Calculate CL after interaction.'), 5.5, 'L/h', l('10 × [(1 − 0,6) + 0,6 × 0,25] = 5,5.', '10 × [(1 − 0.6) + 0.6 × 0.25] = 5.5.')),
    n('ratio', l('À même dose IV linéaire, calculez AUCaprès/AUCavant.', 'At the same linear IV dose, calculate AUCafter/AUCbefore.'), 10 / 5.5, '', l('10/5,5 = 1,818 sous ces hypothèses.', '10/5.5 = 1.818 under these assumptions.')),
    r('extrapolate', l('Que manque-t-il pour une interaction orale dépendante du temps ?', 'What is missing for a time-dependent oral interaction?'), [l('Exposition de l’inhibiteur et dynamique enzymatique.', 'Inhibitor exposure and enzyme dynamics.'), l('Biodisponibilité, autres voies et incertitude.', 'Bioavailability, other pathways and uncertainty.')], l('Ce calcul statique n’est pas un PBPK complet. Il ne décrit ni premier passage variable ni induction/inactivation retardée.', 'This static calculation is not a full PBPK model. It describes neither changing first pass nor delayed induction/inactivation.'))
  ]),
  a('pd-direct', l('Reconstituer EC50', 'Reconstruct EC50'), l('Identifier un point de mi-effet.', 'Identify a half-effect point.'), l('E = E0 + Emax C/(EC50 + C). E0 = 10, Emax = 80. Un point typique donne E = 50 à C = 3 mg/L.', 'E = E0 + Emax C/(EC50 + C). E0 = 10, Emax = 80. A typical point gives E = 50 at C = 3 mg/L.'), ['goutelle-hill'], [
    n('increment', l('Quel effet incrémental vaut E − E0 ?', 'What is incremental effect E − E0?'), 40, '', l('50 − 10 = 40, moitié de 80.', '50 − 10 = 40, half of 80.')),
    { id: 'identify', type: 'tune', prompt: l('Retrouvez EC50 en gardant les autres paramètres fixés.', 'Find EC50 with other parameters fixed.'), experiment: { kind: 'emax', controls: ['ec50'], settings: { baseline: 10, maximum: 80 } }, targets: { ec50: 3 }, correction: l('EC50 = 3 mg/L. Ce paramètre n’est pas automatiquement une cible thérapeutique.', 'EC50 = 3 mg/L. This parameter is not automatically a therapeutic target.') },
    r('mechanism', l('Cette courbe démontre-t-elle une saturation des récepteurs ?', 'Does this curve demonstrate receptor saturation?'), [l('Distinguer description et mécanisme.', 'Distinguish description and mechanism.'), l('Demander données mécanistiques pour cette attribution.', 'Require mechanistic evidence for that attribution.')], l('Non : Emax peut décrire une réponse saturable sans mesurer occupation ni densité des récepteurs.', 'No: Emax can describe saturable response without measuring receptor occupancy or density.'))
  ]),
  a('pd-effect-compartment', l('Mesurer un délai d’équilibration', 'Measure an equilibration delay'), l('Relier ke0 et demi-temps d’équilibration.', 'Connect ke0 and equilibration half-time.'), l('Concentration plasmatique maintenue à 10 mg/L, Ce(0)=0, dCe/dt=ke0(Cp−Ce), ke0=0,5/h. Il s’agit d’une exposition constante imposée.', 'Plasma concentration held at 10 mg/L, Ce(0)=0, dCe/dt=ke0(Cp−Ce), ke0=0.5/h. This is an imposed constant exposure.'), ['sheiner-effect-compartment'], [
    n('half', l('Quel temps faut-il pour atteindre Ce = 5 mg/L ?', 'How long to reach Ce = 5 mg/L?'), Math.log(2) / 0.5, 'h', l('ln(2)/ke0 = 1,386 h.', 'ln(2)/ke0 = 1.386 h.')),
    n('two', l('Calculez Ce à 2 h : 10(1−exp(−0,5 × 2)).', 'Calculate Ce at 2 h: 10(1−exp(−0.5 × 2)).'), 10 * (1 - Math.exp(-1)), 'mg/L', l('Ce(2) = 6,321 mg/L.', 'Ce(2) = 6.321 mg/L.')),
    r('pair', l('Pourquoi une paire Cp–effet sans horaire peut-elle être insuffisante ?', 'Why may a Cp–effect pair without timing be insufficient?'), [l('Ce dépend de l’historique de Cp.', 'Ce depends on the history of Cp.'), l('Même Cp possible pendant montée et descente avec effets différents.', 'The same Cp may occur during rise and fall with different effects.')], l('Le modèle à compartiment d’effet est dynamique. Une simple relation statique E(Cp) peut masquer l’hystérésis.', 'The effect-compartment model is dynamic. A static E(Cp) relationship can conceal hysteresis.'))
  ]),
  a('pd-indirect', l('Perturber un équilibre de turnover', 'Perturb turnover equilibrium'), l('Distinguer production et disparition.', 'Distinguish production from loss.'), l('dR/dt = kin − kout R ; kin = 10 unités/h, kout = 0,2/h. Le médicament inhibe kin de 50 %, de façon constante.', 'dR/dt = kin − kout R; kin = 10 units/h, kout = 0.2/h. The drug constantly inhibits kin by 50%.'), ['dayneka-jusko-indirect'], [
    n('baseline', l('Calculez R0 avant traitement.', 'Calculate pretreatment R0.'), 50, 'units', l('R0 = kin/kout = 50.', 'R0 = kin/kout = 50.')),
    n('steady', l('Quel nouvel équilibre le modèle prédit-il ?', 'What new equilibrium does the model predict?'), 25, 'units', l('0,5 × kin/kout = 25.', '0.5 × kin/kout = 25.')),
    r('time', l('Pourquoi R ne tombe-t-il pas immédiatement à 25 ?', 'Why does R not fall immediately to 25?'), [l('La réponse est un stock avec son turnover.', 'The response is a pool with turnover.'), l('La vitesse de transition dépend de kout.', 'Transition rate depends on kout.')], l('R(t) = 25 + 25 exp(−0,2t) sous cette inhibition constante. Un effet instantané sur kin n’est pas un saut instantané de R.', 'R(t) = 25 + 25 exp(−0.2t) under constant inhibition. Instantaneous change in kin does not imply an instantaneous jump in R.'))
  ]),
  a('pd-tolerance', l('Même concentration, effet différent', 'Same concentration, different effect'), l('Construire des explications concurrentes.', 'Construct competing explanations.'), l('À Cp = 5 mg/L, un effet incrémental fictif vaut 40 au jour 1 et 20 au jour 10. Le Cp observé est identique, pas nécessairement l’historique.', 'At Cp = 5 mg/L, fictional incremental effect is 40 on day 1 and 20 on day 10. Observed Cp is identical, not necessarily its history.'), ['sharma-jusko-indirect'], [
    n('ratio', l('Quel est le ratio d’effet jour 10 / jour 1 ?', 'What is the day 10 / day 1 effect ratio?'), 0.5, '', l('20/40 = 0,5.', '20/40 = 0.5.')),
    s('hypotheses', l('Quelles hypothèses faut-il considérer ?', 'Which hypotheses should be considered?'), [l('Tolérance ou médiateur antagoniste.', 'Tolerance or an antagonistic mediator.'), l('Historique différent, maladie ou erreur de mesure.', 'Different history, disease or measurement error.'), l('Ces deux points prouvent un mécanisme unique.', 'These two points prove one unique mechanism.')], [0, 1], l('Un déclin apparent à Cp identique ne prouve pas seul une tolérance mécaniste.', 'An apparent decline at equal Cp does not alone prove mechanistic tolerance.')),
    r('design', l('Quelles données aideraient à départager ces hypothèses ?', 'What data would help distinguish these hypotheses?'), [l('Profils PK/PD répétés et chronologie complète.', 'Repeated PK/PD profiles and complete chronology.'), l('Mesures de référence et suivi après arrêt si approprié.', 'Baseline measurements and post-treatment follow-up where appropriate.')], l('Il faut un dessin informatif sur la dynamique et les facteurs concurrents, pas uniquement deux couples concentration-effet.', 'A design informative about dynamics and competing factors is needed, not just two concentration-effect pairs.'))
  ]),
  a('pd-survival', l('Du hazard à la survie', 'From hazard to survival'), l('Distinguer risque instantané, survie et endpoint.', 'Distinguish hazard, survival and endpoint.'), l('Modèle exponentiel fictif : hazard constant 0,1/mois ; S(t)=exp(−0,1t).', 'Fictional exponential model: constant hazard 0.1/month; S(t)=exp(−0.1t).'), ['holford-tte-tutorial', 'kaplan-meier-1958'], [
    n('six', l('Calculez S(6).', 'Calculate S(6).'), Math.exp(-0.6), '', l('exp(−0,6) = 0,5488 ; ce n’est pas 1 − 0,6.', 'exp(−0.6) = 0.5488; this is not 1 − 0.6.'), { experiment: { kind: 'survival', controls: ['hazard'] } }),
    n('median', l('Calculez la médiane de survie.', 'Calculate median survival.'), Math.log(2) / 0.1, 'months', l('S(t)=0,5 donne t=ln(2)/0,1=6,931 mois.', 'S(t)=0.5 gives t=ln(2)/0.1=6.931 months.')),
    r('endpoint', l('Un décès sans progression documentée est-il un événement de PFS ? Une covariable temporelle suffit-elle à un modèle joint ?', 'Is death without documented progression a PFS event? Is a time-varying covariate sufficient for a joint model?'), [l('La PFS compte progression ou décès.', 'PFS counts progression or death.'), l('Un modèle joint modélise aussi le processus longitudinal.', 'A joint model also models the longitudinal process.')], l('Oui pour la PFS selon sa définition usuelle. Non pour le modèle joint : une covariable temporelle seule ne constitue pas une modélisation conjointe.', 'Yes for PFS under its usual definition. No for a joint model: a time-varying covariate alone is not joint modeling.'))
  ]),
  a('onco-models', l('Comparer deux lois de croissance', 'Compare two growth laws'), l('Contrôler les hypothèses de croissance.', 'Check growth assumptions.'), l('T=100, kg=0,02/j ; modèle exponentiel dT/dt=kg T ; logistique dT/dt=kg T(1−T/K), K=200.', 'T=100, kg=0.02/day; exponential model dT/dt=kg T; logistic dT/dt=kg T(1−T/K), K=200.'), ['simeoni', 'stein-tumor-growth'], [
    n('exp', l('Calculez la pente exponentielle à cet instant.', 'Calculate the exponential slope at this instant.'), 2, 'units/day', l('0,02 × 100 = 2.', '0.02 × 100 = 2.')),
    n('logistic', l('Calculez la pente logistique.', 'Calculate the logistic slope.'), 1, 'units/day', l('2 × (1 − 100/200) = 1.', '2 × (1 − 100/200) = 1.')),
    r('selection', l('Des données précoces à T très inférieur à K permettent-elles de distinguer facilement ces lois ?', 'Can early data with T far below K easily distinguish these laws?'), [l('Les pentes deviennent proches lorsque T/K est petit.', 'Slopes become similar when T/K is small.'), l('Examiner durée du suivi et incertitude sur K.', 'Examine follow-up duration and uncertainty in K.')], l('Pas forcément. La plausibilité d’un plateau ne remplace pas l’information nécessaire à son estimation.', 'Not necessarily. A plausible plateau does not replace the information needed to estimate it.'))
  ]),
  a('onco-tgi', l('Stabiliser une tumeur simulée', 'Stabilize a simulated tumor'), l('Séparer prédiction TGI et causalité sur la survie.', 'Separate TGI prediction from survival causality.'), l('Exemple réduit : dT/dt=(kg−kd)T, T0=100 ; kg=0,02/j et destruction kd constante. Ce n’est pas le modèle complet de Simeoni.', 'Reduced example: dT/dt=(kg−kd)T, T0=100; kg=0.02/day and constant killing kd. This is not the full Simeoni model.'), ['claret-tgi-os', 'simeoni'], [
    n('untreated', l('Sans traitement, calculez T à 30 jours.', 'Without treatment, calculate T at 30 days.'), 100 * Math.exp(0.6), 'units', l('100 exp(0,02 × 30) = 182,212.', '100 exp(0.02 × 30) = 182.212.')),
    { id: 'stabilize', type: 'tune', prompt: l('Ajustez kd pour garder T constant.', 'Adjust kd to keep T constant.'), experiment: { kind: 'growth', controls: ['kill'] }, targets: { kill: 0.02 }, correction: l('kd = kg = 0,02/j annule la croissance nette dans cette illustration.', 'kd = kg = 0.02/day cancels net growth in this illustration.') },
    r('survival', l('Cette stabilisation démontre-t-elle qu’une dose plus forte prolonge la survie ?', 'Does this stabilization demonstrate that a higher dose prolongs survival?'), [l('Prédiction conditionnelle à un modèle réduit.', 'Prediction conditional on a reduced model.'), l('Association tumeur-survie distincte d’un effet causal de dose.', 'Tumor-survival association differs from causal dose effect.')], l('Non. Survie, toxicité et biais d’exposition doivent être modélisés et évalués séparément ; le graphe ne prouve pas une causalité.', 'No. Survival, toxicity and exposure bias need separate modeling and evaluation; the graph does not prove causality.'))
  ]),
  a('onco-tox', l('Transit et rétrocontrôle hématologique', 'Hematologic transit and feedback'), l('Lire la convention de MTT et le feedback.', 'Read the MTT convention and feedback.'), l('Convention Friberg utilisée ici : ktr=4/MTT, MTT=120 h. Circ0=5, Circ=2,5, gamma=0,17 ; feedback=(Circ0/Circ)^gamma.', 'Friberg convention used here: ktr=4/MTT, MTT=120 h. Circ0=5, Circ=2.5, gamma=0.17; feedback=(Circ0/Circ)^gamma.'), ['friberg'], [
    n('ktr', l('Calculez ktr.', 'Calculate ktr.'), 4 / 120, '1/h', l('4/120 = 0,03333/h ; le facteur dépend de la structure et de la convention MTT.', '4/120 = 0.03333/h; the factor depends on structure and MTT convention.'), { tolerance: { kind: 'absolute', value: 0.001 } }),
    n('feedback', l('Calculez le facteur de rétrocontrôle.', 'Calculate the feedback factor.'), 2 ** 0.17, '', l('2^0,17 = 1,125 environ : stimulation compensatrice.', '2^0.17 is about 1.125: compensatory stimulation.')),
    r('nadir', l('Pourquoi le nadir peut-il survenir après la disparition de l’exposition ?', 'Why may the nadir occur after exposure has disappeared?'), [l('L’effet en amont traverse les compartiments de maturation.', 'The upstream effect propagates through maturation compartments.'), l('Le délai ne se réduit pas à la demi-vie PK.', 'The delay is not just the PK half-life.')], l('L’inhibition des précurseurs se manifeste plus tard dans le sang. Les observations longitudinales et cycles doivent être pris en compte.', 'Precursor inhibition appears later in blood. Longitudinal observations and cycles must be considered.'))
  ]),
  a('infectio-pkpd', l('Concentration libre au-dessus de la CMI', 'Unbound concentration above MIC'), l('Calculer un indice et distinguer PTA individuelle.', 'Calculate an index and distinguish it from PTA.'), l('Profil fictif libre : Cu(t)=8 exp(−0,25t) mg/L sur 8 h ; CMI=2 mg/L, pas de nouvelle dose dans la fenêtre.', 'Fictional unbound profile: Cu(t)=8 exp(−0.25t) mg/L over 8 h; MIC=2 mg/L, no new dose within the window.'), ['craig-pkpd', 'eucast'], [
    n('cross', l('À quelle heure Cu rejoint-elle la CMI ?', 'At what time does Cu reach MIC?'), Math.log(4) / 0.25, 'h', l('8 exp(−0,25t)=2 donne t=5,545 h.', '8 exp(−0.25t)=2 gives t=5.545 h.')),
    n('fraction', l('Calculez fT>CMI en pourcentage de la fenêtre.', 'Calculate fT>MIC as a percentage of the window.'), Math.log(4) / 0.25 / 8 * 100, '%', l('5,545/8 × 100 = 69,31 % ; ce n’est pas une PTA.', '5.545/8 × 100 = 69.31%; this is not PTA.')),
    r('pta', l('Que faut-il ajouter pour estimer une PTA ?', 'What must be added to estimate PTA?'), [l('Une cible définie et une distribution d’expositions.', 'A defined target and an exposure distribution.'), l('Fixer CMI et population ; distinguer population et posterior individuel.', 'Specify MIC and population; distinguish population and individual posterior.')], l('La PTA est une probabilité d’atteindre la cible, pas le pourcentage de temps d’un seul profil. Aucune cible clinique n’est proposée ici.', 'PTA is the probability of attaining a target, not the time percentage of one profile. No clinical target is proposed here.'))
  ]),
  a('infectio-tdm', l('Compter des atteintes de cible', 'Count target attainments'), l('Interpréter une PTA et sa dépendance à la CMI.', 'Interpret PTA and its dependence on MIC.'), l('Quatre AUC24 simulées équipondérées : 200, 300, 400, 500 mg.h/L. Cible fictive AUC24/CMI ≥ 300 h, CMI = 1 mg/L.', 'Four equally weighted simulated AUC24 values: 200, 300, 400, 500 mg.h/L. Fictional target AUC24/MIC ≥ 300 h, MIC = 1 mg/L.'), ['minichmayr-mipd', 'craig-pkpd'], [
    n('pta', l('Calculez la PTA empirique.', 'Calculate empirical PTA.'), 75, '%', l('Trois profils sur quatre atteignent la cible.', 'Three out of four profiles reach the target.')),
    n('mic', l('Avec CMI = 2 mg/L et même cible, quelle PTA obtient-on ?', 'With MIC = 2 mg/L and the same target, what PTA results?'), 0, '%', l('Il faudrait AUC24 ≥ 600 ; aucun profil n’y parvient.', 'AUC24 would need to be ≥ 600; no profile reaches it.')),
    r('uncertainty', l('Pourquoi quatre simulations ne suffisent-elles pas pour une décision clinique ?', 'Why are four simulations insufficient for a clinical decision?'), [l('Incertitude Monte-Carlo et modèle/population représentatifs.', 'Monte Carlo uncertainty and representative model/population.'), l('Cible validée, mesure de CMI, exposition libre/totale et toxicité.', 'Validated target, MIC measurement, unbound/total exposure and toxicity.')], l('Ce comptage illustre la définition, pas une performance validée. La cible est fictive et non une recommandation antibiotique.', 'This count illustrates the definition, not validated performance. The target is fictional, not an antibiotic recommendation.'))
  ]),
  a('infectio-viral', l('Lire une décroissance en log10', 'Read a log10 decline'), l('Convertir pente logarithmique et vitesse.', 'Convert log slope to rate.'), l('Phase fictive V(t)=V0 exp(−ct), baisse de 2 log10 en 4 jours ; production négligée pendant cette phase.', 'Fictional phase V(t)=V0 exp(−ct), a 2-log10 fall over 4 days; production neglected during this phase.'), ['perelson-hiv', 'neumann-hcv'], [
    n('rate', l('Calculez c = 2 ln(10)/4.', 'Calculate c = 2 ln(10)/4.'), Math.log(10) / 2, '1/day', l('c = 1,1513/j ; une pente log10 n’est pas une pente en logarithme naturel.', 'c = 1.1513/day; a log10 slope is not a natural-log slope.')),
    n('half', l('Calculez la demi-vie de cette phase.', 'Calculate the half-life of this phase.'), Math.log(2) / (Math.log(10) / 2), 'days', l('ln(2)/c = 0,6021 jour.', 'ln(2)/c = 0.6021 day.')),
    r('mechanism', l('Cette pente identifie-t-elle toujours la clairance virale intrinsèque ?', 'Does this slope always identify intrinsic viral clearance?'), [l('La production négligée est une hypothèse forte.', 'Negligible production is a strong assumption.'), l('Cellules infectées, efficacité et phases multiples peuvent intervenir.', 'Infected cells, efficacy and multiple phases may matter.')], l('Non : dans un système couplé, une pente observée peut combiner plusieurs processus. L’exercice isole une phase simplifiée.', 'No: in a coupled system, an observed slope may combine processes. This exercise isolates a simplified phase.'))
  ]),
  a('mab-pk', l('Une demi-vie longue, avec quelles unités ?', 'A long half-life, in which units?'), l('Relier petit CL et volume apparent.', 'Connect low CL and apparent volume.'), l('Illustration mono-compartimentale IV linéaire : dose 100 mg, CL = 0,2 L/j, V = 4 L. Pas de TMDD dans ce calcul.', 'Linear one-compartment IV illustration: dose 100 mg, CL = 0.2 L/day, V = 4 L. No TMDD in this calculation.'), ['ryman-meibohm', 'dirks-meibohm'], [
    n('half', l('Calculez la demi-vie.', 'Calculate half-life.'), Math.log(2) * 20, 'days', l('ln(2) × 4/0,2 = 13,863 jours.', 'ln(2) × 4/0.2 = 13.863 days.')),
    n('auc', l('Calculez AUC complète.', 'Calculate complete AUC.'), 500, 'mg.day/L', l('100/0,2 = 500 mg.j/L, pas mg.h/L.', '100/0.2 = 500 mg.day/L, not mg.h/L.')),
    r('nonlinear', l('Pourquoi ne pas généraliser cette proportionnalité à toutes les doses d’un anticorps ?', 'Why not generalize this proportionality to all antibody doses?'), [l('La disposition médiée par la cible peut être saturable.', 'Target-mediated disposition may be saturable.'), l('État de maladie, ADA et évolution temporelle peuvent intervenir.', 'Disease state, ADA and time variation may matter.')], l('La PK linéaire est une hypothèse locale à vérifier, pas une propriété universelle des anticorps.', 'Linear PK is a local assumption to check, not a universal antibody property.'))
  ]),
  a('mab-tmdd', l('Saturation d’une voie d’élimination', 'Saturation of an elimination pathway'), l('Distinguer vitesse et clairance apparente.', 'Distinguish rate from apparent clearance.'), l('Approximation Michaelis-Menten : vitesse=Vmax C/(Km+C), Vmax=10 mg/j, Km=2 mg/L. Ce n’est pas un système TMDD complet.', 'Michaelis-Menten approximation: rate=Vmax C/(Km+C), Vmax=10 mg/day, Km=2 mg/L. This is not a full TMDD system.'), ['mager-jusko-tmdd', 'gibiansky-qss'], [
    n('rate', l('À C=2, calculez la vitesse.', 'At C=2, calculate the rate.'), 5, 'mg/day', l('10 × 2/(2+2) = 5.', '10 × 2/(2+2) = 5.')),
    n('clearance', l('À C=8, calculez la clairance apparente de cette voie : vitesse/C.', 'At C=8, calculate this pathway apparent clearance: rate/C.'), 1, 'L/day', l('Vitesse=8 mg/j, donc 8/8=1 L/j ; à C=2 elle valait 2,5 L/j.', 'Rate=8 mg/day, so 8/8=1 L/day; at C=2 it was 2.5 L/day.')),
    r('target', l('Que perd cette approximation par rapport à une TMDD complète ?', 'What is lost relative to full TMDD?'), [l('Dynamique de cible et complexe.', 'Target and complex dynamics.'), l('Hypothèses de quasi-équilibre ou quasi-stationnarité à vérifier.', 'Quasi-equilibrium or quasi-steady-state assumptions to check.')], l('Une fonction saturable ne représente pas explicitement toute la cinétique de liaison, synthèse et internalisation.', 'A saturable function does not explicitly represent all binding, synthesis and internalization kinetics.'))
  ]),
  a('mab-ada', l('Association ADA et exposition', 'ADA and exposure association'), l('Quantifier sans conclure à un mécanisme universel.', 'Quantify without claiming a universal mechanism.'), l('Exemple IV linéaire à dose identique : CL=0,2 L/j avant, 0,3 L/j après détection d’ADA ; autres facteurs non contrôlés.', 'Same-dose linear IV example: CL=0.2 L/day before, 0.3 L/day after ADA detection; other factors uncontrolled.'), ['ryman-meibohm', 'fda-immunogenicity'], [
    n('clratio', l('Calculez le ratio de CL.', 'Calculate the CL ratio.'), 1.5, '', l('0,3/0,2 = 1,5.', '0.3/0.2 = 1.5.')),
    n('auc', l('Sous cette PK, calculez AUCaprès/AUCavant.', 'Under this PK, calculate AUCafter/AUCbefore.'), 2 / 3, '', l('Le ratio des AUC est l’inverse : 0,2/0,3 = 0,667.', 'The AUC ratio is inverse: 0.2/0.3 = 0.667.')),
    r('causality', l('Ces valeurs démontrent-elles que tous les ADA augmentent la CL ?', 'Do these values demonstrate that all ADA increase CL?'), [l('Considérer titre, persistance, neutralisation, assay et molécule.', 'Consider titer, persistence, neutralization, assay and molecule.'), l('Évaluer facteurs confondants et chronologie.', 'Evaluate confounders and chronology.')], l('Non. Les ADA peuvent modifier la PK, mais certains ont peu d’effet mesurable ; cet exemple ne prouve ni causalité ni universalité.', 'No. ADA may alter PK, but some have little measurable effect; this example proves neither causality nor universality.'))
  ])
];
