import { l, activity as a, numeric as n, select as s, reflect as r } from '../../learning/activityContent.js';
export const mathNcaActivities = [
  a('math-edo', l('Un pas numérique face à la solution exacte', 'A numerical step against the exact solution'), l('Contrôler signe et erreur de discrétisation.', 'Check sign and discretization error.'), l('dA/dt = −0,2 A ; A(0) = 100 mg. Euler : A(t+h) = A(t) + h dA/dt.', 'dA/dt = −0.2 A; A(0) = 100 mg. Euler: A(t+h) = A(t) + h dA/dt.'), ['gibaldi-perrier'], [
    n('euler', l('Avec h = 1 h, calculez A(1) par Euler.', 'With h = 1 h, calculate Euler A(1).'), 80, 'mg', l('100 − 0,2 × 100 × 1 = 80 mg.', '100 − 0.2 × 100 × 1 = 80 mg.')),
    n('exact', l('Calculez la solution exacte A(1) = 100 exp(−0,2).', 'Calculate exact A(1) = 100 exp(−0.2).'), 100 * Math.exp(-0.2), 'mg', l('81,873 mg : un pas numérique n’est pas la solution exacte.', '81.873 mg: a numerical step is not the exact solution.')),
    r('step', l('Euler donne une quantité négative si h = 6 h. Comment l’interpréter ?', 'Euler gives a negative amount if h = 6 h. How should this be interpreted?'), [l('Identifier une erreur numérique, pas une PK négative.', 'Identify numerical error, not negative PK.'), l('Réduire le pas et contrôler la convergence ou employer un solveur adapté.', 'Reduce the step and check convergence or use an appropriate solver.')], l('Le facteur 1 − 0,2h devient négatif. Il faut tester le solveur avant d’interpréter un comportement non physique.', 'The factor 1 − 0.2h becomes negative. Test the solver before interpreting nonphysical behavior.'))
  ]),
  a('math-regression', l('Pondérer des résidus hétéroscédastiques', 'Weight heteroscedastic residuals'), l('Passer du résidu à la vraisemblance.', 'Move from residual to likelihood.'), l('Deux résidus indépendants : 1 et 4 mg/L ; écarts-types connus 1 et 4 mg/L.', 'Two independent residuals: 1 and 4 mg/L; known standard deviations 1 and 4 mg/L.'), ['davidian-giltinan', 'wang-nonmem-methods'], [
    n('raw', l('Calculez la somme brute des carrés.', 'Calculate the raw sum of squares.'), 17, '(mg/L)^2', l('1² + 4² = 17.', '1² + 4² = 17.')),
    n('weighted', l('Calculez la somme des carrés standardisés.', 'Calculate the sum of standardized squares.'), 2, '', l('(1/1)² + (4/4)² = 2 : les deux écarts valent un SD.', '(1/1)² + (4/4)² = 2: both deviations equal one SD.')),
    r('likelihood', l('Si les SD deviennent des paramètres à estimer, suffit-il de minimiser cette somme ?', 'If SDs become estimated parameters, is minimizing this sum sufficient?'), [l('Inclure le terme log de variance de la vraisemblance normale.', 'Include the normal likelihood log-variance term.'), l('Éviter de gonfler arbitrairement les SD.', 'Avoid arbitrarily inflating SDs.')], l('Non : −2 log L contient aussi les log variances. Omettre leur coût favoriserait des variances arbitrairement grandes.', 'No: −2 log L also contains log variances. Omitting their cost would favor arbitrarily large variances.'))
  ]),
  a('math-stats', l('Un LRT sous conditions', 'A likelihood-ratio test with conditions'), l('Distinguer test régulier et frontière.', 'Distinguish regular testing from boundary cases.'), l('Modèles ML emboîtés, mêmes observations et définition de vraisemblance : OFV0 = 108, OFV1 = 104, un effet fixe supplémentaire intérieur au domaine.', 'Nested ML models, same observations and likelihood definition: OFV0 = 108, OFV1 = 104, one additional interior fixed effect.'), ['wilks-1938', 'asa-pvalue'], [
    n('delta', l('Calculez la diminution d’OFV.', 'Calculate the OFV decrease.'), 4, '', l('108 − 104 = 4.', '108 − 104 = 4.')),
    s('conditions', l('Que vérifier avant d’utiliser le repère 3,84 ?', 'What should be checked before using 3.84 as a reference?'), [l('Convergence et maxima comparables.', 'Convergence and comparable maxima.'), l('Conditions asymptotiques et de régularité.', 'Asymptotic and regularity conditions.'), l('La valeur 3,84 s’applique toujours à une variance testée à zéro.', '3.84 always applies to a variance tested at zero.')], [0, 1], l('Une variance nulle place H0 à une frontière : le chi-deux usuel ne s’applique pas automatiquement.', 'Zero variance places H0 on a boundary: the usual chi-square does not apply automatically.')),
    r('decision', l('Une différence statistique suffit-elle à retenir l’effet ?', 'Is statistical evidence sufficient to retain the effect?'), [l('Examiner taille, précision et plausibilité de l’effet.', 'Examine effect size, precision and plausibility.'), l('Tenir compte des essais multiples et de la validation.', 'Consider multiple testing and validation.')], l('Non : le test répond à une question restreinte sous hypothèses, pas à toute la décision scientifique.', 'No: the test answers a restricted question under assumptions, not the entire scientific decision.'))
  ]),
  a('math-bayes', l('Une mesure peu précise et un prior', 'An imprecise measurement and a prior'), l('Calculer les poids de précision.', 'Calculate precision weights.'), l('Exemple scalaire : prior normal de moyenne 4 et variance 1 ; mesure y = 8 de variance 9. Ce n’est pas un modèle de concentrations.', 'Scalar example: normal prior mean 4, variance 1; measurement y = 8 with variance 9. This is not a concentration model.'), ['sheiner-forecasting'], [
    n('weight', l('Quel poids reçoit la mesure dans la moyenne posterior ?', 'What weight does the measurement receive in the posterior mean?'), 0.1, '', l('(1/9)/(1 + 1/9) = 0,1.', '(1/9)/(1 + 1/9) = 0.1.')),
    n('posterior', l('Calculez la moyenne posterior.', 'Calculate posterior mean.'), 4.4, '', l('0,9 × 4 + 0,1 × 8 = 4,4.', '0.9 × 4 + 0.1 × 8 = 4.4.')),
    r('prior', l('Que devient cette confiance si le prior provient d’une autre population ?', 'What happens to this confidence if the prior comes from another population?'), [l('La précision formelle ne mesure pas le biais du prior.', 'Formal precision does not measure prior bias.'), l('Évaluer transportabilité et sensibilité.', 'Evaluate transportability and sensitivity.')], l('La mise à jour peut être précise mais biaisée. Il faut distinguer incertitude conditionnelle et validité des hypothèses.', 'The update may be precise but biased. Distinguish conditional uncertainty from validity of assumptions.'))
  ]),
  a('math-covariates', l('Transformer un effet de poids', 'Transform a weight effect'), l('Identifier référence et coefficient.', 'Identify reference and coefficient.'), l('log(CL) = log(5) + beta log(WT/70). Le ratio CL(140)/CL(70) vaut 1,6 dans cet exemple fictif.', 'log(CL) = log(5) + beta log(WT/70). CL(140)/CL(70) is 1.6 in this fictional example.'), ['jonsson-karlsson-scm', 'ribbing-selection-bias'], [
    n('beta', l('Calculez beta = log(1,6)/log(2).', 'Calculate beta = log(1.6)/log(2).'), Math.log(1.6) / Math.log(2), '', l('beta = 0,6781 ; le ratio 1,6 n’est pas le coefficient.', 'beta = 0.6781; the ratio 1.6 is not the coefficient.')),
    n('reference', l('Quelle est CL à 70 kg ?', 'What is CL at 70 kg?'), 5, 'L/h', l('log(WT/70) = 0 à la référence.', 'log(WT/70) = 0 at the reference.')),
    r('selection', l('Quel risque si le meilleur seuil est choisi après des dizaines d’essais ?', 'What is the risk if the best threshold is chosen after dozens of attempts?'), [l('Biais de sélection et multiplicité.', 'Selection bias and multiplicity.'), l('Validation indépendante ou procédure imbriquée.', 'Independent validation or a nested procedure.')], l('Le gain apparent peut être optimiste. La procédure de sélection entière doit être évaluée, pas seulement le dernier modèle.', 'Apparent gain may be optimistic. Evaluate the entire selection procedure, not only the final model.'))
  ]),
  a('math-fisher', l('Deux plans, deux matrices d’information', 'Two designs, two information matrices'), l('Comparer information et précision locale.', 'Compare information and local precision.'), l('Même modèle, paramètres et unités : FIM(A) = diag(4,1), FIM(B) = diag(3,3). Approximation Cov = FIM inverse.', 'Same model, parameters and units: FIM(A) = diag(4,1), FIM(B) = diag(3,3). Approximation Cov = inverse FIM.'), ['mentre-optimal-design', 'pfim'], [
    n('det', l('Calculez det(FIM(B))/det(FIM(A)).', 'Calculate det(FIM(B))/det(FIM(A)).'), 2.25, '', l('9/4 = 2,25 ; B est préférable selon ce critère D local.', '9/4 = 2.25; B is preferable by this local D criterion.')),
    n('se', l('Quel SE approximatif pour le second paramètre sous A ?', 'What approximate SE for the second parameter under A?'), 1, '', l('Variance = 1/1 ; SE = sqrt(1) = 1.', 'Variance = 1/1; SE = sqrt(1) = 1.')),
    r('robust', l('Pourquoi le meilleur plan local peut-il décevoir ?', 'Why might the best local design disappoint?'), [l('Il dépend des paramètres nominaux et de la structure.', 'It depends on nominal parameters and structure.'), l('Vérifier robustesse, contraintes et simulations.', 'Check robustness, constraints and simulations.')], l('L’approximation FIM ne couvre pas toutes les erreurs de modèle ni les contraintes opérationnelles ; une analyse de sensibilité est nécessaire.', 'The FIM approximation does not cover all model errors or operational constraints; sensitivity analysis is needed.'))
  ]),
  a('math-copula', l('Marges identiques, dépendance différente', 'Same margins, different dependence'), l('Ne pas confondre marginales et distribution jointe.', 'Do not confuse marginals and joint distribution.'), l('Deux variables normales X et Y, moyennes 0, SD(X) = 2, SD(Y) = 3 ; corrélation 0,5.', 'Two normal variables X and Y, means 0, SD(X) = 2, SD(Y) = 3; correlation 0.5.'), ['nelsen-copulas', 'bonate'], [
    n('cov', l('Calculez Cov(X,Y).', 'Calculate Cov(X,Y).'), 3, '', l('rho × SD(X) × SD(Y) = 0,5 × 2 × 3 = 3.', 'rho × SD(X) × SD(Y) = 0.5 × 2 × 3 = 3.')),
    n('sum', l('Calculez Var(X+Y).', 'Calculate Var(X+Y).'), 19, '', l('4 + 9 + 2 × 3 = 19, contre 13 sous indépendance.', '4 + 9 + 2 × 3 = 19, compared with 13 under independence.')),
    r('tails', l('La même corrélation suffit-elle pour reproduire tous les événements extrêmes ?', 'Is the same correlation sufficient to reproduce all extreme events?'), [l('La copule décrit une dépendance au-delà d’un seul coefficient.', 'A copula describes dependence beyond one coefficient.'), l('Examiner les queues et la plausibilité physiologique.', 'Examine tails and physiological plausibility.')], l('Non : des distributions jointes peuvent partager marges et corrélation tout en différant dans les queues.', 'No: joint distributions can share marginals and correlation yet differ in their tails.'))
  ]),
  a('nca-intro', l('Ce que les observations permettent de calculer', 'What observations allow us to calculate'), l('Séparer AUC observée et extrapolation.', 'Separate observed AUC and extrapolation.'), l('Concentrations fictives à t = 0, 2, 4 h : 8, 4, 2 mg/L. Utiliser les trapèzes linéaires.', 'Fictional concentrations at t = 0, 2, 4 h: 8, 4, 2 mg/L. Use linear trapezoids.'), ['yamaoka-moments', 'gibaldi-perrier'], [
    n('first', l('Calculez AUC(0,2).', 'Calculate AUC(0,2).'), 12, 'mg.h/L', l('(8 + 4)/2 × 2 = 12.', '(8 + 4)/2 × 2 = 12.'), { table: { columns: [l('Temps (h)', 'Time (h)'), l('C (mg/L)', 'C (mg/L)')], rows: [[0, 8], [2, 4], [4, 2]] }, hints: [l('Aire = durée × moyenne des deux concentrations.', 'Area = duration × mean of the two concentrations.')] }),
    n('total', l('Calculez AUC(0,4).', 'Calculate AUC(0,4).'), 18, 'mg.h/L', l('12 + (4 + 2)/2 × 2 = 18.', '12 + (4 + 2)/2 × 2 = 18.')),
    r('infinite', l('Pourquoi 18 n’est-il pas l’AUC à l’infini ?', 'Why is 18 not AUC to infinity?'), [l('La concentration à 4 h est non nulle.', 'Concentration at 4 h is nonzero.'), l('Il faut justifier une pente terminale et l’extrapolation.', 'A terminal slope and extrapolation must be justified.')], l('La NCA ne supprime pas les hypothèses de prélèvement et d’extrapolation. Un profil incomplet peut donner une AUC complète imprécise.', 'NCA does not remove sampling and extrapolation assumptions. An incomplete profile may give imprecise complete AUC.'))
  ]),
  a('nca-auc', l('Quantifier la partie extrapolée', 'Quantify the extrapolated part'), l('Auditer une AUC terminale.', 'Audit terminal AUC.'), l('AUC observée = 30 mg.h/L ; dernière concentration = 2 mg/L ; lambda_z = 0,2/h.', 'Observed AUC = 30 mg.h/L; last concentration = 2 mg/L; lambda_z = 0.2/h.'), ['yamaoka-moments', 'gabrielsson-weiner'], [
    n('tail', l('Calculez l’AUC extrapolée.', 'Calculate extrapolated AUC.'), 10, 'mg.h/L', l('Clast/lambda_z = 2/0,2 = 10.', 'Clast/lambda_z = 2/0.2 = 10.')),
    n('fraction', l('Quel pourcentage de l’AUC complète est extrapolé ?', 'What percentage of complete AUC is extrapolated?'), 25, '%', l('10/(30 + 10) × 100 = 25 %.', '10/(30 + 10) × 100 = 25%.')),
    r('terminal', l('Quels éléments rendent lambda_z crédible ?', 'What makes lambda_z credible?'), [l('Choix de points d’une phase terminale log-linéaire.', 'Points selected from a log-linear terminal phase.'), l('Étendue temporelle, bruit, nombre de points et sensibilité au choix.', 'Time span, noise, point count and sensitivity to selection.')], l('Un grand R² seul ne suffit pas. Une pente mal identifiée peut amplifier l’incertitude du terme extrapolé.', 'A high R² alone is insufficient. A poorly determined slope may amplify uncertainty in the extrapolated term.'))
  ]),
  a('nca-params', l('Corriger le MRT après perfusion', 'Correct MRT after infusion'), l('Tenir compte du temps d’entrée.', 'Account for input duration.'), l('Perfusion IV constante de 100 mg sur 2 h : AUC = 20 mg.h/L, AUMC = 120 mg.h²/L. PK linéaire, intégrales complètes.', 'Constant IV infusion of 100 mg over 2 h: AUC = 20 mg.h/L, AUMC = 120 mg.h²/L. Linear PK, complete integrals.'), ['yamaoka-moments', 'gibaldi-perrier'], [
    n('cl', l('Calculez CL.', 'Calculate CL.'), 5, 'L/h', l('Dose/AUC = 100/20 = 5.', 'Dose/AUC = 100/20 = 5.')),
    n('mrt', l('Calculez MRT corrigé = AUMC/AUC − Tinf/2.', 'Calculate corrected MRT = AUMC/AUC − Tinf/2.'), 5, 'h', l('120/20 − 2/2 = 5 h, et non 6 h.', '120/20 − 2/2 = 5 h, not 6 h.')),
    n('vss', l('Calculez Vss avec ce MRT.', 'Calculate Vss using this MRT.'), 25, 'L', l('Vss = CL × MRT = 5 × 5 = 25 L. Le calcul non corrigé donnerait 30 L.', 'Vss = CL × MRT = 5 × 5 = 25 L. The uncorrected calculation would give 30 L.'))
  ]),
  a('nca-absorption', l('Le ratio ponctuel ne décide pas seul', 'The point ratio does not decide alone'), l('Lire l’intervalle de bioéquivalence.', 'Read a bioequivalence interval.'), l('Exemple fictif de ratio test/référence des moyennes géométriques d’AUC : 1,05 ; IC90 % = [0,79 ; 1,20]. Pour cet exercice, limites applicables [0,80 ; 1,25].', 'Fictional test/reference geometric-mean AUC ratio: 1.05; 90% CI = [0.79, 1.20]. For this exercise, applicable limits [0.80, 1.25].'), ['fda-bioequivalence', 'ema-bioequivalence'], [
    n('percent', l('Exprimez le ratio ponctuel en pourcentage.', 'Express the point ratio as a percentage.'), 105, '%', l('1,05 × 100 = 105 %.', '1.05 × 100 = 105%.')),
    s('interval', l('Que conclure pour l’AUC avec les limites indiquées ?', 'What can be concluded for AUC using these limits?'), [l('L’IC90 % n’est pas entièrement contenu.', 'The 90% CI is not entirely contained.'), l('La valeur ponctuelle suffit à conclure.', 'The point value is sufficient to conclude.'), l('Le critère spécifié n’est pas satisfait.', 'The specified criterion is not met.')], [0, 2], l('La borne 0,79 est sous 0,80. Cela ne prouve pas à lui seul une différence clinique.', 'The 0.79 bound is below 0.80. This alone does not prove a clinical difference.')),
    r('scope', l('Pourquoi préciser les limites applicables et l’analyse de Cmax ?', 'Why specify applicable limits and the Cmax analysis?'), [l('Les exigences dépendent du produit et du cadre retenu.', 'Requirements depend on the product and framework.'), l('AUC ne remplace pas les autres critères préspécifiés.', 'AUC does not replace other prespecified criteria.')], l('Le raisonnement porte sur l’IC du ratio des moyennes géométriques, habituellement calculé sur l’échelle log, et non sur des ratios individuels.', 'The reasoning concerns the CI of the geometric-mean ratio, usually calculated on the log scale, not individual ratios.'))
  ])
];
