import { l, activity as a, numeric as n, select as s, reflect as r } from '../../learning/activityContent.js';

// Deliberately matched scenarios across tools make parameterization comparable.
const tools = [
  { name: 'NONMEM', key: 'nonmem', source: 'nonmem', structure: 'CL = THETA(1)*EXP(ETA(1))\nV = THETA(2)*EXP(ETA(2))\nS1 = V', variance: '$OMEGA\n0.09', error: '$ERROR\nY = F*(1+EPS(1))\n$SIGMA\n0.04', coefficient: 0.04 },
  { name: 'Monolix', key: 'monolix', source: 'monolix', structure: '[LONGITUDINAL]\ninput = {V, Cl}\nPK:\nCc = pkmodel(V, Cl)\nOUTPUT:\noutput = {Cc}', variance: 'distribution = logNormal\ntypical CL = 5\nomega_CL = 0.3', error: 'proportional error\nSD(Y | prediction) = b * prediction\nb = 0.2', coefficient: 0.2 },
  { name: 'nlmixr2', key: 'nlmixr2', source: 'nlmixr2', structure: 'ini({ tcl <- log(5); tv <- log(20) })\nmodel({\n  cl <- exp(tcl)\n  v <- exp(tv)\n  cp <- centr/v\n})', variance: 'ini({ eta.cl ~ 0.09 })\nmodel({ cl <- exp(tcl + eta.cl) })', error: 'ini({ prop.sd <- 0.2 })\nmodel({ cp ~ prop(prop.sd) })', coefficient: 0.2 }
];

export const softwareActivities = [
  a('tools-algorithms', l('Comparer des résultats de moteurs', 'Compare engine results'), l('Vérifier l’équivalence du problème estimé.', 'Check equivalence of the fitted problem.'), l('Même modèle : deux lancements renvoient OFV 250 et 252, mais l’un utilise une approximation FOCE et l’autre une estimation de vraisemblance par importance sampling.', 'Same model: two runs return OFV 250 and 252, but one uses a FOCE approximation and the other importance-sampling likelihood estimation.'), ['wang-nonmem-methods', 'kuhn-lavielle-saem'], [
    n('difference', l('Calculez l’écart numérique.', 'Calculate the numerical difference.'), 2, '', l('252−250=2 ; cela ne constitue pas automatiquement un LRT.', '252−250=2; this is not automatically an LRT.')),
    s('compare', l('Que faut-il harmoniser ?', 'What should be harmonized?'), [l('Définition de vraisemblance et constantes.', 'Likelihood definition and constants.'), l('Données, contraintes et convergence.', 'Data, constraints and convergence.'), l('Seulement la couleur des graphiques.', 'Only plot colors.')], [0, 1], l('Deux sorties appelées OFV ne sont pas nécessairement comparables directement.', 'Two outputs called OFV are not necessarily directly comparable.')),
    r('repeat', l('Pourquoi répéter avec plusieurs initialisations ou graines ?', 'Why repeat with multiple initializations or seeds?'), [l('Détecter minima locaux et instabilité.', 'Detect local minima and instability.'), l('Quantifier variabilité Monte-Carlo des méthodes stochastiques.', 'Assess Monte Carlo variability of stochastic methods.')], l('L’accord de plusieurs lancements renforce un diagnostic numérique, sans démontrer un maximum global ni une structure correcte.', 'Agreement across runs strengthens numerical diagnosis without proving a global maximum or correct structure.'))
  ]),
  a('tools-simulation', l('Simuler un patient ou des observations ?', 'Simulate a patient or observations?'), l('Séparer ETA, EPS et pas de sortie.', 'Separate ETA, EPS and output grid.'), l('Simulation de 10 patients, 25 temps par patient, une occasion. Paramètres individuels fixes au cours de l’occasion ; erreur de mesure indépendante.', 'Simulation of 10 patients, 25 times per patient, one occasion. Individual parameters fixed within the occasion; independent measurement error.'), ['mrgsolve', 'fidler-nlmixr'], [
    n('eta', l('Combien de vecteurs ETA faut-il tirer ?', 'How many ETA vectors should be drawn?'), 10, 'vectors', l('Un vecteur par patient, pas un par temps.', 'One vector per patient, not one per time.')),
    n('eps', l('Combien de tirages d’erreur pour une observation à chaque temps ?', 'How many error draws for one observation at each time?'), 250, 'draws', l('10 × 25=250 tirages sous l’hypothèse d’indépendance.', '10 × 25=250 draws under the independence assumption.')),
    r('reproducible', l('Que conserver pour rendre le scénario reproductible ?', 'What should be retained to make the scenario reproducible?'), [l('Code, versions, paramètres, graines et événements.', 'Code, versions, parameters, seeds and events.'), l('Tolérances du solveur et distinction prédiction/observation.', 'Solver tolerances and distinction between prediction and observation.')], l('Une grille de sortie plus fine ne signifie pas automatiquement une meilleure précision d’intégration. Le code et les événements font partie du résultat.', 'A finer output grid does not automatically imply better integration accuracy. Code and events are part of the result.'))
  ]),
  a('tools-mipd', l('Auditer l’historique avant MAP', 'Audit history before MAP'), l('Mettre doses et prélèvements sur la même horloge.', 'Put doses and samples on the same clock.'), l('Bolus fictifs à 08:00 et 20:00 le même jour ; prélèvement à 19:00. Temps zéro à 08:00. Même date et fuseau.', 'Fictional boluses at 08:00 and 20:00 on the same day; sample at 19:00. Time zero at 08:00. Same date and time zone.'), ['mapbayr', 'sheiner-forecasting'], [
    n('sample', l('Quel TIME attribuer au prélèvement ?', 'What TIME should the sample receive?'), 11, 'h', l('19−8=11 h.', '19−8=11 h.')),
    n('dose', l('Quel TIME attribuer au second bolus ?', 'What TIME should the second bolus receive?'), 12, 'h', l('20−8=12 h ; il est postérieur au prélèvement.', '20−8=12 h; it occurs after the sample.')),
    r('fit', l('Un très bon ajustement suffit-il si le second bolus est codé à 10 h ?', 'Is a very good fit sufficient if the second bolus is coded at 10 h?'), [l('Un historique faux change le problème inverse.', 'Incorrect history changes the inverse problem.'), l('Le modèle peut compenser via paramètres et erreur.', 'The model may compensate through parameters and error.')], l('Non. Vérifier chronologie, unités, covariables et modèle d’erreur précède l’interprétation des EBE et de l’AUC.', 'No. Check chronology, units, covariates and error model before interpreting EBEs and AUC.'))
  ]),
  a('residual-mipd', l('Changer le poids de la mesure', 'Change measurement weight'), l('Comprendre le levier résiduel sans règle universelle.', 'Understand the residual-error lever without a universal rule.'), l('Exemple gaussien scalaire : prior moyenne 5 variance 4, mesure 9. Variance résiduelle initiale 4, puis 1. Ce n’est pas une validation clinique.', 'Scalar Gaussian example: prior mean 5 variance 4, measurement 9. Initial residual variance 4, then 1. This is not clinical validation.'), ['berrah-residual', 'sheiner-forecasting'], [
    n('first', l('Calculez la moyenne posterior avec variance résiduelle 4.', 'Calculate posterior mean with residual variance 4.'), 7, '', l('Précisions égales : (5+9)/2=7.', 'Equal precisions: (5+9)/2=7.')),
    n('second', l('Calculez-la avec variance résiduelle 1.', 'Calculate it with residual variance 1.'), 8.2, '', l('(5/4+9)/(1/4+1)=8,2 : plus proche de la mesure.', '(5/4+9)/(1/4+1)=8.2: closer to the measurement.')),
    r('risk', l('Pourquoi ne pas diminuer systématiquement l’erreur résiduelle ?', 'Why not always reduce residual error?'), [l('Une mesure biaisée ou mal horodatée reçoit plus de poids.', 'A biased or mistimed measurement receives more weight.'), l('Évaluer calibration et performance hors entraînement.', 'Evaluate calibration and held-out performance.')], l('Un levier utile dans un contexte validé n’est pas une règle universelle. L’incertitude ne doit pas être artificiellement minimisée.', 'A useful lever in a validated context is not a universal rule. Uncertainty should not be artificially minimized.'))
  ]),
  ...tools.flatMap(tool => [
    a(`tools-${tool.key}`, l(`Préparer un ajustement ${tool.name}`, `Prepare a ${tool.name} fit`), l('Définir un problème reproductible avant de lancer le logiciel.', 'Define a reproducible problem before running software.'), l('Jeu fictif : 12 patients, chacun avec 1 dose et 3 prélèvements. Les lignes de dose ne sont pas des observations de concentration.', 'Fictional dataset: 12 patients, each with 1 dose and 3 samples. Dose rows are not concentration observations.'), [tool.source], [
      n('rows', l('Combien de lignes d’événement au total ?', 'How many event rows in total?'), 48, 'rows', l('12 × (1+3)=48.', '12 × (1+3)=48.')),
      n('observations', l('Combien de mesures contribuent à la vraisemblance des concentrations ?', 'How many measurements contribute to concentration likelihood?'), 36, 'observations', l('12 × 3=36, en l’absence d’exclusion ou de censure.', '12 × 3=36, without exclusions or censoring.')),
      r('workflow', l('Quels contrôles effectuer avant d’estimer ?', 'What checks should precede estimation?'), [l('ID, doses, unités, temps, voie et codage des mesures.', 'ID, doses, units, times, route and observation coding.'), l('Modèle structural, variabilité, erreur, versions et initialisations.', 'Structure, variability, error, versions and initialization.')], l('Un moteur ne corrige pas automatiquement un jeu mal codé. Documenter le logiciel ne dispense pas de définir les hypothèses.', 'An engine does not automatically correct miscoded data. Documenting the software does not replace defining assumptions.'))
    ], { difficulty: 1 }),
    a(`${tool.key}-modele-structural`, l(`${tool.name} : vérifier les échelles`, `${tool.name}: check scales`), l('Contrôler un fragment avant le modèle complet.', 'Check a fragment before the complete model.'), l('Contrat IV mono-compartimental : CL=5 L/h, V=20 L, bolus=100 mg. Fragments d’illustration seulement, pas des fichiers exécutables complets.', 'One-compartment IV contract: CL=5 L/h, V=20 L, bolus=100 mg. Illustrative fragments only, not complete executable files.'), [tool.source], [
      n('ke', l('Quel ke doit produire le modèle ?', 'What ke should the model produce?'), 0.25, '1/h', l('CL/V=5/20=0,25/h.', 'CL/V=5/20=0.25/h.'), { code: tool.structure }),
      n('initial', l('Quelle concentration immédiatement après bolus ?', 'What concentration immediately after bolus?'), 5, 'mg/L', l('Dose/V=100/20=5.', 'Dose/V=100/20=5.')),
      r('test', l('Pourquoi contrôler la concentration et pas seulement la quantité ?', 'Why check concentration rather than amount alone?'), [l('Le compartiment peut contenir une quantité en mg.', 'The compartment may contain amount in mg.'), l('La division par V et les unités de sortie doivent correspondre aux données.', 'Division by V and output units must match data.')], l('Une erreur d’échelle peut être absorbée par des paramètres. Vérifier C(0+), CL/V et un bilan simple avant un ajustement.', 'A scaling error may be absorbed by parameters. Check C(0+), CL/V and a simple balance before fitting.'))
    ]),
    a(`${tool.key}-variabilite`, l(`${tool.name} : traduire OMEGA`, `${tool.name}: translate OMEGA`), l('Distinguer SD et variance des ETA.', 'Distinguish ETA SD and variance.'), l('CL=5 exp(ETA), ETA normale de moyenne 0 et SD 0,3. L’extrait montre la convention du logiciel ; les autres blocs sont omis.', 'CL=5 exp(ETA), normal ETA with mean 0 and SD 0.3. The excerpt shows the software convention; other blocks are omitted.'), [tool.source, 'savic-karlsson-shrinkage'], [
      n('variance', l('Quelle est la variance de l’ETA ?', 'What is ETA variance?'), 0.09, '', l('0,3²=0,09. NONMEM et la déclaration eta~ de nlmixr2 utilisent ici la variance ; omega dans Monolix est le SD.', '0.3²=0.09. NONMEM and the nlmixr2 eta~ declaration use variance here; Monolix omega is SD.'), { code: tool.variance, tolerance: { kind: 'absolute', value: 0.001 } }),
      n('individual', l('Pour ETA=0,3, calculez CLi.', 'For ETA=0.3, calculate CLi.'), 5 * Math.exp(0.3), 'L/h', l('5 exp(0,3)=6,749 L/h.', '5 exp(0.3)=6.749 L/h.')),
      r('mean', l('La valeur typique 5 est-elle la moyenne arithmétique de CL ?', 'Is the typical value 5 the arithmetic mean of CL?'), [l('Elle est la médiane sous cette distribution lognormale.', 'It is the median under this lognormal distribution.'), l('La moyenne vaut 5 exp(0,09/2).', 'The mean is 5 exp(0.09/2).')], l('La moyenne vaut environ 5,230 L/h. Traduire un modèle nécessite de conserver distribution, corrélations et échelles, pas seulement les nombres.', 'The mean is about 5.230 L/h. Translating a model requires retaining distributions, correlations and scales, not only numbers.'))
    ]),
    a(`${tool.key}-erreur-residuelle`, l(`${tool.name} : coder 20 % d’erreur`, `${tool.name}: encode 20% error`), l('Vérifier la convention résiduelle et la censure.', 'Check residual convention and censoring.'), l('Erreur normale purement proportionnelle, SD relatif=0,2. Les extraits sont partiels ; Monolix indique ici le réglage d’interface, pas du code mlxtran.', 'Purely proportional normal error, relative SD=0.2. Excerpts are partial; Monolix shows the interface setting here, not mlxtran code.'), [tool.source, 'beal-bql'], [
      n('coefficient', l('Quel nombre faut-il dans la déclaration montrée pour représenter ce SD ?', 'What number is needed in the shown declaration to represent this SD?'), tool.coefficient, '', l(tool.key === 'nonmem' ? 'SIGMA stocke une variance : 0,2²=0,04.' : 'Le coefficient montré est un SD proportionnel : 0,2.', tool.key === 'nonmem' ? 'SIGMA stores variance: 0.2²=0.04.' : 'The shown coefficient is proportional SD: 0.2.'), { code: tool.error, tolerance: { kind: 'absolute', value: 0.001 } }),
      n('sd', l('À une prédiction de 10 mg/L, quel SD absolu ?', 'At a 10 mg/L prediction, what absolute SD?'), 2, 'mg/L', l('0,2 × 10=2 mg/L.', '0.2 × 10=2 mg/L.')),
      r('blq', l('Une observation BLQ peut-elle être remplacée automatiquement par zéro ?', 'Can a BLQ observation automatically be replaced with zero?'), [l('BLQ est une information de censure.', 'BLQ is censoring information.'), l('Préciser limite, méthode et support logiciel.', 'Specify limit, method and software support.')], l('Non : cela transforme un intervalle d’information en valeur mesurée. La méthode de traitement doit être justifiée et correctement codée.', 'No: that turns interval information into a measured value. Handling must be justified and correctly encoded.'))
    ]),
    a(`${tool.key}-moteur`, l(`${tool.name} : contrôler la stabilité`, `${tool.name}: check stability`), l('Auditer plusieurs lancements plutôt qu’un succès affiché.', 'Audit multiple runs rather than a success message.'), l('Trois lancements du même problème donnent CL=[5,0 ; 5,1 ; 9,0] L/h. Ne pas mélanger les méthodes de calcul de la vraisemblance pour cette comparaison.', 'Three runs of the same problem give CL=[5.0,5.1,9.0] L/h. Do not mix likelihood evaluation methods for this comparison.'), [tool.source, 'wang-nonmem-methods', 'kuhn-lavielle-saem'], [
      n('spread', l('Quelle est l’étendue max−min des CL ?', 'What is the max−min CL range?'), 4, 'L/h', l('9−5=4 : il faut examiner ce désaccord.', '9−5=4: this disagreement needs investigation.')),
      s('checks', l('Quelles vérifications sont utiles ?', 'Which checks are useful?'), [l('Initialisations, contraintes et convergence.', 'Initializations, constraints and convergence.'), l('Traces, précision, OFV comparable et stabilité numérique.', 'Traces, precision, comparable OFV and numerical stability.'), l('Garder toujours la dernière exécution.', 'Always keep the last run.')], [0, 1], l('Le nom de l’algorithme ne garantit pas un résultat unique ou un maximum global.', 'The algorithm name does not guarantee a unique result or global maximum.')),
      r('report', l('Que rapporter si le désaccord persiste ?', 'What should be reported if disagreement persists?'), [l('Instabilité et configurations exactes, sans masquer un lancement.', 'Instability and exact configurations without hiding a run.'), l('Conséquence sur paramètres et prédictions.', 'Consequences for parameters and predictions.')], l('Une instabilité non résolue limite l’interprétation. Changer de moteur peut aider à diagnostiquer, pas automatiquement valider.', 'Unresolved instability limits interpretation. Changing engines may help diagnosis, not automatically validate.'))
    ]),
    a(`${tool.key}-avance`, l(`${tool.name} : un bootstrap par patient`, `${tool.name}: a patient-level bootstrap`), l('Conserver la structure des données lors du rééchantillonnage.', 'Retain data structure during resampling.'), l('20 patients, chacun avec 6 prélèvements. Bootstrap non paramétrique de sujets : 20 IDs tirés avec remise par réplication, tous leurs enregistrements conservés.', '20 patients, each with 6 samples. Nonparametric subject bootstrap: 20 IDs drawn with replacement per replicate, retaining all their records.'), [tool.source, 'efron-bootstrap'], [
      n('rows', l('Combien de prélèvements par réplication dans ce cas équilibré ?', 'How many samples per replicate in this balanced case?'), 120, 'observations', l('20 × 6=120 ; les copies d’un même patient reçoivent des IDs distincts.', '20 × 6=120; repeated copies of a patient receive distinct IDs.')),
      n('success', l('Sur 200 réplications, 170 convergent. Quel taux de convergence ?', 'Of 200 replicates, 170 converge. What is the convergence rate?'), 85, '%', l('170/200 × 100=85 % ; documenter les 15 % restants.', '170/200 × 100=85%; document the remaining 15%.')),
      r('failures', l('Pourquoi ne pas supprimer silencieusement les échecs ?', 'Why not silently remove failures?'), [l('Les échecs peuvent dépendre des échantillons et paramètres.', 'Failures may depend on samples and parameters.'), l('Rapporter taux, causes et impact sur intervalles.', 'Report rate, causes and impact on intervals.')], l('Un intervalle calculé sur les seuls succès peut être conditionnel à une sélection. Le bootstrap n’efface pas les problèmes de modèle.', 'An interval computed only from successes may be conditional on selection. Bootstrap does not erase model problems.'))
    ])
  ])
];
