// @ts-nocheck
import { l, activity as a, numeric as n, select as s, reflect as r } from '../../learning/activityContent.js';

const synthesis = (track, chapter, title, objective, context, sources, steps, extra = {}) => a(
  chapter,
  title,
  objective,
  context,
  sources,
  steps,
  { id: `synthesis-${track}`, track, kind: 'synthesis', minutes: 25, difficulty: 3, ...extra }
);

export const synthesisActivities = [
  synthesis('start', 'tdm', l('Cas final : deux patients, une même dose', 'Final case: two patients, one dose'), l('Mobiliser CL, V, absorption, variabilité, PD et Bayes dans une seule décision.', 'Combine CL, V, absorption, variability, PD and Bayes in one decision.'), l('Dose orale de 100 mg. A : CL=5 L/h, V=20 L, F=1, Ka=1/h. B : CL=10 L/h, V=40 L, F=1, Ka=1/h. PK linéaire ; aucune cible clinique.', 'Oral dose 100 mg. A: CL=5 L/h, V=20 L, F=1, Ka=1/h. B: CL=10 L/h, V=40 L, F=1, Ka=1/h. Linear PK; no clinical target.'), ['rowland-tozer', 'sheiner-forecasting'], [
    s('predict', l('Avant de calculer, quelles propositions sont vraies ?', 'Before calculating, which statements are true?'), [l("B aura une AUC plus faible.", 'B will have a lower AUC.'), l('B aura nécessairement une réponse deux fois plus faible.', 'B must have half the response.'), l('Les deux patients ont le même rapport CL/V.', 'Both patients have the same CL/V.')], [0, 2], l('Dose/CL détermine ici l’AUC ; CL/V est identique, mais la réponse exige un modèle PD.', 'Dose/CL determines AUC here; CL/V is identical, but response requires a PD model.')),
    n('auc', l('Calculez AUC(B).', 'Calculate AUC(B).'), 10, 'mg.h/L', l('100/10 = 10 mg.h/L.', '100/10 = 10 mg.h/L.')),
    s('noise', l('Une concentration de B dépasse la prédiction. Quelles explications restent possibles ?', 'One concentration for B exceeds prediction. Which explanations remain possible?'), [l('Une variabilité individuelle de CL.', 'Individual CL variability.'), l('Une erreur de prélèvement ou résiduelle.', 'Sampling or residual error.'), l('La dose prouve à elle seule une erreur de modèle.', 'The dose alone proves model error.')], [0, 1], l('Une observation isolée ne sépare pas variabilité, erreur et inadéquation structurale.', 'A single observation cannot separate variability, error and structural misspecification.')),
    r('decision', l('Expliquez ce qu’apporte une estimation MAP avant d’envisager une adaptation.', 'Explain what MAP estimation adds before considering adaptation.'), [l('Combiner prior de population, covariables et observations datées.', 'Combine population prior, covariates and timed observations.'), l('Quantifier l’incertitude et vérifier la transportabilité.', 'Quantify uncertainty and check transportability.')], l('Le MAP individualise les paramètres sous un modèle explicite ; il ne valide ni la cible, ni la sécurité, ni la causalité de la réponse.', 'MAP individualises parameters under an explicit model; it validates neither target, safety nor response causality.'))
  ]),
  synthesis('math', 'math-covariates', l('Cas de synthèse : équation, vraisemblance et incertitude', 'Synthesis case: equation, likelihood and uncertainty'), l('Passer d’une EDO à une estimation interprétable.', 'Move from an ODE to an interpretable estimate.'), l('Bolus IV : dA/dt=-kA, dose 100 mg, V=20 L. Deux concentrations sans erreur : C(0)=5 et C(4)=2,247 mg/L.', 'IV bolus: dA/dt=-kA, dose 100 mg, V=20 L. Two error-free concentrations: C(0)=5 and C(4)=2.247 mg/L.'), ['davidian-giltinan'], [
    n('k', l('Calculez k à partir de C(4)/C(0).', 'Calculate k from C(4)/C(0).'), 0.2, '1/h', l('k=-ln(2,247/5)/4 ≈ 0,2/h.', 'k=-ln(2.247/5)/4 ≈ 0.2/h.')),
    n('cl', l('Déduisez CL.', 'Derive CL.'), 4, 'L/h', l('CL=kV=0,2×20=4 L/h.', 'CL=kV=0.2×20=4 L/h.')),
    s('uncertainty', l('Que faut-il ajouter pour obtenir un intervalle d’incertitude défendable ?', 'What is needed for a defensible uncertainty interval?'), [l('Un modèle d’erreur.', 'An error model.'), l('Un plan d’échantillonnage et une vraisemblance.', 'A sampling design and likelihood.'), l('Seulement davantage de décimales.', 'Only more decimal places.')], [0, 1], l('La précision numérique n’est pas l’incertitude statistique.', 'Numerical precision is not statistical uncertainty.')),
    r('limits', l('Pourquoi N-P n’est-il pas un diagnostic suffisant ici ?', 'Why is N-P not a sufficient diagnostic here?'), [l('Les observations peuvent être corrélées.', 'Observations may be correlated.'), l('Non-linéarité, effets aléatoires et frontières modifient les conditions usuelles.', 'Nonlinearity, random effects and boundaries alter usual conditions.')], l('Les degrés de liberté des modèles mixtes ne se résument pas toujours à un simple comptage.', 'Degrees of freedom in mixed models do not always reduce to simple counting.'))
  ]),
  synthesis('nca', 'nca-absorption', l('Cas de synthèse NCA : de la courbe à la biodisponibilité', 'NCA synthesis: from curve to bioavailability'), l('Calculer puis juger si le dessin permet l’interprétation.', 'Calculate, then judge whether the design supports interpretation.'), l('Même sujet : IV 100 mg, AUC=20 mg.h/L ; oral 200 mg, AUC=30 mg.h/L. Dernier prélèvement oral alors que la concentration reste à 20 % du Cmax.', 'Same subject: IV 100 mg, AUC=20 mg.h/L; oral 200 mg, AUC=30 mg.h/L. Last oral sample while concentration remains at 20% of Cmax.'), ['yamaoka-moments'], [
    n('f', l('Calculez la biodisponibilité absolue.', 'Calculate absolute bioavailability.'), 0.75, '', l('(30/200)/(20/100)=0,75.', '(30/200)/(20/100)=0.75.')),
    s('terminal', l('Quelle réserve est prioritaire ?', 'Which caveat is the priority?'), [l('La phase terminale orale peut être insuffisamment décrite.', 'The oral terminal phase may be insufficiently described.'), l('F doit nécessairement être supérieur à 1.', 'F must necessarily exceed 1.')], [0], l('Une AUC extrapolée importante fragilise F, t1/2 et les paramètres dérivés.', 'Substantial AUC extrapolation weakens F, t1/2 and derived parameters.')),
    r('be', l('Que comparerait une analyse de bioéquivalence ?', 'What would a bioequivalence analysis compare?'), [l('IC90% du ratio test/référence des moyennes géométriques.', '90% CI for the test/reference ratio of geometric means.'), l('AUC et Cmax après transformation log, avec limites applicables.', 'AUC and Cmax after log transformation, with applicable limits.')], l('Une simple comparaison de deux valeurs individuelles ne constitue pas une étude de bioéquivalence.', 'A simple comparison of two individual values is not a bioequivalence study.'))
  ]),
  synthesis('pbpk', 'pbpk-applications', l('Cas de synthèse PBPK : extrapoler sans surpromettre', 'PBPK synthesis: extrapolate without overclaiming'), l('Tracer la chaîne hypothèse-paramètre-prédiction-validation.', 'Trace the assumption-parameter-prediction-validation chain.'), l('Un modèle prédit une AUC doublée en insuffisance hépatique après modification de fu et de la clairance intrinsèque.', 'A model predicts doubled AUC in hepatic impairment after changing fu and intrinsic clearance.'), ['jones-rowland-yeo'], [
    s('mechanism', l('Quelles entrées doivent être distinguées ?', 'Which inputs must be distinguished?'), [l('Liaison protéique.', 'Protein binding.'), l('Débit hépatique et clairance intrinsèque.', 'Hepatic blood flow and intrinsic clearance.'), l('La couleur du schéma.', 'Diagram colour.')], [0, 1], l('Le mécanisme dépend du régime d’extraction et des hypothèses de distribution.', 'The mechanism depends on extraction regime and distribution assumptions.')),
    r('free', l('Une hausse de fu prouve-t-elle une hausse durable de l’exposition libre ?', 'Does increased fu prove a sustained increase in unbound exposure?'), [l('Non : clairance et distribution peuvent aussi changer.', 'No: clearance and distribution may also change.'), l('Préciser dose, voie et état stationnaire.', 'Specify dose, route and steady state.')], l('La théorie de la fraction libre ne permet pas une conclusion absolue sans le modèle complet.', 'Free-fraction theory does not support an absolute conclusion without the full model.')),
    s('validate', l('Que faut-il confronter aux données ?', 'What should be confronted with data?'), [l('Concentrations totales et libres si disponibles.', 'Total and unbound concentrations if available.'), l('Prédictions dans la population cible.', 'Predictions in the target population.'), l('Uniquement le bilan de masse interne.', 'Only internal mass balance.')], [0, 1], l('La cohérence interne ne remplace pas l’évaluation externe ou clinique.', 'Internal consistency does not replace external or clinical evaluation.'))
  ]),
  synthesis('pd', 'pd-survival', l('Cas de synthèse PD : même exposition, réponses différentes', 'PD synthesis: same exposure, different responses'), l('Distinguer effet direct, retard, turnover et événement.', 'Distinguish direct effect, delay, turnover and event.'), l('Après une dose, C(t) culmine à 2 h, un biomarqueur à 8 h et un événement est suivi sur 6 mois.', 'After a dose, C(t) peaks at 2 h, a biomarker at 8 h and an event is followed for 6 months.'), ['holford-sheiner-dose-effect'], [
    s('delay', l('Quels modèles peuvent expliquer le retard du biomarqueur ?', 'Which models may explain the biomarker delay?'), [l('Compartiment d’effet.', 'Effect compartment.'), l('Réponse indirecte.', 'Indirect response.'), l('Effet direct instantané uniquement.', 'Instantaneous direct effect only.')], [0, 1], l('Le dessin et la biologie doivent départager ces structures.', 'Design and biology must distinguish these structures.')),
    r('survival', l('Une covariable biomarqueur dépendante du temps est-elle automatiquement un modèle joint ?', 'Is a time-varying biomarker covariate automatically a joint model?'), [l('Non : un modèle joint spécifie conjointement longitudinal et événement.', 'No: a joint model jointly specifies the longitudinal and event processes.'), l('Décrire le mécanisme de liaison et l’incertitude.', 'Describe the linking mechanism and uncertainty.')], l('Une association exposition-réponse-survie reste conditionnelle au modèle et ne prouve pas un effet causal de dose.', 'An exposure-response-survival association remains model-conditional and does not prove a causal dose effect.')),
    s('choice', l('Quel diagnostic est indispensable ?', 'Which diagnostic is essential?'), [l('Adéquation temporelle de la PK et de la PD.', 'Temporal adequacy of PK and PD.'), l('Prédiction des événements et calibration.', 'Event prediction and calibration.'), l('Seulement l’AIC.', 'AIC only.')], [0, 1], l('Chaque sous-modèle et leur liaison doivent être évalués.', 'Each submodel and their link must be evaluated.'))
  ]),
  synthesis('covariates', 'covariates-implementation', l('Cas de synthèse covariables : relation ou extrapolation ?', 'Covariate synthesis: relationship or extrapolation?'), l('Choisir, coder et borner une relation covariable-paramètre.', 'Choose, code and bound a covariate-parameter relationship.'), l('CL=5×(DFG/90)^0,8×exp(ETA), estimé chez des adultes avec DFG 30–120 mL/min/1,73 m2.', 'CL=5×(GFR/90)^0.8×exp(ETA), estimated in adults with GFR 30–120 mL/min/1.73 m2.'), ['anderson-holford-allometry'], [
    n('cl', l('Calculez CL typique pour DFG=45.', 'Calculate typical CL for GFR=45.'), 5 * 0.5 ** 0.8, 'L/h', l('5×0,5^0,8 ≈ 2,872 L/h.', '5×0.5^0.8 ≈ 2.872 L/h.')),
    s('eta', l('Que représente ETA après ajout de la covariable ?', 'What does ETA represent after adding the covariate?'), [l('La variabilité interindividuelle restante.', 'Remaining between-subject variability.'), l('Le DFG lui-même.', 'GFR itself.')], [0], l('L’effet fixe du DFG et l’écart individuel résiduel sont distincts.', 'The fixed GFR effect and remaining individual deviation are distinct.')),
    r('outside', l('Que conclure pour DFG=10 ?', 'What should be concluded for GFR=10?'), [l('Le calcul est possible mais hors plage étudiée.', 'The calculation is possible but outside the studied range.'), l('Physiologie, population et validation externe doivent être revues.', 'Physiology, population and external validation must be reviewed.')], l('Une formule de covariable décrit d’abord la plage qui l’a informée ; elle n’autorise pas silencieusement l’extrapolation.', 'A covariate equation first describes the range that informed it; it does not silently authorise extrapolation.'))
  ]),
  synthesis('onco', 'onco-models', l('Cas de synthèse oncologie : tumeur, résistance et décision', 'Oncology synthesis: tumour, resistance and decision'), l('Séparer prédiction tumorale, toxicité et inférence causale.', 'Separate tumour prediction, toxicity and causal inference.'), l('Un modèle TGI prédit une réduction précoce puis une repousse par résistance ; un modèle myélosuppression prédit un nadir au jour 10.', 'A TGI model predicts early shrinkage then resistant regrowth; a myelosuppression model predicts a nadir on day 10.'), ['claret-tgi-os', 'friberg'], [
    s('dose', l('Augmenter la dose garantit-il une meilleure survie ?', 'Does increasing dose guarantee better survival?'), [l('Non.', 'No.'), l('Oui, si la tumeur diminue dans le modèle.', 'Yes, if the tumour shrinks in the model.')], [0], l('Le résultat est une prédiction conditionnelle ; toxicité, résistance, sélection et causalité restent à établir.', 'The result is conditional prediction; toxicity, resistance, selection and causality remain to be established.')),
    r('joint', l('Quels éléments doivent être évalués ensemble ?', 'Which elements should be evaluated together?'), [l('Croissance sans traitement et effet du traitement.', 'Untreated growth and treatment effect.'), l('Sous-populations sensibles/résistantes et toxicité.', 'Sensitive/resistant subpopulations and toxicity.')], l('Une dose est un compromis multi-objectifs, pas seulement une courbe tumorale.', 'A dose is a multi-objective compromise, not only a tumour curve.')),
    s('data', l('Quelles données renforceraient le modèle ?', 'Which data would strengthen the model?'), [l('Mesures longitudinales de tumeur.', 'Longitudinal tumour measurements.'), l('Historique des doses et interruptions.', 'Dose and interruption history.'), l('Temps d’événement et censure.', 'Event times and censoring.'), l('Uniquement la dernière taille tumorale.', 'Only the last tumour size.')], [0, 1, 2], l('La chronologie complète est nécessaire pour relier exposition, réponse et événement.', 'Complete chronology is needed to link exposure, response and event.'))
  ]),
  synthesis('infectio', 'infectio-tdm', l('Cas de synthèse infectiologie : profil, CMI et PTA', 'Infectious-disease synthesis: profile, MIC and PTA'), l('Distinguer indice individuel et probabilité populationnelle.', 'Distinguish an individual index from a population probability.'), l('Quatre AUC24 libres simulées : 80, 100, 120, 160 mg.h/L ; CMI=1 mg/L ; cible pédagogique fAUC24/CMI>=100.', 'Four simulated unbound AUC24 values: 80, 100, 120, 160 mg.h/L; MIC=1 mg/L; teaching target fAUC24/MIC>=100.'), ['craig-pkpd'], [
    n('pta', l('Calculez la PTA empirique, bornes incluses.', 'Calculate empirical PTA, inclusive bounds.'), 75, '%', l('Trois profils sur quatre atteignent 100.', 'Three of four profiles reach 100.')),
    n('mic', l('Avec CMI=2, quelle PTA obtient-on ?', 'With MIC=2, what PTA results?'), 0, '%', l('Aucun profil n’atteint fAUC24>=200.', 'No profile reaches fAUC24>=200.')),
    r('interpret', l('Pourquoi ce résultat n’est-il pas une recommandation ?', 'Why is this result not a recommendation?'), [l('Petit échantillon et cible fictive.', 'Small sample and fictional target.'), l('Dépendance au modèle, à la population, à la fraction libre et à la CMI.', 'Dependence on model, population, free fraction and MIC.')], l('La PTA est conditionnelle à toutes ces hypothèses et doit intégrer efficacité et toxicité.', 'PTA is conditional on all these assumptions and must integrate efficacy and toxicity.'))
  ]),
  synthesis('mab', 'mab-ada', l('Cas de synthèse anticorps : TMDD et ADA', 'Antibody synthesis: TMDD and ADA'), l('Interpréter une PK non linéaire sans mécanisme déterministe.', 'Interpret nonlinear PK without deterministic mechanism claims.'), l('À faible dose, la clairance apparente diminue quand la dose augmente. Des ADA sont détectés chez certains patients.', 'At low dose, apparent clearance decreases as dose increases. ADA are detected in some patients.'), ['mager-jusko-tmdd', 'ryman-meibohm'], [
    s('tmdd', l('Quelle hypothèse est compatible avec la non-linéarité ?', 'Which hypothesis is compatible with nonlinearity?'), [l('Une élimination médiée par la cible saturable.', 'Saturable target-mediated elimination.'), l('Une clairance linéaire constante uniquement.', 'Constant linear clearance only.')], [0], l('Compatible ne signifie pas démontrée : d’autres structures peuvent mimer cette forme.', 'Compatible does not mean proven: other structures can mimic this shape.')),
    r('ada', l('La présence d’ADA impose-t-elle CL↑ et exposition↓ ?', 'Does ADA presence force CL up and exposure down?'), [l('Non : titre, persistance, neutralisation, complexes et assay comptent.', 'No: titre, persistence, neutralisation, complexes and assay matter.'), l('L’effet dépend aussi de la molécule.', 'The effect also depends on the molecule.')], l('Les ADA peuvent affecter la PK, mais l’association n’est pas un mécanisme déterministe universel.', 'ADA may affect PK, but the association is not a universal deterministic mechanism.')),
    s('measure', l('Quelles mesures aideraient ?', 'Which measurements would help?'), [l('Médicament libre/total selon le contexte.', 'Free/total drug as relevant.'), l('Cible et complexes.', 'Target and complexes.'), l('Chronologie et titre des ADA.', 'ADA timing and titre.'), l('La seule présence ADA, sans information analytique.', 'ADA presence alone, without analytical information.')], [0, 1, 2], l('La temporalité et les méthodes analytiques sont essentielles.', 'Timing and analytical methods are essential.'))
  ]),
  synthesis('ai', 'ai-llm', l('Cas de synthèse IA : gain apparent ou modèle transportable ?', 'AI synthesis: apparent gain or transportable model?'), l('Comparer performance, validation et interprétation.', 'Compare performance, validation and interpretation.'), l('Un XGBoost réduit le RMSE de 20 à 14% en validation interne, avec prélèvements C0+C1 simulés par le même modèle PK.', 'XGBoost reduces RMSE from 20 to 14% in internal validation, with C0+C1 samples simulated from the same PK model.'), ['hastie-esl'], [
    n('gain', l('Calculez la réduction relative du RMSE.', 'Calculate relative RMSE reduction.'), 30, '%', l('(20-14)/20=30%.', '(20-14)/20=30%.')),
    s('claims', l('Quelles conclusions sont défendables ?', 'Which conclusions are defensible?'), [l('Gain conditionnel au générateur et au dessin.', 'Gain conditional on generator and design.'), l('Bénéfice clinique démontré.', 'Proven clinical benefit.'), l('Validation externe encore nécessaire.', 'External validation still needed.')], [0, 2], l('Une validation interne simulée ne démontre ni transportabilité ni utilité clinique.', 'Internal simulated validation demonstrates neither transportability nor clinical utility.')),
    r('explain', l('Que doit accompagner une explication locale ?', 'What should accompany a local explanation?'), [l('Domaine d’entraînement et incertitude.', 'Training domain and uncertainty.'), l('Comparaison au MAP et contrôles négatifs.', 'Comparison with MAP and negative controls.')], l('Une importance de variable ou une explication locale ne transforme pas une association en mécanisme.', 'Feature importance or local explanation does not turn association into mechanism.'))
  ]),
  synthesis('valid', 'valid-interpretation', l('Cas de synthèse validation : bon AIC, mauvais VPC', 'Validation synthesis: good AIC, poor VPC'), l('Décider à partir d’un faisceau de diagnostics.', 'Decide from a body of diagnostics.'), l('Le modèle B diminue AIC de 12 points, converge, mais sous-prédit la variabilité tardive dans la VPC et son omega ajouté a un RSE de 80%.', 'Model B lowers AIC by 12 points and converges, but underpredicts late variability in the VPC and its added omega has 80% RSE.'), ['bergstrand-pcvpc', 'savic-karlsson-shrinkage'], [
    s('retain', l('Peut-on retenir B uniquement parce que son AIC est plus bas ?', 'Can B be retained only because its AIC is lower?'), [l('Non.', 'No.'), l('Oui, le plus bas gagne toujours.', 'Yes, lowest always wins.')], [0], l('Convergence, précision, diagnostics prédictifs et plausibilité doivent être cohérents.', 'Convergence, precision, predictive diagnostics and plausibility must be coherent.')),
    r('rse', l('Que démontre surtout le RSE élevé ?', 'What does high RSE primarily show?'), [l('Une faible précision de l’estimation.', 'Low estimation precision.'), l('Pas, à lui seul, une non-identifiabilité prouvée.', 'Not, by itself, proven non-identifiability.')], l('L’identifiabilité est un concept plus fort que l’imprécision.', 'Identifiability is a stronger concept than imprecision.')),
    s('next', l('Quelles actions sont raisonnables ?', 'Which actions are reasonable?'), [l('Vérifier structure et modèle d’erreur.', 'Check structure and error model.'), l('Stratifier la VPC et vérifier le dessin simulé.', 'Stratify VPC and verify simulation design.'), l('Ignorer la VPC.', 'Ignore the VPC.')], [0, 1], l('Un diagnostic indique où enquêter ; il ne donne pas une correction unique.', 'A diagnostic indicates where to investigate; it does not provide a unique correction.'))
  ]),
  synthesis('trials', 'trials-interpretation', l('Cas de synthèse essais : operating characteristic ou PoS ?', 'Trial synthesis: operating characteristic or PoS?'), l('Relier scénarios, incertitude et décision.', 'Link scenarios, uncertainty and decision.'), l('Sous un effet fixé, 820 essais simulés sur 1000 sont positifs. Un second calcul tire l’effet dans une distribution d’incertitude.', 'Under a fixed effect, 820 of 1000 simulated trials are positive. A second calculation draws the effect from an uncertainty distribution.'), ['bretz-mcp-mod'], [
    n('power', l('Calculez la fréquence conditionnelle de succès du premier calcul.', 'Calculate conditional success frequency in the first calculation.'), 82, '%', l('820/1000=82% : operating characteristic ou puissance conditionnelle au scénario.', '820/1000=82%: operating characteristic or power conditional on the scenario.')),
    s('pos', l('Quel calcul peut être appelé assurance/PoS ?', 'Which calculation may be called assurance/PoS?'), [l('Celui qui intègre l’incertitude pertinente sur l’effet.', 'The one integrating relevant effect uncertainty.'), l('Toute fréquence sous paramètres fixés.', 'Any frequency under fixed parameters.')], [0], l('Les termes dépendent du cadre probabiliste effectivement simulé.', 'Terms depend on the probabilistic framework actually simulated.')),
    r('adaptive', l('Un design adaptatif utilise-t-il toujours moins de patients ?', 'Does an adaptive design always use fewer patients?'), [l('Non : il peut améliorer l’efficacité sous certaines hypothèses.', 'No: it may improve efficiency under some assumptions.'), l('Il peut aussi accroître taille maximale et complexité opérationnelle.', 'It may also increase maximum size and operational complexity.')], l('Les règles d’adaptation doivent être préspécifiées et évaluées par simulation.', 'Adaptation rules must be prespecified and evaluated by simulation.'))
  ]),
  synthesis('tools', 'tools-mipd', l('Cas de synthèse outils : reproduire une analyse', 'Tools synthesis: reproduce an analysis'), l('Identifier tout ce qu’un fichier de modèle ne contient pas.', 'Identify everything a model file does not contain.'), l('On vous transmet un code structural mrgsolve et deux concentrations, mais ni OMEGA, ni SIGMA, ni historique complet des doses.', 'You receive structural mrgsolve code and two concentrations, but no OMEGA, SIGMA or complete dose history.'), ['mapbayr'], [
    s('missing', l('Que manque-t-il pour un ajustement MAP reproductible ?', 'What is missing for a reproducible MAP fit?'), [l('Distribution a priori OMEGA.', 'OMEGA prior distribution.'), l('Erreur résiduelle SIGMA.', 'SIGMA residual error.'), l('Doses, temps, unités et compartiments.', 'Doses, times, units and compartments.'), l('Une couleur de courbe imposée.', 'A prescribed curve colour.')], [0, 1, 2], l('La structure seule ne définit ni le prior, ni la vraisemblance, ni les données.', 'Structure alone defines neither prior, likelihood nor data.')),
    r('software', l('Changer de logiciel doit-il changer la question scientifique ?', 'Should changing software change the scientific question?'), [l('Non : structure, données, unités et hypothèses doivent rester traçables.', 'No: structure, data, units and assumptions must remain traceable.'), l('Comparer les paramétrisations avant les sorties numériques.', 'Compare parameterisations before numerical outputs.')], l('Des syntaxes différentes peuvent représenter le même modèle, ou masquer une différence de variance, transformation ou échelle.', 'Different syntaxes may represent the same model, or hide differences in variance, transformation or scale.')),
    s('report', l('Que faut-il exporter avec le résultat ?', 'What should be exported with the result?'), [l('Code et version des dépendances.', 'Code and dependency versions.'), l('Données ou scénario synthétique.', 'Data or synthetic scenario.'), l('Hypothèses, contrôles et diagnostics.', 'Assumptions, checks and diagnostics.'), l('Seulement une capture d’écran.', 'Only a screenshot.')], [0, 1, 2], l('Un résultat sans provenance n’est pas reproductible.', 'A result without provenance is not reproducible.'))
  ])
];
