arguments <- commandArgs(trailingOnly = FALSE)
path <- sub("^--file=", "", grep("^--file=", arguments, value = TRUE)[1])
APP_ROOT <- normalizePath(file.path(dirname(path), ".."), winslash = "/")
setwd(APP_ROOT)
environment <- new.env(parent = globalenv())
sys.source(file.path(APP_ROOT, "app.R"), envir = environment)
shiny::testServer(environment$onco_server, args = list(report_plot_uri = function(plot) ""), {
  session$setInputs(growth = "exponential", toxicity = TRUE, decision = 42, horizon = 84, dose = 100, interval = 21, infusion = 1,
    history = "time,amount,infusion\n0,100,1\n21,100,1", fraction = 75, delay = 7, new_interval = 21, anc_floor = 1, tumor_goal = 0.8)
  session$setInputs(compare = 1)
  stopifnot(!is.null(comparison()), length(output$metrics) > 0, length(output$tumor_plot) > 0, length(output$anc_plot) > 0)
  session$setInputs(fraction = 50)
  stopifnot(is.null(comparison()))
  session$setInputs(compare = 2)
  stopifnot(!is.null(comparison()))
  session$setInputs(KG = 0.02)
  stopifnot(is.null(comparison()), is.null(fit_store()))
  session$setInputs(accept = FALSE, observations = "time,endpoint,value\n0,tumor,60\n14,tumor,52\n28,tumor,46\n42,tumor,44", estimate = "KILL", fit = 1)
  stopifnot(is.null(fit_store()))
})
cat("Oncology Shiny: rendered curves, metrics, invalidation and fitting acknowledgement passed.\n")
import_store <- shiny::reactiveVal(NULL)
shiny::testServer(environment$onco_server, args = list(report_plot_uri = function(plot) "", imported = import_store), {
  session$setInputs(growth = "gompertz", toxicity = TRUE, history = "time,amount,infusion\n0,100,1\n21,100,1")
  config <- environment$onco_config(list(growth = "gompertz", parameters = list(T0 = 75, CAP = 280)))
  import_store(list(id = "test-import", view = "onco", config = config))
  session$flushReact()
  # No numeric parameter inputs are mounted: opening an accordion must not be required.
  stopifnot(configuration()$parameters$T0 == 75, configuration()$parameters$CAP == 280)
})
cat("Oncology workshop import preserves parameters before opening the parameter panel.\n")
