arguments <- commandArgs(trailingOnly = FALSE)
file_argument <- sub("^--file=", "", grep("^--file=", arguments, value = TRUE)[1])
APP_ROOT <- normalizePath(file.path(dirname(file_argument), ".."), winslash = "/", mustWork = TRUE)
setwd(APP_ROOT)
environment <- new.env(parent = globalenv())
sys.source(file.path(APP_ROOT, "app.R"), envir = environment)
store <- shiny::reactiveVal(NULL)
shiny::testServer(environment$pd_server, args = list(analysis_store = store, report_plot_uri = function(plot) ""), {
  session$setInputs(type = "linear", delay = FALSE, exposure = "exponential", horizon = 24, c0 = 10, kel = 0.1,
    E0 = 12, SLOPE = 3, data_mode = "concentration", estimate = c("E0", "SLOPE"), accept = TRUE,
    observations = "concentration,effect\n0,10\n1,12\n2,14\n3,16\n4,18\n5,20")
  observations$replace(data.frame(concentration = 0:5, effect = seq(10, 20, by = 2)))
  session$flushReact()
  session$setInputs(fit = 1)
  stopifnot(!is.null(fit_store()), fit_store()$rmse < 1e-8)
  stopifnot(length(output$fit_parameters) > 0, length(output$fit_data) > 0, length(output$fit_plot) > 0)
  session$setInputs(SLOPE = 4)
  stopifnot(is.null(fit_store()))
  session$setInputs(delay = TRUE, fit = 2)
  stopifnot(is.null(fit_store()))
  session$setInputs(delay = FALSE, accept = FALSE, fit = 3)
  stopifnot(is.null(fit_store()))
})
cat("PD Shiny fitting, stale-result invalidation and guards passed.\n")

columns <- shiny::reactiveVal(c("time", "effect"))
shiny::testServer(environment$pd_observations_server, args = list(columns = columns, initial = data.frame(time = 0:2, effect = 10:12)), {
  session$setInputs(table_cell_edit = list(row = 1, col = 1, value = "145"))
  stopifnot(rows()$effect[1] == 145)
  session$setInputs(table_cell_edit = list(row = 1, col = 0, value = "-1"))
  stopifnot(rows()$time[1] == 0, revision() == 1L)
  session$setInputs(table_cell_edit = list(row = 1, col = 1, value = "not numeric"))
  stopifnot(rows()$effect[1] == 145, revision() == 2L)
  session$setInputs(add = 1)
  stopifnot(nrow(rows()) == 4, is.na(rows()$effect[4]))
  session$setInputs(table_rows_selected = 4, remove = 1)
  stopifnot(nrow(rows()) == 3)
  columns(c("concentration", "effect")); session$flushReact()
  replace(data.frame(concentration = 1:2, effect = 20:21))
  columns(c("time", "effect")); session$flushReact()
  stopifnot(nrow(rows()) == 3, rows()$effect[1] == 145)
})
cat("Observation edits, invalid-value rollback, blank rows and separate data modes passed.\n")
