import { access, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getSiteOrigin, SITE_ORIGIN_TOKEN } from '../site.config.js';

const textExtensions = new Set(['.html', '.xml', '.txt', '.json', '.js']);

// Both sitemaps are generated by this repository; loc values are absolute URLs.
// The separate Internat/Stats deployments are listed in the index, not checked locally.
async function validateSitemap(file, target, origin) {
  const xml = await readFile(file, 'utf8');
  const locations = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)];
  if (!locations.length) throw new Error(`Empty sitemap: ${file}`);
  for (const [, location] of locations) {
    const url = new URL(location);
    if (url.origin !== origin) {
      throw new Error(`Origin mismatch in ${file}: ${url.origin}; rebuild with PUBLIC_SITE_ORIGIN=${origin}`);
    }
    const pathname = decodeURIComponent(url.pathname);
    const destination = path.resolve(target, '.' + pathname, pathname.endsWith('/') ? 'index.html' : '');
    if (!destination.startsWith(target + path.sep)) throw new Error(`Invalid sitemap path: ${pathname}`);
    await access(destination);
  }
}

export async function configureSiteOrigin(directory, origin = getSiteOrigin()) {
  const target = path.resolve(directory);
  const sources = path.resolve('portal');
  if (target === sources || sources.startsWith(target + path.sep) || target.startsWith(sources + path.sep)) {
    throw new Error('Configure an assembled output directory, never the portal sources.');
  }
  async function configure(folder) {
    for (const entry of await readdir(folder, { withFileTypes: true })) {
      // SvelteKit embeds its own origin. Never rewrite models or compiled application code.
      if (folder === target && entry.name === 'pharmacometrie') continue;
      const file = path.join(folder, entry.name);
      if (entry.isDirectory()) { await configure(file); continue; }
      if (!textExtensions.has(path.extname(file))) continue;
      const source = await readFile(file, 'utf8');
      if (source.includes(SITE_ORIGIN_TOKEN))
        await writeFile(file, source.replaceAll(SITE_ORIGIN_TOKEN, origin));
    }
  }
  await configure(target);
  await mkdir(path.join(target, 'assets'), { recursive: true });
  await writeFile(path.join(target, 'assets/site-origin.js'),
    `// Generated from PUBLIC_SITE_ORIGIN.\nexport const SITE_ORIGIN = ${JSON.stringify(origin)};\n`);
  for (const sitemap of ['sitemap.xml', 'pharmacometrie/sitemap.xml']) {
    const file = path.join(target, sitemap);
    try { await access(file); } catch (error) {
      if (error.code === 'ENOENT') continue;
      throw error;
    }
    await validateSitemap(file, target, origin);
  }
  console.log(`Public site origin: ${origin}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await configureSiteOrigin(process.argv[2] || 'dist');
}
