import assert from 'node:assert/strict';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import matter from 'gray-matter';
import { exercises } from '../src/lib/content/exercises.js';
import { guidedActivities } from '../src/lib/content/guidedActivities.js';
import { learningTracks, beginnerTrack } from '../src/lib/content/tracks.js';
import { molecularLabIds } from '../src/lib/labs/molecular.js';
import { glossaryDetails, glossaryEnglish } from '../src/lib/content/glossaryMeta.js';

const root = new URL('../', import.meta.url);
const chapterDir = new URL('src/content/chapters/', root);
const englishDir = new URL('src/content/chapters/en/', root);
const visualizationDir = new URL('src/lib/components/visualizations/', root);
const output = new URL('docs/content-inventory.md', root);
const citation = readFileSync(new URL('CITATION.cff', root), 'utf8');
const contentLicense = readFileSync(new URL('LICENSE-CONTENT.md', root), 'utf8');
const portalHome = readFileSync(new URL('portal/index.html', root), 'utf8');
const chapterFiles = readdirSync(chapterDir).filter(file => file.endsWith('.md') && !file.startsWith('_'));
const chapters = chapterFiles.map(file => ({ file, ...matter(readFileSync(new URL(file, chapterDir), 'utf8')).data }));
const englishFiles = readdirSync(englishDir).filter(file => file.endsWith('.md') && !file.startsWith('_'));
const visualizations = readdirSync(visualizationDir).filter(file => file.endsWith('.svelte'));
const vizKeys = new Set(chapterFiles.flatMap(file => [...readFileSync(new URL(file, chapterDir), 'utf8').matchAll(/\bviz="([^"]+)"/g)].map(match => match[1])));
const syntheses = guidedActivities.filter(activity => activity.kind === 'synthesis');
const guided = guidedActivities.filter(activity => activity.kind !== 'synthesis');
const pendingReviews = chapters.filter(chapter => chapter.updated_on && chapter.reviewed_on && chapter.updated_on > chapter.reviewed_on);
const rows = [
  ['French chapters', chapters.length],
  ['English chapter translations', englishFiles.length],
  ['Learning tracks, including starter path', learningTracks.length],
  ['Starter-path chapters', beginnerTrack.chapterSlugs.length],
  ['Chapter quiz questions', chapters.reduce((sum, chapter) => sum + (chapter.quiz?.length ?? 0), 0)],
  ['Short numerical exercises', exercises.length],
  ['Guided activities', guided.length],
  ['Synthesis cases', syntheses.length],
  ['Guided and synthesis steps', guidedActivities.reduce((sum, activity) => sum + activity.steps.length, 0)],
  ['Animated laboratories', 4 + molecularLabIds.length],
  ['Visualization components', visualizations.length],
  ['Visualization keys used by chapters', vizKeys.size],
  ['Glossary terms', Object.keys(glossaryEnglish).length],
  ['Rich glossary entries', Object.keys(glossaryDetails).length],
  ['Chapters with explicit prerequisites metadata', chapters.filter(chapter => Array.isArray(chapter.prerequisites)).length],
  ['Chapters with prerequisites', chapters.filter(chapter => chapter.prerequisites?.length).length],
  ['Chapters with explicit glossary metadata', chapters.filter(chapter => Array.isArray(chapter.glossary)).length],
  ['Chapters with glossary links', chapters.filter(chapter => chapter.glossary?.length).length],
  ['Chapters with source identifiers', chapters.filter(chapter => chapter.sources?.length).length],
  ['Chapters with a scientific review date', chapters.filter(chapter => chapter.reviewed_on).length],
  ['Chapters pending scientific review', pendingReviews.length]
];

assert.equal(new Set(chapters.map(chapter => chapter.slug)).size, chapters.length, 'Duplicate chapter slug');
assert.equal(beginnerTrack.chapterSlugs.length, 12, 'Starter path must keep twelve steps');
assert.equal(syntheses.length, 13, 'One synthesis case is required for each major learning path');
assert.equal(chapters.filter(chapter => Array.isArray(chapter.prerequisites)).length, chapters.length, 'Every chapter must declare prerequisites metadata');
assert.equal(chapters.filter(chapter => Array.isArray(chapter.glossary)).length, chapters.length, 'Every chapter must declare glossary metadata');
assert.match(citation, new RegExp(`${chapters.length} chapitres\\s+en français, ${englishFiles.length} chapitres traduits en anglais et ${visualizations.length} visualisations`), 'CITATION.cff public counts are stale');
assert.match(contentLicense, new RegExp(`${chapters.length} chapitres en français, ${englishFiles.length} chapitres en anglais, ${visualizations.length} visualisations`), 'LICENSE-CONTENT.md public counts are stale');
assert.ok(citation.includes('title: "PMx Explain"') && contentLicense.includes('**PMx Explain**'), 'Public citation and licence branding must use PMx Explain');
assert.ok(portalHome.includes(`${learningTracks.length - 1} specialised tracks plus a guided starter path`), 'Portal learning-track count is stale');

const markdown = `# PMx Explain content inventory

This file is generated by \`npm run inventory\`. Do not edit counts manually.

| Content | Current count |
| --- | ---: |
${rows.map(([label, count]) => `| ${label} | ${count} |`).join('\n')}

## Source of truth

- Chapters and metadata: \`src/content/chapters/\`
- English translations: \`src/content/chapters/en/\`
- Exercises and activities: \`src/lib/content/\`
- Laboratories: \`src/lib/labs/\`
- Visualizations: \`src/lib/components/visualizations/\`

The counts describe repository content. They do not certify scientific validity,
clinical suitability, translation quality or learning effectiveness.

## Scientific review debt

${pendingReviews.length
  ? `| Chapter | Track | Level | Updated | Last review |\n| --- | --- | --- | --- | --- |\n${pendingReviews.map(chapter => `| ${chapter.slug} | ${chapter.track} | ${chapter.level} | ${chapter.updated_on} | ${chapter.reviewed_on} |`).join('\n')}`
  : 'No chapter currently has an editorial update newer than its scientific review date.'}
`;

if (process.argv.includes('--check')) {
  const current = readFileSync(output, 'utf8').replace(/\r\n/g, '\n');
  assert.equal(current, markdown, 'docs/content-inventory.md is stale; run npm run inventory');
} else {
  writeFileSync(output, markdown, 'utf8');
  console.log(`Content inventory written: ${rows.length} measures.`);
}
