// @ts-nocheck
const rNumber = (value) => Number(value).toPrecision(12).replace(/\.?0+$/, '');
const rVector = (values) => `c(${values.map(rNumber).join(', ')})`;

export function populationCsv(population) {
  const header = ['id', 'time', 'ipred', 'dv', 'CL', 'Vc', 'Q1', 'Vp1', 'Q2', 'Vp2', 'Ka'];
  const rows = population.profiles.flatMap((profile) => profile.points.map((point) => [
    profile.id, point.t, point.ipred, point.dv, profile.params.cl, profile.params.vc,
    profile.params.q1, profile.params.vp1, profile.params.q2, profile.params.vp2, profile.params.ka
  ]));
  return [header, ...rows].map((row) => row.join(',')).join('\n');
}

/** Generate an executable mrgsolve script matching the browser simulation design. */
export function simulationR(config, samplingTimes) {
  const compartments = [];
  if (config.route === 'oral_1st') {
    if (config.absorptionMode === 'transit') for (let index = 1; index <= config.nTransit; index += 1) compartments.push(`TR${index}`);
    compartments.push('GUT');
  }
  compartments.push('CENT');
  for (let index = 1; index < config.nCompartments; index += 1) compartments.push(`PERI${index}`);

  const parameters = [
    `TVCL=${rNumber(config.cl)}`, `TVVC=${rNumber(config.vc)}`, `TVKA=${rNumber(config.ka)}`,
    `TVQ1=${rNumber(config.q1)}`, `TVVP1=${rNumber(config.vp1)}`, `TVQ2=${rNumber(config.q2)}`, `TVVP2=${rNumber(config.vp2)}`,
    `LAG=${rNumber(config.lag)}`, `KTR=${rNumber((config.nTransit + 1) / config.mtt)}`,
    'ETA_CL=0', 'ETA_VC=0', 'ETA_KA=0', 'ETA_Q1=0', 'ETA_VP1=0', 'ETA_Q2=0', 'ETA_VP2=0', 'KAPPA_CL=0'
  ];
  const ode = [];
  let input = '0';
  if (config.route === 'oral_1st' && config.absorptionMode === 'transit') {
    ode.push('dxdt_TR1 = -KTR*TR1;');
    for (let index = 2; index <= config.nTransit; index += 1) ode.push(`dxdt_TR${index} = KTR*TR${index - 1} - KTR*TR${index};`);
    ode.push(`dxdt_GUT = KTR*TR${config.nTransit} - KA*GUT;`);
    input = 'KA*GUT';
  } else if (config.route === 'oral_1st') {
    ode.push('dxdt_GUT = -KA*GUT;');
    input = 'KA*GUT';
  }
  const losses = ['CL'];
  const returns = [];
  for (let index = 1; index < config.nCompartments; index += 1) {
    losses.push(`Q${index}`);
    returns.push(`Q${index}*PERI${index}/VP${index}`);
  }
  ode.push(`dxdt_CENT = ${input} - (${losses.join(' + ')})*CENT/VC${returns.length ? ` + ${returns.join(' + ')}` : ''};`);
  for (let index = 1; index < config.nCompartments; index += 1) ode.push(`dxdt_PERI${index} = Q${index}*CENT/VC - Q${index}*PERI${index}/VP${index};`);

  const model = [
    `$PARAM ${parameters.join(', ')}`,
    `$CMT ${compartments.join(' ')}`,
    '$MAIN',
    'double CL = TVCL*exp(ETA_CL + KAPPA_CL);',
    'double VC = TVVC*exp(ETA_VC);',
    'double KA = TVKA*exp(ETA_KA);',
    ...(config.nCompartments >= 2 ? ['double Q1 = TVQ1*exp(ETA_Q1);', 'double VP1 = TVVP1*exp(ETA_VP1);'] : []),
    ...(config.nCompartments >= 3 ? ['double Q2 = TVQ2*exp(ETA_Q2);', 'double VP2 = TVVP2*exp(ETA_VP2);'] : []),
    ...(config.route === 'oral_1st' && config.absorptionMode === 'lag' ? ['ALAG_GUT = LAG;'] : []),
    '$ODE', ...ode,
    `$SIGMA ${rNumber(config.resEnabled ? config.sigmaProp ** 2 : 0)} ${rNumber(config.resEnabled ? config.sigmaAdd ** 2 : 0)}`,
    '$TABLE',
    'double IPRED = CENT/VC;',
    'double DV = fmax(0.0, IPRED*(1.0 + EPS(1)) + EPS(2));',
    `$CAPTURE IPRED DV CL VC KA${config.nCompartments >= 2 ? ' Q1 VP1' : ''}${config.nCompartments >= 3 ? ' Q2 VP2' : ''}`
  ];
  const modelLines = model.map((line) => JSON.stringify(line)).join(',\n  ');
  const doseCompartment = config.route === 'oral_1st'
    ? config.absorptionMode === 'transit' ? 'TR1' : 'GUT' : 'CENT';
  const event = config.route === 'iv_infusion'
    ? `ev(amt = dose, cmt = "${doseCompartment}", rate = dose / ${rNumber(config.infusionDuration)})`
    : `ev(amt = dose, cmt = "${doseCompartment}")`;
  const omega = (enabled, value) => enabled ? rNumber(value) : '0';

  return `# Generated by Pharmacometrie Pratique - Simulation
# Model structure, population variability and residual error are explicit below.
library(mrgsolve)

set.seed(${Math.round(config.seed)})
n_subjects <- ${Math.round(config.nInd)}
dose <- ${rNumber(config.dose)}
t_end <- ${rNumber(config.tEnd)}
sampling_times <- ${rVector(samplingTimes)}

model_code <- paste(c(
  ${modelLines}
), collapse = "\\n")
mod <- mcode("poppk_simulation", model_code)

idata <- data.frame(
  ID = seq_len(n_subjects),
  ETA_CL = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaCL)}),
  ETA_VC = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaVc)}),
  ETA_KA = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaKa)}),
  ETA_Q1 = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaQ)}),
  ETA_VP1 = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaQ)}),
  ETA_Q2 = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaQ)}),
  ETA_VP2 = rnorm(n_subjects, 0, ${omega(config.iivEnabled, config.omegaQ)}),
  KAPPA_CL = rnorm(n_subjects, 0, ${omega(config.iovEnabled, config.kappaCL)})
)

dose_event <- ${event}
grid <- tgrid(0, t_end, delta = max(t_end / 500, 0.01), add = sampling_times)
mod <- idata_set(mod, idata)
mod <- ev(mod, dose_event)
simulation <- as.data.frame(mrgsim(mod, tgrid = grid))
keep <- vapply(simulation$time, function(value) any(abs(value - sampling_times) < 1e-8), logical(1))
columns <- c("ID", "time", "IPRED", "DV", "CL", "VC"${config.nCompartments >= 2 ? ', "Q1", "VP1"' : ''}${config.nCompartments >= 3 ? ', "Q2", "VP2"' : ''}, "KA")
simulation <- simulation[keep, columns]
simulation <- simulation[!duplicated(simulation[c("ID", "time")], fromLast = TRUE), ]
write.csv(simulation, "poppk_simulation_R.csv", row.names = FALSE)
simulation
`;
}

export function simulationRmd(config, samplingTimes, english = false) {
  const intro = english
    ? 'This notebook reproduces the selected population simulation with `mrgsolve`. The downloaded CSV is the browser result; the R simulation uses the same design and seed but its random-number stream is independent.'
    : 'Ce notebook reproduit la simulation de population selectionnee avec `mrgsolve`. Le CSV telecharge est le resultat du navigateur ; la simulation R utilise le meme plan et la meme graine, mais son flux aleatoire est independant.';
  return `---
title: "${english ? 'Population PK simulation' : 'Simulation PK de population'}"
output: html_document
---

${intro}

\`\`\`{r simulation, message=FALSE, warning=FALSE}
${simulationR(config, samplingTimes)}
\`\`\`
`;
}

export function downloadText(filename, text, type = 'text/plain;charset=utf-8') {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const link = document.createElement('a');
  link.href = url; link.download = filename; link.click();
  URL.revokeObjectURL(url);
}
